// Comprehensive JLPT N5 & N4 Official Simulation Question Banks

export const N5_SECTIONS_DATA = [
  {
    id: 'sec-vocab',
    title: 'Section 1: Language Knowledge (文字・語彙)',
    shortTitle: '文字・語彙 (Kanji & Vocab)',
    timeLimitSeconds: 20 * 60, // 20 minutes
    questions: [
      {
        id: 'n5-v-1',
        type: 'Kanji Reading (漢字読み)',
        question: 'あのおとこの　<u>ひと</u>は　だれですか。',
        options: ['木', '人', '入', '大'],
        correct: 1,
        explanation: '「ひと」is the kun\'yomi reading of「人」 (person).',
      },
      {
        id: 'n5-v-2',
        type: 'Kanji Reading (漢字読み)',
        question: 'まいあさ　<u>みず</u>を　のみます。',
        options: ['水', '木', '金', '土'],
        correct: 0,
        explanation: '「みず」is the kun\'yomi reading of「水」 (water).',
      },
      {
        id: 'n5-v-3',
        type: 'Kanji Reading (漢字読み)',
        question: 'きのう　ほんを　<u>さんさつ</u>　かいました。',
        options: ['三本', '三冊', '三枚', '三個'],
        correct: 1,
        explanation: '「さんさつ」(counter for bound books) is written as「三冊」.',
      },
      {
        id: 'n5-v-4',
        type: 'Kanji Reading (漢字読み)',
        question: '駅の　<u>まえ</u>で　待ち合わせを　しましょう。',
        options: ['後', '前', '上', '下'],
        correct: 1,
        explanation: '「まえ」(in front of / before) is written as「前」.',
      },
      {
        id: 'n5-v-5',
        type: 'Kanji Writing (表記)',
        question: 'えきまで　<u>あるいて</u>　いきました。',
        options: ['走って', '歩いて', '泳いで', '飛んで'],
        correct: 1,
        explanation: '「あるいて」comes from 歩く (to walk).',
      },
      {
        id: 'n5-v-6',
        type: 'Kanji Writing (表記)',
        question: '新しい　<u>くるま</u>を　かいました。',
        options: ['電車', '自転車', '車', '飛行機'],
        correct: 2,
        explanation: '「くるま」(car) is written as「車」.',
      },
      {
        id: 'n5-v-7',
        type: 'Contextual Vocabulary (文脈規定)',
        question: 'へやが　くらいですから、でんきを　（　）ください。',
        options: ['あけて', 'つけて', 'けして', 'しめて'],
        correct: 1,
        explanation: 'To turn on lights: 電気を【つける】 -> つけてください.',
      },
      {
        id: 'n5-v-8',
        type: 'Contextual Vocabulary (文脈規定)',
        question: 'あした　テストが　ありますから、こんばん　（　）します。',
        options: ['さんぽ', 'べんきょう', 'かいもの', 'りょこう'],
        correct: 1,
        explanation: 'Studying for an exam is 勉強 (べんきょう).',
      },
      {
        id: 'n5-v-9',
        type: 'Contextual Vocabulary (文脈規定)',
        question: 'ごはんを　たべるまえに、「（　）」と　言います。',
        options: ['ごちそうさまでした', 'いただきます', 'いってきます', 'おやすみなさい'],
        correct: 1,
        explanation: 'Before eating meals in Japan, you say「いただきます」.',
      },
      {
        id: 'n5-v-10',
        type: 'Paraphrases & Synonyms (類義語)',
        question: 'きょうは　<u>てんきがいい</u>です。',
        options: ['雨が降っています', '晴れています', '風が強いです', '雪が降っています'],
        correct: 1,
        explanation: '「てんきがいい」(good weather) is synonymous with「晴れています」(it is sunny).',
      },
    ],
  },
  {
    id: 'sec-grammar',
    title: 'Section 2: Grammar & Reading (文法・読解)',
    shortTitle: '文法・読解 (Grammar & Reading)',
    timeLimitSeconds: 40 * 60, // 40 minutes
    questions: [
      {
        id: 'n5-g-1',
        type: 'Grammar Structure (文法形式)',
        question: 'わたしは　毎朝　パン（　）食べます。',
        options: ['に', 'で', 'を', 'が'],
        correct: 2,
        explanation: 'The direct object marker is「を」.',
      },
      {
        id: 'n5-g-2',
        type: 'Grammar Structure (文法形式)',
        question: '日曜日、友達（　）映画を　見に行きました。',
        options: ['に', 'で', 'と', 'を'],
        correct: 2,
        explanation: 'Particle「と」indicates doing an action "together with" someone.',
      },
      {
        id: 'n5-g-3',
        type: 'Grammar Structure (文法形式)',
        question: '机の　上（　）本と　ペンが　あります。',
        options: ['に', 'で', 'を', 'へ'],
        correct: 0,
        explanation: 'Particle「に」indicates the location where an object exists (あります).',
      },
      {
        id: 'n5-g-4',
        type: 'Grammar Structure (文法形式)',
        question: 'すみませんが、この言葉の意味を（　）ください。',
        options: ['教えて', '教える', '教えた', '教え'],
        correct: 0,
        explanation: 'Polite request uses Verb [て-form] + ください: 教えてください.',
      },
      {
        id: 'n5-g-5',
        type: 'Grammar Structure (文法形式)',
        question: '日本へ　桜を（　）行きたいです。',
        options: ['見に', '見るに', '見て', '見た'],
        correct: 0,
        explanation: 'Purpose of movement uses Verb [ます-stem] + に行く: 見に行く.',
      },
      {
        id: 'n5-g-6',
        type: 'Sentence Re-arrangement (文の組み立て ★)',
        question: 'わたしは　スーパーへ　＿＿＿　＿＿＿　＿★＿　＿＿＿　行きました。',
        options: ['りんごを', '買い', 'に', '３個'],
        correct: 2,
        explanation: 'Correct sentence order: りんごを (1) ３個 (4) 買い (2) に (3) 行きました. Star (★) is at position 3 (に).',
      },
      {
        id: 'n5-g-7',
        type: 'Sentence Re-arrangement (文の組み立て ★)',
        question: '昨日は　＿＿＿　＿＿＿　＿★＿　＿＿＿　寝ました。',
        options: ['お風呂に', 'から', '入って', '早く'],
        correct: 1,
        explanation: 'Correct order: お風呂に (1) 入って (3) から (2) 早く (4) 寝ました. Star (★) is at position 3 (から).',
      },
      {
        id: 'n5-g-8',
        type: 'Reading Comprehension - Short Passage (短文読解)',
        question: '【メモ】\n山田さんへ\n今日の会議は３階の会議室で午後２時から始まります。\n資料は机の上に置いてありますから、２部持ってきてください。\n佐藤より\n\n質問：山田さんは何をしなければなりませんか。',
        options: ['２階の部屋に行くこと', '資料を２部持って会議室に行くこと', '会議の資料を作ること', '佐藤さんに電話をかけること'],
        correct: 1,
        explanation: 'The memo explicitly asks:「資料は机の上に置いてありますから、２部持ってきてください」(Please bring 2 copies of the handout).',
      },
      {
        id: 'n5-g-9',
        type: 'Reading Comprehension - Notice / Sign (情報検索)',
        question: '【図書館の案内】\n開館時間：午前９時〜午後６時\n休館日：毎週月曜日（月曜日が祝日の場合は火曜日が休み）\n本の貸出：１人５冊まで（２週間）\n\n質問：火曜日が祝日で月曜日が平日の場合、図書館は何曜日が休みですか。',
        options: ['月曜日', '火曜日', '水曜日', '休みはない'],
        correct: 0,
        explanation: 'Since Monday is a regular weekday, the library is closed on its regular closing day: 月曜日.',
      },
    ],
  },
  {
    id: 'sec-listening',
    title: 'Section 3: Listening Comprehension (聴解)',
    shortTitle: '聴解 (Listening)',
    timeLimitSeconds: 30 * 60, // 30 minutes
    questions: [
      {
        id: 'n5-l-1',
        type: 'Task-Based Comprehension (課題理解)',
        audioTrackId: 'n5-a-1',
        audioSrc: '/audio/japanese/n5/captured-media-0-mp3.mp3',
        question: '男の人と女の人が話しています。男の人はこの後、まず何をしますか。',
        options: ['窓を閉める', '電気を消す', 'ゴミを捨てる', 'ドアにカギをかける'],
        correct: 0,
        explanation: 'In the audio dialogue, the instructions state to close all windows first before locking the doors.',
      },
      {
        id: 'n5-l-2',
        type: 'Point Comprehension (ポイント理解)',
        audioTrackId: 'n5-a-2',
        audioSrc: '/audio/japanese/n5/captured-media-1-mp3.mp3',
        question: '女の人は何時に駅で友達と会いますか。',
        options: ['１時', '１時半', '２時', '２時半'],
        correct: 1,
        explanation: 'They agree to meet at 1:30 (１時半).',
      },
      {
        id: 'n5-l-3',
        type: 'Utterance Expressions (発話表現)',
        audioTrackId: 'n5-a-3',
        audioSrc: '/audio/japanese/n5/captured-media-2-mp3.mp3',
        question: 'レストランで料理を注文します。何と言いますか。',
        options: ['ごちそうさまでした', 'これをください', 'いただきます', 'いらっしゃいませ'],
        correct: 1,
        explanation: 'When ordering food at a restaurant, you say「これをください」(Please give me this one).',
      },
      {
        id: 'n5-l-4',
        type: 'Quick Response (即時応答)',
        audioTrackId: 'n5-a-4',
        audioSrc: '/audio/japanese/n5/captured-media-3-mp3.mp3',
        question: '「お茶をもう一杯いかがですか。」',
        options: ['はい、もう一杯です。', 'いいえ、けっこうです。', 'どういたしまして。', 'おめでとうございます。'],
        correct: 1,
        explanation: 'Politely declining a second cup of tea:「いいえ、けっこうです」(No thank you, I am fine).',
      },
    ],
  },
];

export const N4_SECTIONS_DATA = [
  {
    id: 'sec-vocab-n4',
    title: 'Section 1: Language Knowledge (文字・語彙)',
    shortTitle: '文字・語彙 (Kanji & Vocab)',
    timeLimitSeconds: 25 * 60, // 25 minutes
    questions: [
      {
        id: 'n4-v-1',
        type: 'Kanji Reading (漢字読み)',
        question: '明日の　<u>かいぎ</u>は　１０時からです。',
        options: ['会社', '会議', '会場', '会話'],
        correct: 1,
        explanation: '「かいぎ」(meeting) is written as「会議」.',
      },
      {
        id: 'n4-v-2',
        type: 'Kanji Reading (漢字読み)',
        question: 'この車は　<u>うんてん</u>が　しやすいです。',
        options: ['運転', '運搬', '運動', '運賃'],
        correct: 0,
        explanation: '「うんてん」(driving/operation) is written as「運転」.',
      },
      {
        id: 'n4-v-3',
        type: 'Kanji Writing (表記)',
        question: '機械の　<u>こしょう</u>を　直します。',
        options: ['故郷', '故障', '工場', '校長'],
        correct: 1,
        explanation: '「こしょう」(breakdown/malfunction) is written as「故障」.',
      },
      {
        id: 'n4-v-4',
        type: 'Contextual Vocabulary (文脈規定)',
        question: '作業を始める前に、必ず　安全を　（　）してください。',
        options: ['確認', '案内', '連絡', '相談'],
        correct: 0,
        explanation: 'Confirming or checking safety is 確認 (かくにん).',
      },
      {
        id: 'n4-v-5',
        type: 'Contextual Vocabulary (文脈規定)',
        question: 'この道具は　とても（　）ので、気をつけて使ってください。',
        options: ['危険な', '安全な', '静かな', '便利な'],
        correct: 0,
        explanation: 'Dangerous tools require care: 危険な (きけんな).',
      },
      {
        id: 'n4-v-6',
        type: 'Paraphrases & Synonyms (類義語)',
        question: '田中さんに　<u>手伝ってもらいました</u>。',
        options: ['田中さんを助けました', '田中さんが手伝ってくれました', '田中さんに教えました', '田中さんに頼みました'],
        correct: 1,
        explanation: '「手伝ってもらいました」means Tanaka-san kindly helped me (手伝ってくれました).',
      },
    ],
  },
  {
    id: 'sec-grammar-n4',
    title: 'Section 2: Grammar & Reading (文法・読解)',
    shortTitle: '文法・読解 (Grammar & Reading)',
    timeLimitSeconds: 55 * 60, // 55 minutes
    questions: [
      {
        id: 'n4-g-1',
        type: 'Grammar Structure (文法形式)',
        question: 'この靴は　軽くて　とても（　）やすいです。',
        options: ['歩き', '歩く', '歩いて', '歩いた'],
        correct: 0,
        explanation: 'The suffix「〜やすい」attaches to Verb [ます-stem]: 歩きやすい (easy to walk in).',
      },
      {
        id: 'n4-g-2',
        type: 'Grammar Structure (文法形式)',
        question: '時間が　（　）なら、手伝ってください。',
        options: ['ある', 'あった', 'あって', 'あります'],
        correct: 0,
        explanation: 'Conditional「なら」attaches to dictionary form: あるなら.',
      },
      {
        id: 'n4-g-3',
        type: 'Grammar Structure (文法形式)',
        question: '弟は　母に　部屋を　掃除（　）。',
        options: ['させられました', 'させました', 'されました', 'しました'],
        correct: 0,
        explanation: 'Causative-passive form indicates being made to clean: 掃除させられました.',
      },
      {
        id: 'n4-g-4',
        type: 'Grammar Structure (文法形式)',
        question: '日本語の新聞が　（　）ようになりました。',
        options: ['読める', '読む', '読んだ', '読まない'],
        correct: 0,
        explanation: 'Becoming able to do something uses Potential form + ようになる: 読めるようになる.',
      },
      {
        id: 'n4-g-5',
        type: 'Sentence Re-arrangement (文の組み立て ★)',
        question: '先生に　＿＿＿　＿＿＿　＿★＿　＿＿＿　言われました。',
        options: ['宿題を', '忘れない', 'ように', 'と'],
        correct: 2,
        explanation: 'Correct order: 宿題を (1) 忘れない (2) ように (3) と (4) 言われました. Star (★) is at position 3 (ように).',
      },
      {
        id: 'n4-g-6',
        type: 'Reading Comprehension - Workplace Notice (実務読解)',
        question: '【工場点検のお知らせ】\n点検日時：８月２５日（金）午前９時〜午後４時\n注意事項：\n１．作業中は必ずヘルメットと安全靴を着用すること。\n２．点検箇所の周囲には立ち入らないこと。\n３．緊急時はインターホンで管理室（内線３０２）に連絡すること。\n\n質問：点検中に緊急事態が起きた場合、どうすればいいですか。',
        options: ['管理室に電話（内線３０２）で連絡する', 'ヘルメットを脱いで待機する', '点検箇所の周囲に入る', '午後４時まで待つ'],
        correct: 0,
        explanation: 'Instruction 3 says:「緊急時はインターホンで管理室（内線３０２）に連絡すること」.',
      },
    ],
  },
  {
    id: 'sec-listening-n4',
    title: 'Section 3: Listening Comprehension (聴解)',
    shortTitle: '聴解 (Listening)',
    timeLimitSeconds: 35 * 60, // 35 minutes
    questions: [
      {
        id: 'n4-l-1',
        type: 'Task-Based Comprehension (課題理解)',
        audioTrackId: 'n4-a-1',
        audioSrc: '/audio/japanese/n4/captured-media-0-mp3.mp3',
        question: '会社で男の人と女の人が話しています。男の人はこれから何を準備しますか。',
        options: ['会議の資料をコピーする', '部屋の机を並べる', 'お茶を用意する', 'プロジェクターをつなぐ'],
        correct: 0,
        explanation: 'The manager requests making copies of the handouts first.',
      },
      {
        id: 'n4-l-2',
        type: 'Point Comprehension (ポイント理解)',
        audioTrackId: 'n4-a-2',
        audioSrc: '/audio/japanese/n4/captured-media-1-mp3.mp3',
        question: '男の人はどうして昨日会社を休みましたか。',
        options: ['熱があったから', '電車が止まったから', '病院で検査があったから', '家族の用事があったから'],
        correct: 0,
        explanation: 'He took the day off due to having a fever (熱があった).',
      },
      {
        id: 'n4-l-3',
        type: 'Utterance Expressions (発話表現)',
        audioTrackId: 'n4-a-3',
        audioSrc: '/audio/japanese/n4/captured-media-2-mp3.mp3',
        question: '仕事が終わって先に帰ります。同僚に何と言いますか。',
        options: ['お先に失礼します', 'いってきます', 'ただいま', 'おかえりなさい'],
        correct: 0,
        explanation: 'When leaving the workplace before others, you say「お先に失礼します」.',
      },
      {
        id: 'n4-l-4',
        type: 'Quick Response (即時応答)',
        audioTrackId: 'n4-a-4',
        audioSrc: '/audio/japanese/n4/captured-media-3-mp3.mp3',
        question: '「その荷物、重そうですね。手伝いましょうか。」',
        options: ['いいえ、重くありません。', 'すみません、助かります。', 'こちらこそ。', '気をつけてください。'],
        correct: 1,
        explanation: 'Accepting an offer of assistance:「すみません、助かります」.',
      },
    ],
  },
];

// Fallback legacy flat exports
export const N5_EXAM_QUESTIONS = N5_SECTIONS_DATA.flatMap((s) => s.questions);
export const N4_EXAM_QUESTIONS = N4_SECTIONS_DATA.flatMap((s) => s.questions);
