// Generated complete Verbs datasets for JLPT N5 and N4
export const N5_VERBS = [
  {
    "id": "n5-v-1",
    "number": 1,
    "jp": "浴びる",
    "romaji": "abiru",
    "meaning": "to bathe, to shower",
    "masuForm": "浴びます",
    "naiForm": "浴びない",
    "taForm": "浴びた",
    "level": "N5"
  },
  {
    "id": "n5-v-2",
    "number": 2,
    "jp": "上げる",
    "romaji": "ageru",
    "meaning": "to raise; to elevate",
    "masuForm": "上げます",
    "naiForm": "上げない",
    "taForm": "上げた",
    "level": "N5"
  },
  {
    "id": "n5-v-3",
    "number": 3,
    "jp": "開ける",
    "romaji": "akeru",
    "meaning": "to open",
    "masuForm": "開けます",
    "naiForm": "開けない",
    "taForm": "開けた",
    "level": "N5"
  },
  {
    "id": "n5-v-4",
    "number": 4,
    "jp": "開く",
    "romaji": "aku",
    "meaning": "to open",
    "masuForm": "開きます",
    "naiForm": "開かない",
    "taForm": "開いた",
    "level": "N5"
  },
  {
    "id": "n5-v-5",
    "number": 5,
    "jp": "洗う",
    "romaji": "arau",
    "meaning": "to wash",
    "masuForm": "洗います",
    "naiForm": "洗わない",
    "taForm": "洗った",
    "level": "N5"
  },
  {
    "id": "n5-v-6",
    "number": 6,
    "jp": "ある",
    "romaji": "aru",
    "meaning": "to be, to have",
    "masuForm": "あります",
    "naiForm": "あった",
    "taForm": "",
    "level": "N5"
  },
  {
    "id": "n5-v-7",
    "number": 7,
    "jp": "歩く",
    "romaji": "aruku",
    "meaning": "to walk",
    "masuForm": "歩きます",
    "naiForm": "歩かない",
    "taForm": "歩いた",
    "level": "N5"
  },
  {
    "id": "n5-v-8",
    "number": 8,
    "jp": "遊ぶ",
    "romaji": "asobu",
    "meaning": "to play",
    "masuForm": "遊びます",
    "naiForm": "遊ばない",
    "taForm": "遊んだ",
    "level": "N5"
  },
  {
    "id": "n5-v-9",
    "number": 9,
    "jp": "会う",
    "romaji": "au",
    "meaning": "to meet",
    "masuForm": "会います",
    "naiForm": "会わない",
    "taForm": "会った",
    "level": "N5"
  },
  {
    "id": "n5-v-10",
    "number": 10,
    "jp": "勉強をする",
    "romaji": "benkyou o suru",
    "meaning": "to study",
    "masuForm": "勉強をします",
    "naiForm": "勉強をしない",
    "taForm": "勉強をした",
    "level": "N5"
  },
  {
    "id": "n5-v-11",
    "number": 11,
    "jp": "違う",
    "romaji": "chigau",
    "meaning": "to differ",
    "masuForm": "違います",
    "naiForm": "違わない",
    "taForm": "違った",
    "level": "N5"
  },
  {
    "id": "n5-v-12",
    "number": 12,
    "jp": "出す",
    "romaji": "dasu",
    "meaning": "to take out; to get out;",
    "masuForm": "出します",
    "naiForm": "出さない",
    "taForm": "出した",
    "level": "N5"
  },
  {
    "id": "n5-v-13",
    "number": 13,
    "jp": "出かける",
    "romaji": "dekakeru",
    "meaning": "to go out; to leave; to depart",
    "masuForm": "出かけます",
    "naiForm": "出かけない",
    "taForm": "出かけた",
    "level": "N5"
  },
  {
    "id": "n5-v-14",
    "number": 14,
    "jp": "電話をする",
    "romaji": "denwa o suru",
    "meaning": "to call",
    "masuForm": "電話をします",
    "naiForm": "電話をしない",
    "taForm": "電話をした",
    "level": "N5"
  },
  {
    "id": "n5-v-15",
    "number": 15,
    "jp": "出る",
    "romaji": "deru",
    "meaning": "to leave; to exit Present Negative Past Positive",
    "masuForm": "出ます",
    "naiForm": "出ない",
    "taForm": "出た",
    "level": "N5"
  },
  {
    "id": "n5-v-16",
    "number": 16,
    "jp": "吹く",
    "romaji": "fuku",
    "meaning": "to blow",
    "masuForm": "吹きます",
    "naiForm": "吹かない",
    "taForm": "吹いた",
    "level": "N5"
  },
  {
    "id": "n5-v-17",
    "number": 17,
    "jp": "降る",
    "romaji": "furu",
    "meaning": "to fall",
    "masuForm": "降ります",
    "naiForm": "降らない",
    "taForm": "降った",
    "level": "N5"
  },
  {
    "id": "n5-v-18",
    "number": 18,
    "jp": "入る",
    "romaji": "hairu",
    "meaning": "to enter; to go into",
    "masuForm": "入ります",
    "naiForm": "入らない",
    "taForm": "入った",
    "level": "N5"
  },
  {
    "id": "n5-v-19",
    "number": 19,
    "jp": "始まる",
    "romaji": "hajimaru",
    "meaning": "to begin",
    "masuForm": "始まります",
    "naiForm": "始まらない",
    "taForm": "始まった",
    "level": "N5"
  },
  {
    "id": "n5-v-20",
    "number": 20,
    "jp": "履く",
    "romaji": "haku",
    "meaning": "to wear, to put on trousers",
    "masuForm": "履きます",
    "naiForm": "履かない",
    "taForm": "履いた",
    "level": "N5"
  },
  {
    "id": "n5-v-21",
    "number": 21,
    "jp": "話す",
    "romaji": "hanasu",
    "meaning": "to speak; to talk",
    "masuForm": "話します",
    "naiForm": "話さない",
    "taForm": "話した",
    "level": "N5"
  },
  {
    "id": "n5-v-22",
    "number": 22,
    "jp": "晴れる",
    "romaji": "hareru",
    "meaning": "to be sunny",
    "masuForm": "晴れます",
    "naiForm": "晴れない",
    "taForm": "晴れた",
    "level": "N5"
  },
  {
    "id": "n5-v-23",
    "number": 23,
    "jp": "貼る",
    "romaji": "haru",
    "meaning": "to stick; to paste",
    "masuForm": "貼ります",
    "naiForm": "貼らない",
    "taForm": "貼った",
    "level": "N5"
  },
  {
    "id": "n5-v-24",
    "number": 24,
    "jp": "走る",
    "romaji": "hashiru",
    "meaning": "to run",
    "masuForm": "走ります",
    "naiForm": "走らない",
    "taForm": "走った",
    "level": "N5"
  },
  {
    "id": "n5-v-25",
    "number": 25,
    "jp": "働く",
    "romaji": "hataraku",
    "meaning": "to work",
    "masuForm": "働きます",
    "naiForm": "働かない",
    "taForm": "働いた",
    "level": "N5"
  },
  {
    "id": "n5-v-26",
    "number": 26,
    "jp": "引く",
    "romaji": "hiku",
    "meaning": "to pull",
    "masuForm": "引きます",
    "naiForm": "引かない",
    "taForm": "引いた",
    "level": "N5"
  },
  {
    "id": "n5-v-27",
    "number": 27,
    "jp": "弾く",
    "romaji": "hiku",
    "meaning": "to play",
    "masuForm": "弾きます",
    "naiForm": "弾かない",
    "taForm": "弾いた",
    "level": "N5"
  },
  {
    "id": "n5-v-28",
    "number": 28,
    "jp": "行く",
    "romaji": "iku",
    "meaning": "to go; to move",
    "masuForm": "行きます",
    "naiForm": "行かない",
    "taForm": "行った",
    "level": "N5"
  },
  {
    "id": "n5-v-29",
    "number": 29,
    "jp": "入れる",
    "romaji": "ireru",
    "meaning": "to put in; to let in",
    "masuForm": "入れます",
    "naiForm": "入れない",
    "taForm": "入れた",
    "level": "N5"
  },
  {
    "id": "n5-v-30",
    "number": 30,
    "jp": "居る",
    "romaji": "iru",
    "meaning": "to be, to have",
    "masuForm": "居ます",
    "naiForm": "居ない",
    "taForm": "居た",
    "level": "N5"
  },
  {
    "id": "n5-v-31",
    "number": 31,
    "jp": "要る",
    "romaji": "iru",
    "meaning": "to be needed Present Negative Past Positive",
    "masuForm": "要ります",
    "naiForm": "要らない",
    "taForm": "要った",
    "level": "N5"
  },
  {
    "id": "n5-v-32",
    "number": 32,
    "jp": "言う",
    "romaji": "iu",
    "meaning": "to say; to call",
    "masuForm": "言います",
    "naiForm": "言わない",
    "taForm": "言った",
    "level": "N5"
  },
  {
    "id": "n5-v-33",
    "number": 33,
    "jp": "授業をする",
    "romaji": "jugyou o suru",
    "meaning": "to give a lecture",
    "masuForm": "授業をします",
    "naiForm": "授業をしない",
    "taForm": "授業をした",
    "level": "N5"
  },
  {
    "id": "n5-v-34",
    "number": 34,
    "jp": "帰る",
    "romaji": "kaeru",
    "meaning": "-",
    "masuForm": "to go back​",
    "naiForm": "かえります",
    "taForm": "かえらない",
    "level": "N5"
  },
  {
    "id": "n5-v-35",
    "number": 35,
    "jp": "返す",
    "romaji": "kaesu",
    "meaning": "to return something",
    "masuForm": "返します",
    "naiForm": "返さない",
    "taForm": "返した",
    "level": "N5"
  },
  {
    "id": "n5-v-36",
    "number": 36,
    "jp": "掛かる",
    "romaji": "kakaru",
    "meaning": "to take (time, money)",
    "masuForm": "掛かります",
    "naiForm": "掛からない",
    "taForm": "掛かった",
    "level": "N5"
  },
  {
    "id": "n5-v-37",
    "number": 37,
    "jp": "掛ける",
    "romaji": "kakeru",
    "meaning": "to hang up; to",
    "masuForm": "make (a call)​;",
    "naiForm": "かけます",
    "taForm": "かけない",
    "level": "N5"
  },
  {
    "id": "n5-v-38",
    "number": 38,
    "jp": "書く",
    "romaji": "kaku",
    "meaning": "to write",
    "masuForm": "書きます",
    "naiForm": "書かない",
    "taForm": "書いた",
    "level": "N5"
  },
  {
    "id": "n5-v-39",
    "number": 39,
    "jp": "借りる",
    "romaji": "kariru",
    "meaning": "to borrow",
    "masuForm": "借ります",
    "naiForm": "借りない",
    "taForm": "借りた",
    "level": "N5"
  },
  {
    "id": "n5-v-40",
    "number": 40,
    "jp": "貸す",
    "romaji": "kasu",
    "meaning": "to lend; to loan",
    "masuForm": "貸します",
    "naiForm": "貸さない",
    "taForm": "貸した",
    "level": "N5"
  },
  {
    "id": "n5-v-41",
    "number": 41,
    "jp": "買う",
    "romaji": "kau",
    "meaning": "to buy; to purchase",
    "masuForm": "買います",
    "naiForm": "買わない",
    "taForm": "買った",
    "level": "N5"
  },
  {
    "id": "n5-v-42",
    "number": 42,
    "jp": "結婚をする",
    "romaji": "kekkon o suru",
    "meaning": "to marry",
    "masuForm": "結婚をします",
    "naiForm": "結婚をしない",
    "taForm": "結婚をした",
    "level": "N5"
  },
  {
    "id": "n5-v-43",
    "number": 43,
    "jp": "消す",
    "romaji": "kesu",
    "meaning": "to erase, to turn off power",
    "masuForm": "消します",
    "naiForm": "消さない",
    "taForm": "消した",
    "level": "N5"
  },
  {
    "id": "n5-v-44",
    "number": 44,
    "jp": "消える",
    "romaji": "kieru",
    "meaning": "to disappear",
    "masuForm": "消えます",
    "naiForm": "消えない",
    "taForm": "消えた",
    "level": "N5"
  },
  {
    "id": "n5-v-45",
    "number": 45,
    "jp": "聞く",
    "romaji": "kiku",
    "meaning": "to hear; to listen; to ask",
    "masuForm": "聞きます",
    "naiForm": "聞かない",
    "taForm": "聞いた",
    "level": "N5"
  },
  {
    "id": "n5-v-46",
    "number": 46,
    "jp": "切る",
    "romaji": "kiru",
    "meaning": "to cut",
    "masuForm": "切ります",
    "naiForm": "切らない",
    "taForm": "切った",
    "level": "N5"
  },
  {
    "id": "n5-v-47",
    "number": 47,
    "jp": "着る",
    "romaji": "kiru",
    "meaning": "to wear Present Negative Past Positive",
    "masuForm": "着ます",
    "naiForm": "着ない",
    "taForm": "着た",
    "level": "N5"
  },
  {
    "id": "n5-v-48",
    "number": 48,
    "jp": "困る",
    "romaji": "komaru",
    "meaning": "to be troubled",
    "masuForm": "困ります",
    "naiForm": "困らない",
    "taForm": "困った",
    "level": "N5"
  },
  {
    "id": "n5-v-49",
    "number": 49,
    "jp": "コピーをする",
    "romaji": "kopii o suru",
    "meaning": "to copy",
    "masuForm": "コピーをします",
    "naiForm": "コピーをした",
    "taForm": "",
    "level": "N5"
  },
  {
    "id": "n5-v-50",
    "number": 50,
    "jp": "答える",
    "romaji": "kotaeru",
    "meaning": "to answer",
    "masuForm": "答えます",
    "naiForm": "答えない",
    "taForm": "答えた",
    "level": "N5"
  },
  {
    "id": "n5-v-51",
    "number": 51,
    "jp": "曇る",
    "romaji": "kumoru",
    "meaning": "to become cloudy",
    "masuForm": "曇ります",
    "naiForm": "曇らない",
    "taForm": "曇った",
    "level": "N5"
  },
  {
    "id": "n5-v-52",
    "number": 52,
    "jp": "来る",
    "romaji": "kuru",
    "meaning": "to come",
    "masuForm": "来ます",
    "naiForm": "来ない",
    "taForm": "来た",
    "level": "N5"
  },
  {
    "id": "n5-v-53",
    "number": 53,
    "jp": "曲がる",
    "romaji": "magaru",
    "meaning": "to turn, to bend",
    "masuForm": "曲ります",
    "naiForm": "曲らない",
    "taForm": "曲った",
    "level": "N5"
  },
  {
    "id": "n5-v-54",
    "number": 54,
    "jp": "待つ",
    "romaji": "matsu",
    "meaning": "-",
    "masuForm": "to wait​",
    "naiForm": "まちます",
    "taForm": "またない",
    "level": "N5"
  },
  {
    "id": "n5-v-55",
    "number": 55,
    "jp": "磨く",
    "romaji": "migaku",
    "meaning": "to polish; to brush (teeth)",
    "masuForm": "磨きます",
    "naiForm": "磨かない",
    "taForm": "磨いた",
    "level": "N5"
  },
  {
    "id": "n5-v-56",
    "number": 56,
    "jp": "見る",
    "romaji": "miru",
    "meaning": "to see; to look",
    "masuForm": "見ます",
    "naiForm": "見ない",
    "taForm": "見た",
    "level": "N5"
  },
  {
    "id": "n5-v-57",
    "number": 57,
    "jp": "見せる",
    "romaji": "miseru",
    "meaning": "to show; to display",
    "masuForm": "見せます",
    "naiForm": "見せない",
    "taForm": "見せた",
    "level": "N5"
  },
  {
    "id": "n5-v-58",
    "number": 58,
    "jp": "持つ",
    "romaji": "motsu",
    "meaning": "to hold",
    "masuForm": "持ちます",
    "naiForm": "持たない",
    "taForm": "持った",
    "level": "N5"
  },
  {
    "id": "n5-v-59",
    "number": 59,
    "jp": "鳴く",
    "romaji": "naku",
    "meaning": "animal noise. to chirp",
    "masuForm": "鳴きます",
    "naiForm": "鳴かない",
    "taForm": "鳴いた",
    "level": "N5"
  },
  {
    "id": "n5-v-60",
    "number": 60,
    "jp": "無くす",
    "romaji": "nakusu",
    "meaning": "to lose (something)",
    "masuForm": "無くします",
    "naiForm": "無くさない",
    "taForm": "無くした",
    "level": "N5"
  },
  {
    "id": "n5-v-61",
    "number": 61,
    "jp": "並べる",
    "romaji": "naraberu",
    "meaning": "to line up, to set up",
    "masuForm": "並べます",
    "naiForm": "並べない",
    "taForm": "並べた",
    "level": "N5"
  },
  {
    "id": "n5-v-62",
    "number": 62,
    "jp": "並ぶ",
    "romaji": "narabu",
    "meaning": "to line up",
    "masuForm": "並びます",
    "naiForm": "並ばない",
    "taForm": "並んだ",
    "level": "N5"
  },
  {
    "id": "n5-v-63",
    "number": 63,
    "jp": "習う",
    "romaji": "narau",
    "meaning": "to be taught; to learn Present Negative Past Positive",
    "masuForm": "習います",
    "naiForm": "習わない",
    "taForm": "習った",
    "level": "N5"
  },
  {
    "id": "n5-v-64",
    "number": 64,
    "jp": "寝る",
    "romaji": "neru",
    "meaning": "to sleep",
    "masuForm": "寝ます",
    "naiForm": "寝ない",
    "taForm": "寝た",
    "level": "N5"
  },
  {
    "id": "n5-v-65",
    "number": 65,
    "jp": "登る",
    "romaji": "noboru",
    "meaning": "to climb",
    "masuForm": "登ります",
    "naiForm": "登らない",
    "taForm": "登った",
    "level": "N5"
  },
  {
    "id": "n5-v-66",
    "number": 66,
    "jp": "飲む",
    "romaji": "nomu",
    "meaning": "to drink",
    "masuForm": "飲みます",
    "naiForm": "飲まない",
    "taForm": "飲んだ",
    "level": "N5"
  },
  {
    "id": "n5-v-67",
    "number": 67,
    "jp": "乗る",
    "romaji": "noru",
    "meaning": "to get on (train, plane,  etc.)",
    "masuForm": "乗ります",
    "naiForm": "乗らない",
    "taForm": "乗った",
    "level": "N5"
  },
  {
    "id": "n5-v-68",
    "number": 68,
    "jp": "脱ぐ",
    "romaji": "nugu",
    "meaning": "to take off clothes",
    "masuForm": "脱ぎます",
    "naiForm": "脱がない",
    "taForm": "脱いだ",
    "level": "N5"
  },
  {
    "id": "n5-v-69",
    "number": 69,
    "jp": "覚える",
    "romaji": "oboeru",
    "meaning": "to remember",
    "masuForm": "覚えます",
    "naiForm": "覚えない",
    "taForm": "覚えた",
    "level": "N5"
  },
  {
    "id": "n5-v-70",
    "number": 70,
    "jp": "起きる",
    "romaji": "okiru",
    "meaning": "to get up; to wake up",
    "masuForm": "起きます",
    "naiForm": "起きない",
    "taForm": "起きた",
    "level": "N5"
  },
  {
    "id": "n5-v-71",
    "number": 71,
    "jp": "置く",
    "romaji": "oku",
    "meaning": "-",
    "masuForm": "to put; to place​",
    "naiForm": "おきます",
    "taForm": "おかない",
    "level": "N5"
  },
  {
    "id": "n5-v-72",
    "number": 72,
    "jp": "降りる",
    "romaji": "oriru",
    "meaning": "to get off",
    "masuForm": "降ります",
    "naiForm": "降りない",
    "taForm": "降りた",
    "level": "N5"
  },
  {
    "id": "n5-v-73",
    "number": 73,
    "jp": "教える",
    "romaji": "oshieru",
    "meaning": "to teach",
    "masuForm": "教えます",
    "naiForm": "教えない",
    "taForm": "教えた",
    "level": "N5"
  },
  {
    "id": "n5-v-74",
    "number": 74,
    "jp": "押す",
    "romaji": "osu",
    "meaning": "-",
    "masuForm": "to push; to press​",
    "naiForm": "おします",
    "taForm": "おさない",
    "level": "N5"
  },
  {
    "id": "n5-v-75",
    "number": 75,
    "jp": "終る",
    "romaji": "owaru",
    "meaning": "to finish; to end",
    "masuForm": "終わります",
    "naiForm": "終わらない",
    "taForm": "終わった",
    "level": "N5"
  },
  {
    "id": "n5-v-76",
    "number": 76,
    "jp": "泳ぐ",
    "romaji": "oyogu",
    "meaning": "to swim",
    "masuForm": "泳ぎます",
    "naiForm": "泳がない",
    "taForm": "泳いだ",
    "level": "N5"
  },
  {
    "id": "n5-v-77",
    "number": 77,
    "jp": "練習をする",
    "romaji": "renshuu o suru",
    "meaning": "to practice",
    "masuForm": "練習をします",
    "naiForm": "練習をしない",
    "taForm": "練習をした",
    "level": "N5"
  },
  {
    "id": "n5-v-78",
    "number": 78,
    "jp": "旅行をする",
    "romaji": "ryokou o suru",
    "meaning": "to travel",
    "masuForm": "旅行をします",
    "naiForm": "旅行をしない",
    "taForm": "旅行をした",
    "level": "N5"
  },
  {
    "id": "n5-v-79",
    "number": 79,
    "jp": "料理をする",
    "romaji": "ryouri o suru",
    "meaning": "to cook Present Negative Past Positive",
    "masuForm": "料理をします",
    "naiForm": "料理をしない",
    "taForm": "料理をした",
    "level": "N5"
  },
  {
    "id": "n5-v-80",
    "number": 80,
    "jp": "咲く",
    "romaji": "saku",
    "meaning": "to bloom",
    "masuForm": "咲きます",
    "naiForm": "咲かない",
    "taForm": "咲いた",
    "level": "N5"
  },
  {
    "id": "n5-v-81",
    "number": 81,
    "jp": "散歩をする",
    "romaji": "sanpo o suru",
    "meaning": "to go for a walk",
    "masuForm": "散歩をします",
    "naiForm": "散歩をしない",
    "taForm": "散歩をした",
    "level": "N5"
  },
  {
    "id": "n5-v-82",
    "number": 82,
    "jp": "差す",
    "romaji": "sasu",
    "meaning": "to stretch out hands, to raise an umbrella",
    "masuForm": "差します",
    "naiForm": "差さない",
    "taForm": "差した",
    "level": "N5"
  },
  {
    "id": "n5-v-83",
    "number": 83,
    "jp": "洗濯をする",
    "romaji": "sentaku o suru",
    "meaning": "to wash laundry",
    "masuForm": "洗濯をします",
    "naiForm": "洗濯をしない",
    "taForm": "洗濯をした",
    "level": "N5"
  },
  {
    "id": "n5-v-84",
    "number": 84,
    "jp": "仕事をする",
    "romaji": "shigoto o suru",
    "meaning": "to work",
    "masuForm": "仕事をします",
    "naiForm": "仕事をしない",
    "taForm": "仕事をした",
    "level": "N5"
  },
  {
    "id": "n5-v-85",
    "number": 85,
    "jp": "閉まる",
    "romaji": "shimaru",
    "meaning": "to close, to be closed",
    "masuForm": "閉まります",
    "naiForm": "閉まらない",
    "taForm": "閉まった",
    "level": "N5"
  },
  {
    "id": "n5-v-86",
    "number": 86,
    "jp": "締める",
    "romaji": "shimeru",
    "meaning": "to tie; to fasten;",
    "masuForm": "to tighten​",
    "naiForm": "しめます",
    "taForm": "しめない",
    "level": "N5"
  },
  {
    "id": "n5-v-87",
    "number": 87,
    "jp": "閉める",
    "romaji": "shimeru",
    "meaning": "to close; to shut",
    "masuForm": "閉めます",
    "naiForm": "閉めない",
    "taForm": "閉めた",
    "level": "N5"
  },
  {
    "id": "n5-v-88",
    "number": 88,
    "jp": "死ぬ",
    "romaji": "shinu",
    "meaning": "to die",
    "masuForm": "死にます",
    "naiForm": "死なない",
    "taForm": "死んだ",
    "level": "N5"
  },
  {
    "id": "n5-v-89",
    "number": 89,
    "jp": "知る",
    "romaji": "shiru",
    "meaning": "to know",
    "masuForm": "知ります",
    "naiForm": "知らない",
    "taForm": "知った",
    "level": "N5"
  },
  {
    "id": "n5-v-90",
    "number": 90,
    "jp": "質問をする",
    "romaji": "shitsumon o suru",
    "meaning": "to ask a question",
    "masuForm": "質問をします",
    "naiForm": "質問をしない",
    "taForm": "質問をした",
    "level": "N5"
  },
  {
    "id": "n5-v-91",
    "number": 91,
    "jp": "掃除をする",
    "romaji": "souji o suru",
    "meaning": "to clean",
    "masuForm": "掃除をします",
    "naiForm": "掃除をしない",
    "taForm": "掃除をした",
    "level": "N5"
  },
  {
    "id": "n5-v-92",
    "number": 92,
    "jp": "住む",
    "romaji": "sumu",
    "meaning": "to live in",
    "masuForm": "住みます",
    "naiForm": "住まない",
    "taForm": "住んだ",
    "level": "N5"
  },
  {
    "id": "n5-v-93",
    "number": 93,
    "jp": "吸う",
    "romaji": "suu",
    "meaning": "to smoke, to suck",
    "masuForm": "吸います",
    "naiForm": "吸わない",
    "taForm": "吸った",
    "level": "N5"
  },
  {
    "id": "n5-v-94",
    "number": 94,
    "jp": "座る",
    "romaji": "suwaru",
    "meaning": "to sit",
    "masuForm": "座ります",
    "naiForm": "座らない",
    "taForm": "座った",
    "level": "N5"
  },
  {
    "id": "n5-v-95",
    "number": 95,
    "jp": "食べる",
    "romaji": "taberu",
    "meaning": "to eat Present Negative Past Positive",
    "masuForm": "食べます",
    "naiForm": "食べない",
    "taForm": "食べた",
    "level": "N5"
  },
  {
    "id": "n5-v-96",
    "number": 96,
    "jp": "頼む",
    "romaji": "tanomu",
    "meaning": "to ask",
    "masuForm": "頼みます",
    "naiForm": "頼まない",
    "taForm": "頼んだ",
    "level": "N5"
  },
  {
    "id": "n5-v-97",
    "number": 97,
    "jp": "立つ",
    "romaji": "tatsu",
    "meaning": "to stand",
    "masuForm": "立ちます",
    "naiForm": "立たない",
    "taForm": "立った",
    "level": "N5"
  },
  {
    "id": "n5-v-98",
    "number": 98,
    "jp": "テストをする",
    "romaji": "tesuto o suru",
    "meaning": "to take a test",
    "masuForm": "テストをします",
    "naiForm": "テストをした",
    "taForm": "",
    "level": "N5"
  },
  {
    "id": "n5-v-99",
    "number": 99,
    "jp": "飛ぶ",
    "romaji": "tobu",
    "meaning": "to fly; to hop tomaru to stop toru to take a photo or record a film toru to take tsukareru to get tired tsukau to use tsukeru to attach; affix; add; apply tsukeru to turn on tsuku to arrive at tsukuru to make tsutomeru to work for someone umareru to be born uru to sell Present Negative Past Positive utau to sing wakaru to understand wasureru to forget wataru to go across watasu to hand over yaru to do yasumu to be absent; to rest yobu to call out yomu to read See more lessons at JLPTsensei.com",
    "masuForm": "飛びます",
    "naiForm": "飛ばない",
    "taForm": "飛んだ",
    "level": "N5"
  }
];

export const N4_VERBS = [
  {
    "id": "n4-v-1",
    "number": 1,
    "jp": "上がる",
    "kana": "あがる",
    "meaning": "to rise",
    "teForm": "上がって",
    "potential": "上がれる",
    "passive": "上がられる",
    "causative": "上がらせる",
    "level": "N4"
  },
  {
    "id": "n4-v-2",
    "number": 2,
    "jp": "挨拶する",
    "kana": "あいさつする",
    "meaning": "to greet",
    "teForm": "挨拶して",
    "potential": "挨拶できる",
    "passive": "挨拶される",
    "causative": "挨拶させる",
    "level": "N4"
  },
  {
    "id": "n4-v-3",
    "number": 3,
    "jp": "案内する",
    "kana": "あんないする",
    "meaning": "to guide",
    "teForm": "案内して",
    "potential": "案内できる",
    "passive": "案内される",
    "causative": "案内させる",
    "level": "N4"
  },
  {
    "id": "n4-v-4",
    "number": 4,
    "jp": "安心する",
    "kana": "あんしんする",
    "meaning": "to feel peace of mind; to relax",
    "teForm": "安心して",
    "potential": "安心できる",
    "passive": "安心される",
    "causative": "安心させる",
    "level": "N4"
  },
  {
    "id": "n4-v-5",
    "number": 5,
    "jp": "アルバイトする",
    "kana": "to work a",
    "meaning": "part-time job",
    "teForm": "アルバイト",
    "potential": "しよう",
    "passive": "アルバイト",
    "causative": "すれば",
    "level": "N4"
  },
  {
    "id": "n4-v-6",
    "number": 6,
    "jp": "集まる",
    "kana": "あつまる",
    "meaning": "gather; accumulate",
    "teForm": "集まって",
    "potential": "集まれる",
    "passive": "集まられる",
    "causative": "集まらせる",
    "level": "N4"
  },
  {
    "id": "n4-v-7",
    "number": 7,
    "jp": "集める",
    "kana": "あつめる",
    "meaning": "gather; pull together",
    "teForm": "集めて",
    "potential": "集められる",
    "passive": "集められる",
    "causative": "集めさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-8",
    "number": 8,
    "jp": "謝る",
    "kana": "あやまる",
    "meaning": "to apologize",
    "teForm": "謝って",
    "potential": "謝れる",
    "passive": "謝られる",
    "causative": "謝らせる",
    "level": "N4"
  },
  {
    "id": "n4-v-9",
    "number": 9,
    "jp": "貿易する",
    "kana": "ぼうえきする",
    "meaning": "to trade",
    "teForm": "貿易して",
    "potential": "貿易できる",
    "passive": "貿易される",
    "causative": "貿易させる",
    "level": "N4"
  },
  {
    "id": "n4-v-10",
    "number": 10,
    "jp": "チェックする",
    "kana": "to check",
    "meaning": "-",
    "teForm": "し",
    "potential": "チェック",
    "passive": "しよう",
    "causative": "チェック",
    "level": "N4"
  },
  {
    "id": "n4-v-11",
    "number": 11,
    "jp": "注意する",
    "kana": "ちゅういする",
    "meaning": "to caution; to warn Provisional",
    "teForm": "注意して",
    "potential": "注意できる",
    "passive": "注意される",
    "causative": "注意させる",
    "level": "N4"
  },
  {
    "id": "n4-v-12",
    "number": 12,
    "jp": "注射する",
    "kana": "ちゅうしゃする",
    "meaning": "to inject",
    "teForm": "注射して",
    "potential": "注射できる",
    "passive": "注射される",
    "causative": "注射させる",
    "level": "N4"
  },
  {
    "id": "n4-v-13",
    "number": 13,
    "jp": "暖房する",
    "kana": "だんぼうする",
    "meaning": "to heat",
    "teForm": "暖房して",
    "potential": "暖房できる",
    "passive": "暖房される",
    "causative": "暖房させる",
    "level": "N4"
  },
  {
    "id": "n4-v-14",
    "number": 14,
    "jp": "遠慮する",
    "kana": "えんりょする",
    "meaning": "to be reserved",
    "teForm": "遠慮して",
    "potential": "遠慮できる",
    "passive": "遠慮される",
    "causative": "遠慮させる",
    "level": "N4"
  },
  {
    "id": "n4-v-15",
    "number": 15,
    "jp": "選ぶ",
    "kana": "えらぶ",
    "meaning": "to choose",
    "teForm": "選んで",
    "potential": "選べる",
    "passive": "選ばれる",
    "causative": "選ばせる",
    "level": "N4"
  },
  {
    "id": "n4-v-16",
    "number": 16,
    "jp": "ファックスする",
    "kana": "to fax",
    "meaning": "-",
    "teForm": "し",
    "potential": "ファックス",
    "passive": "しよう",
    "causative": "ファックス",
    "level": "N4"
  },
  {
    "id": "n4-v-17",
    "number": 17,
    "jp": "増える",
    "kana": "ふえる",
    "meaning": "to increase",
    "teForm": "増えて",
    "potential": "増えられる",
    "passive": "増えられる",
    "causative": "増えさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-18",
    "number": 18,
    "jp": "復習する",
    "kana": "ふくしゅうする",
    "meaning": "to review",
    "teForm": "復習して",
    "potential": "復習できる",
    "passive": "復習される",
    "causative": "復習させる",
    "level": "N4"
  },
  {
    "id": "n4-v-19",
    "number": 19,
    "jp": "踏む",
    "kana": "ふむ",
    "meaning": "to step on",
    "teForm": "踏んで",
    "potential": "踏める",
    "passive": "踏まれる",
    "causative": "踏ませる",
    "level": "N4"
  },
  {
    "id": "n4-v-20",
    "number": 20,
    "jp": "降り出す",
    "kana": "ふりだす",
    "meaning": "to start to rain",
    "teForm": "振り出して",
    "potential": "振り出せる",
    "passive": "振り出される",
    "causative": "振り出させる",
    "level": "N4"
  },
  {
    "id": "n4-v-21",
    "number": 21,
    "jp": "太る",
    "kana": "ふとる",
    "meaning": "to become fat",
    "teForm": "太って",
    "potential": "太れる",
    "passive": "太られる",
    "causative": "太らせる",
    "level": "N4"
  },
  {
    "id": "n4-v-22",
    "number": 22,
    "jp": "原因する",
    "kana": "げんいんする",
    "meaning": "to cause; be caused by Provisional",
    "teForm": "原因して",
    "potential": "原因できる",
    "passive": "原因される",
    "causative": "原因させる",
    "level": "N4"
  },
  {
    "id": "n4-v-23",
    "number": 23,
    "jp": "下宿する",
    "kana": "げしゅくする",
    "meaning": "to lodge",
    "teForm": "下宿して",
    "potential": "下宿できる",
    "passive": "下宿される",
    "causative": "下宿させる",
    "level": "N4"
  },
  {
    "id": "n4-v-24",
    "number": 24,
    "jp": "ごちそうする",
    "kana": "to treat (meal)",
    "meaning": "-",
    "teForm": "し",
    "potential": "ごちそう",
    "passive": "しよう",
    "causative": "ごちそう",
    "level": "N4"
  },
  {
    "id": "n4-v-25",
    "number": 25,
    "jp": "ご覧になる",
    "kana": "ごらんになる",
    "meaning": "(respectful) to see",
    "teForm": "ご覧になって",
    "potential": "ご覧になれる",
    "passive": "ご覧に",
    "causative": "なられる",
    "level": "N4"
  },
  {
    "id": "n4-v-26",
    "number": 26,
    "jp": "拝見する",
    "kana": "はいけんする",
    "meaning": "-",
    "teForm": "拝見し",
    "potential": "拝見すれば",
    "passive": "拝見できる",
    "causative": "拝見される",
    "level": "N4"
  },
  {
    "id": "n4-v-27",
    "number": 27,
    "jp": "運ぶ",
    "kana": "はこぶ",
    "meaning": "to carry",
    "teForm": "運んで",
    "potential": "運べる",
    "passive": "運ばれる",
    "causative": "運ばせる",
    "level": "N4"
  },
  {
    "id": "n4-v-28",
    "number": 28,
    "jp": "花見する",
    "kana": "はなみする",
    "meaning": "to do flower viewing",
    "teForm": "花見して",
    "potential": "花見できる",
    "passive": "花見される",
    "causative": "花見させる",
    "level": "N4"
  },
  {
    "id": "n4-v-29",
    "number": 29,
    "jp": "反対する",
    "kana": "はんたいする",
    "meaning": "to oppose",
    "teForm": "反対して",
    "potential": "反対できる",
    "passive": "反対される",
    "causative": "反対させる",
    "level": "N4"
  },
  {
    "id": "n4-v-30",
    "number": 30,
    "jp": "払う",
    "kana": "はらう",
    "meaning": "to pay",
    "teForm": "払って",
    "potential": "払える",
    "passive": "払われる",
    "causative": "払わせる",
    "level": "N4"
  },
  {
    "id": "n4-v-31",
    "number": 31,
    "jp": "発音する",
    "kana": "はつおんする",
    "meaning": "to pronounce",
    "teForm": "発音して",
    "potential": "発音できる",
    "passive": "発音される",
    "causative": "発音させる",
    "level": "N4"
  },
  {
    "id": "n4-v-32",
    "number": 32,
    "jp": "返事する",
    "kana": "へんじする",
    "meaning": "to reply; answer",
    "teForm": "返事して",
    "potential": "返事できる",
    "passive": "返事される",
    "causative": "返事させる",
    "level": "N4"
  },
  {
    "id": "n4-v-33",
    "number": 33,
    "jp": "冷える",
    "kana": "ひえる",
    "meaning": "to grow cold Provisional",
    "teForm": "冷えて",
    "potential": "冷えられる",
    "passive": "冷えられる",
    "causative": "冷えさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-34",
    "number": 34,
    "jp": "光る",
    "kana": "ひかる",
    "meaning": "to shine",
    "teForm": "光って",
    "potential": "光れる",
    "passive": "光られる",
    "causative": "光らせる",
    "level": "N4"
  },
  {
    "id": "n4-v-35",
    "number": 35,
    "jp": "引き出す",
    "kana": "ひきだす",
    "meaning": "to withdraw",
    "teForm": "引き出して",
    "potential": "引き出せる",
    "passive": "引き出される",
    "causative": "引き出させる",
    "level": "N4"
  },
  {
    "id": "n4-v-36",
    "number": 36,
    "jp": "引っ越す",
    "kana": "ひっこす",
    "meaning": "to move house",
    "teForm": "引っ越して",
    "potential": "引っ越せる",
    "passive": "引っ越される",
    "causative": "引っ越させる",
    "level": "N4"
  },
  {
    "id": "n4-v-37",
    "number": 37,
    "jp": "開く",
    "kana": "ひらく",
    "meaning": "to open; to unseal",
    "teForm": "開いて",
    "potential": "開ける",
    "passive": "開かれる",
    "causative": "開かせる",
    "level": "N4"
  },
  {
    "id": "n4-v-38",
    "number": 38,
    "jp": "拾う",
    "kana": "ひろう",
    "meaning": "to pick up",
    "teForm": "拾って",
    "potential": "拾える",
    "passive": "拾われる",
    "causative": "拾わせる",
    "level": "N4"
  },
  {
    "id": "n4-v-39",
    "number": 39,
    "jp": "褒める",
    "kana": "ほめる",
    "meaning": "to praise",
    "teForm": "褒めて",
    "potential": "褒められる",
    "passive": "褒められる",
    "causative": "褒めさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-40",
    "number": 40,
    "jp": "翻訳する",
    "kana": "ほんやくする",
    "meaning": "to translate",
    "teForm": "翻訳して",
    "potential": "翻訳できる",
    "passive": "翻訳される",
    "causative": "翻訳させる",
    "level": "N4"
  },
  {
    "id": "n4-v-41",
    "number": 41,
    "jp": "放送する",
    "kana": "ほうそうする",
    "meaning": "to broadcast",
    "teForm": "放送して",
    "potential": "放送できる",
    "passive": "放送される",
    "causative": "放送させる",
    "level": "N4"
  },
  {
    "id": "n4-v-42",
    "number": 42,
    "jp": "いじめる",
    "kana": "to tease",
    "meaning": "-",
    "teForm": "いじめて",
    "potential": "いじめられる",
    "passive": "いじめられる",
    "causative": "いじめさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-43",
    "number": 43,
    "jp": "意見する",
    "kana": "いけんする",
    "meaning": "to give opinion",
    "teForm": "意見して",
    "potential": "意見できる",
    "passive": "意見される",
    "causative": "意見させる",
    "level": "N4"
  },
  {
    "id": "n4-v-44",
    "number": 44,
    "jp": "生きる",
    "kana": "いきる",
    "meaning": "to live Provisional",
    "teForm": "生きて",
    "potential": "生きられる",
    "passive": "生きられる",
    "causative": "生きさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-45",
    "number": 45,
    "jp": "祈る",
    "kana": "いのる",
    "meaning": "to pray",
    "teForm": "祈って",
    "potential": "祈れる",
    "passive": "祈られる",
    "causative": "祈らせる",
    "level": "N4"
  },
  {
    "id": "n4-v-46",
    "number": 46,
    "jp": "急ぐ",
    "kana": "いそぐ",
    "meaning": "to hurry; to rush",
    "teForm": "急いで",
    "potential": "急げる",
    "passive": "急がれる",
    "causative": "急がせる",
    "level": "N4"
  },
  {
    "id": "n4-v-47",
    "number": 47,
    "jp": "頂く",
    "kana": "いただく",
    "meaning": "(humble) to receive",
    "teForm": "頂いて",
    "potential": "頂ける",
    "passive": "頂かれる",
    "causative": "頂かせる",
    "level": "N4"
  },
  {
    "id": "n4-v-48",
    "number": 48,
    "jp": "致す",
    "kana": "いたす",
    "meaning": "(humble) to do",
    "teForm": "致して",
    "potential": "致せる",
    "passive": "致される",
    "causative": "致させる",
    "level": "N4"
  },
  {
    "id": "n4-v-49",
    "number": 49,
    "jp": "準備する",
    "kana": "じゅんびする",
    "meaning": "to prepare",
    "teForm": "準備して",
    "potential": "準備できる",
    "passive": "準備される",
    "causative": "準備させる",
    "level": "N4"
  },
  {
    "id": "n4-v-50",
    "number": 50,
    "jp": "変える",
    "kana": "かえる",
    "meaning": "to change; to transform",
    "teForm": "変えて",
    "potential": "変えられる",
    "passive": "変えられる",
    "causative": "変えさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-51",
    "number": 51,
    "jp": "会議する",
    "kana": "かいぎする",
    "meaning": "meeting; conference",
    "teForm": "会議して",
    "potential": "会議できる",
    "passive": "会議される",
    "causative": "会議させる",
    "level": "N4"
  },
  {
    "id": "n4-v-52",
    "number": 52,
    "jp": "会話する",
    "kana": "かいわする",
    "meaning": "conversation",
    "teForm": "会話して",
    "potential": "会話できる",
    "passive": "会話される",
    "causative": "会話させる",
    "level": "N4"
  },
  {
    "id": "n4-v-53",
    "number": 53,
    "jp": "構う",
    "kana": "かまう",
    "meaning": "to mind",
    "teForm": "構って",
    "potential": "構える",
    "passive": "構われる",
    "causative": "構わせる",
    "level": "N4"
  },
  {
    "id": "n4-v-54",
    "number": 54,
    "jp": "噛む",
    "kana": "かむ",
    "meaning": "to bite; to chew",
    "teForm": "噛んで",
    "potential": "噛める",
    "passive": "噛まれる",
    "causative": "噛ませる",
    "level": "N4"
  },
  {
    "id": "n4-v-55",
    "number": 55,
    "jp": "考える",
    "kana": "かんがえる",
    "meaning": "to think Provisional",
    "teForm": "考えて",
    "potential": "考えられる",
    "passive": "考えられる",
    "causative": "考えさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-56",
    "number": 56,
    "jp": "関係する",
    "kana": "かんけいする",
    "meaning": "to be related to",
    "teForm": "関係して",
    "potential": "関係できる",
    "passive": "関係される",
    "causative": "関係させる",
    "level": "N4"
  },
  {
    "id": "n4-v-57",
    "number": 57,
    "jp": "片付ける",
    "kana": "かたづける",
    "meaning": "to tidy up",
    "teForm": "片付けて",
    "potential": "片付けられる",
    "passive": "片付けられる",
    "causative": "片付けさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-58",
    "number": 58,
    "jp": "勝つ",
    "kana": "かつ",
    "meaning": "to win",
    "teForm": "勝って",
    "potential": "勝てる",
    "passive": "勝たれる",
    "causative": "勝たせる",
    "level": "N4"
  },
  {
    "id": "n4-v-59",
    "number": 59,
    "jp": "乾く",
    "kana": "かわく",
    "meaning": "to get dry",
    "teForm": "乾いて",
    "potential": "乾ける",
    "passive": "乾かれる",
    "causative": "乾かせる",
    "level": "N4"
  },
  {
    "id": "n4-v-60",
    "number": 60,
    "jp": "変わる",
    "kana": "かわる",
    "meaning": "to change",
    "teForm": "変わって",
    "potential": "変われる",
    "passive": "変わられる",
    "causative": "変わらせる",
    "level": "N4"
  },
  {
    "id": "n4-v-61",
    "number": 61,
    "jp": "通う",
    "kana": "かよう",
    "meaning": "to commute",
    "teForm": "通って",
    "potential": "通える",
    "passive": "通われる",
    "causative": "通わせる",
    "level": "N4"
  },
  {
    "id": "n4-v-62",
    "number": 62,
    "jp": "飾る",
    "kana": "かざる",
    "meaning": "to decorate",
    "teForm": "飾って",
    "potential": "飾れる",
    "passive": "飾られる",
    "causative": "飾らせる",
    "level": "N4"
  },
  {
    "id": "n4-v-63",
    "number": 63,
    "jp": "怪我する",
    "kana": "けがする",
    "meaning": "to injure",
    "teForm": "怪我して",
    "potential": "怪我できる",
    "passive": "怪我される",
    "causative": "怪我させる",
    "level": "N4"
  },
  {
    "id": "n4-v-64",
    "number": 64,
    "jp": "計画する",
    "kana": "けいかくする",
    "meaning": "to plan",
    "teForm": "計画して",
    "potential": "計画できる",
    "passive": "計画される",
    "causative": "計画させる",
    "level": "N4"
  },
  {
    "id": "n4-v-65",
    "number": 65,
    "jp": "経験する",
    "kana": "けいけんする",
    "meaning": "to experience",
    "teForm": "経験して",
    "potential": "経験できる",
    "passive": "経験される",
    "causative": "経験させる",
    "level": "N4"
  },
  {
    "id": "n4-v-66",
    "number": 66,
    "jp": "見物する",
    "kana": "けんぶつする",
    "meaning": "to sightsee/ visit Provisional",
    "teForm": "見物して",
    "potential": "見物できる",
    "passive": "見物される",
    "causative": "見物させる",
    "level": "N4"
  },
  {
    "id": "n4-v-67",
    "number": 67,
    "jp": "喧嘩する",
    "kana": "けんかする",
    "meaning": "to quarrel",
    "teForm": "喧嘩して",
    "potential": "喧嘩できる",
    "passive": "喧嘩される",
    "causative": "喧嘩させる",
    "level": "N4"
  },
  {
    "id": "n4-v-68",
    "number": 68,
    "jp": "研究する",
    "kana": "けんきゅうする",
    "meaning": "research",
    "teForm": "研究して",
    "potential": "研究できる",
    "passive": "研究される",
    "causative": "研究させる",
    "level": "N4"
  },
  {
    "id": "n4-v-69",
    "number": 69,
    "jp": "聞こえる",
    "kana": "きこえる",
    "meaning": "to be heard; to be said",
    "teForm": "聞こえて",
    "potential": "聞こえられる",
    "passive": "聞こえられる",
    "causative": "聞こえさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-70",
    "number": 70,
    "jp": "決まる",
    "kana": "きまる",
    "meaning": "to be decided",
    "teForm": "決まって",
    "potential": "決まれる",
    "passive": "決まられる",
    "causative": "決まらせる",
    "level": "N4"
  },
  {
    "id": "n4-v-71",
    "number": 71,
    "jp": "決める",
    "kana": "きめる",
    "meaning": "to decide",
    "teForm": "決めて",
    "potential": "決められる",
    "passive": "決められる",
    "causative": "決めさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-72",
    "number": 72,
    "jp": "込む",
    "kana": "こむ",
    "meaning": "to be crowded",
    "teForm": "込んで",
    "potential": "込める",
    "passive": "込まれる",
    "causative": "込ませる",
    "level": "N4"
  },
  {
    "id": "n4-v-73",
    "number": 73,
    "jp": "故障する",
    "kana": "こしょうする",
    "meaning": "to break-down",
    "teForm": "故障して",
    "potential": "故障できる",
    "passive": "故障される",
    "causative": "故障させる",
    "level": "N4"
  },
  {
    "id": "n4-v-74",
    "number": 74,
    "jp": "講義する",
    "kana": "こうぎする",
    "meaning": "to lecture on",
    "teForm": "講義して",
    "potential": "講義できる",
    "passive": "講義される",
    "causative": "講義させる",
    "level": "N4"
  },
  {
    "id": "n4-v-75",
    "number": 75,
    "jp": "壊れる",
    "kana": "こわれる",
    "meaning": "to be broken",
    "teForm": "壊れて",
    "potential": "壊れられる",
    "passive": "壊れられる",
    "causative": "壊れさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-76",
    "number": 76,
    "jp": "壊す",
    "kana": "こわす",
    "meaning": "to break",
    "teForm": "壊して",
    "potential": "壊せる",
    "passive": "壊される",
    "causative": "壊させる",
    "level": "N4"
  },
  {
    "id": "n4-v-77",
    "number": 77,
    "jp": "下さる",
    "kana": "くださる",
    "meaning": "(respectful) to give Provisional",
    "teForm": "下さって",
    "potential": "下される",
    "passive": "下さられる",
    "causative": "下さらせる",
    "level": "N4"
  },
  {
    "id": "n4-v-78",
    "number": 78,
    "jp": "比べる",
    "kana": "くらべる",
    "meaning": "to compare",
    "teForm": "比べて",
    "potential": "比べられる",
    "passive": "比べられる",
    "causative": "比べさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-79",
    "number": 79,
    "jp": "暮れる",
    "kana": "くれる",
    "meaning": "to get dark",
    "teForm": "暮れて",
    "potential": "暮れられる",
    "passive": "暮れられる",
    "causative": "暮れさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-80",
    "number": 80,
    "jp": "教育する",
    "kana": "きょういくする",
    "meaning": "to educate",
    "teForm": "教育して",
    "potential": "教育できる",
    "passive": "教育される",
    "causative": "教育させる",
    "level": "N4"
  },
  {
    "id": "n4-v-81",
    "number": 81,
    "jp": "競争する",
    "kana": "きょうそうする",
    "meaning": "to compete",
    "teForm": "競争して",
    "potential": "競争できる",
    "passive": "競争される",
    "causative": "競争させる",
    "level": "N4"
  },
  {
    "id": "n4-v-82",
    "number": 82,
    "jp": "急行する",
    "kana": "きゅうこうする",
    "meaning": "to rush to",
    "teForm": "急行して",
    "potential": "急行できる",
    "passive": "急行される",
    "causative": "急行させる",
    "level": "N4"
  },
  {
    "id": "n4-v-83",
    "number": 83,
    "jp": "間違える",
    "kana": "まちがえる",
    "meaning": "to make a mistake",
    "teForm": "間違えて",
    "potential": "間違えられる",
    "passive": "間違えられる",
    "causative": "間違えさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-84",
    "number": 84,
    "jp": "参る",
    "kana": "まいる",
    "meaning": "(humble) to go; to come",
    "teForm": "参って",
    "potential": "参れる",
    "passive": "参られる",
    "causative": "参らせる",
    "level": "N4"
  },
  {
    "id": "n4-v-85",
    "number": 85,
    "jp": "負ける",
    "kana": "まける",
    "meaning": "to lose",
    "teForm": "負けて",
    "potential": "負けられる",
    "passive": "負けられる",
    "causative": "負けさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-86",
    "number": 86,
    "jp": "間に合う",
    "kana": "まにあう",
    "meaning": "to be in time (for)",
    "teForm": "間に合って",
    "potential": "間に合える",
    "passive": "間に合われる",
    "causative": "間に合わせる",
    "level": "N4"
  },
  {
    "id": "n4-v-87",
    "number": 87,
    "jp": "回る",
    "kana": "まわる",
    "meaning": "to go around",
    "teForm": "回って",
    "potential": "回れる",
    "passive": "回られる",
    "causative": "回らせる",
    "level": "N4"
  },
  {
    "id": "n4-v-88",
    "number": 88,
    "jp": "召し上がる",
    "kana": "めしあがる",
    "meaning": "to eat; Provisional",
    "teForm": "召し上がり",
    "potential": "召し上がれば",
    "passive": "召し上がれる",
    "causative": "召し上がられる",
    "level": "N4"
  },
  {
    "id": "n4-v-89",
    "number": 89,
    "jp": "見える",
    "kana": "みえる",
    "meaning": "to be seen; to look; to seem",
    "teForm": "見えて",
    "potential": "見えられる",
    "passive": "見えられる",
    "causative": "見えさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-90",
    "number": 90,
    "jp": "見つかる",
    "kana": "みつかる",
    "meaning": "to be found; be discovered",
    "teForm": "見つかって",
    "potential": "見つかれる",
    "passive": "見つかられる",
    "causative": "見つからせる",
    "level": "N4"
  },
  {
    "id": "n4-v-91",
    "number": 91,
    "jp": "見つける",
    "kana": "みつける",
    "meaning": "to discover; to find",
    "teForm": "見つけて",
    "potential": "見つけられる",
    "passive": "見つけられる",
    "causative": "見つけさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-92",
    "number": 92,
    "jp": "戻る",
    "kana": "もどる",
    "meaning": "to turn back",
    "teForm": "戻って",
    "potential": "戻れる",
    "passive": "戻られる",
    "causative": "戻らせる",
    "level": "N4"
  },
  {
    "id": "n4-v-93",
    "number": 93,
    "jp": "申し上げる",
    "kana": "もうしあげる",
    "meaning": "to say; to offer",
    "teForm": "申し上げて",
    "potential": "申し上げられる",
    "passive": "申し上げられる",
    "causative": "申し上げさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-94",
    "number": 94,
    "jp": "申す",
    "kana": "もうす",
    "meaning": "to be called; to say",
    "teForm": "申して",
    "potential": "申せる",
    "passive": "申される",
    "causative": "申させる",
    "level": "N4"
  },
  {
    "id": "n4-v-95",
    "number": 95,
    "jp": "迎える",
    "kana": "むかえる",
    "meaning": "to go out to meet",
    "teForm": "迎えて",
    "potential": "迎えられる",
    "passive": "迎えられる",
    "causative": "迎えさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-96",
    "number": 96,
    "jp": "向かう",
    "kana": "むかう",
    "meaning": "to head towards",
    "teForm": "向かって",
    "potential": "向かえる",
    "passive": "向かわれる",
    "causative": "向かわせる",
    "level": "N4"
  },
  {
    "id": "n4-v-97",
    "number": 97,
    "jp": "無理する",
    "kana": "むりする",
    "meaning": "to overwork; do impossible",
    "teForm": "無理して",
    "potential": "無理できる",
    "passive": "無理される",
    "causative": "無理させる",
    "level": "N4"
  },
  {
    "id": "n4-v-98",
    "number": 98,
    "jp": "投げる",
    "kana": "なげる",
    "meaning": "to throw or cast away",
    "teForm": "投げて",
    "potential": "投げられる",
    "passive": "投げられる",
    "causative": "投げさせる",
    "level": "N4"
  },
  {
    "id": "n4-v-99",
    "number": 99,
    "jp": "泣く",
    "kana": "なく",
    "meaning": "to weep Provisional to disappear; to get lost to die to be fixed; to be repaired to be cured; to heal to get used to to sound; to ring to sleep in late to sleep to escape to be similar to remain Provisional to change buses or trains to get wet to paint; to plaster to steal to enroll in school / uni. to be hospitalized to fall or drop to be surprised to dance (respectful) to be to celebrate Provisional to perform; to do; carry out to be angry to wake to be late to send to remember to break; to be broken to get off to break or to fold (respectful) to say to drop Provisional to cool (a.c.) to contact; to use; to capitalize on to be absent to get down to look for to lower to give to make noise; be excited to touch to live Provisional to produce to fight a war to explain to have a match/game to scold to examine somebody to fail to investigate to notify to produce to introduce Provisional to rear; to bring up to graduate to discuss to slide; to slip to swim to be hungry to finish to make progress to throw away to discharge from hospital to be born Provisional to fall (over, down) to be sufficient / enough to add (numbers) to build to visit to ask to help; to assist to stay at to stop something to go through Provisional to exchange; to swap to continue; to keep up to continue to catch to soak; to pickle to be attached to take someone with to fish to report; to tell to wrap to plant; to grow Provisional to move to visit to take a lesson or test to hit to move house or transfer to copy or photograph to separate to boil; to heat to boil to laugh; to smile to break Provisional to burn; to be roasted to bake; to grill to be helpful to promise to stop to become thin to get dirty to be delighted to visit; to drop by to prepare for a lesson plan Provisional to prepare to make a reservation to shake",
    "teForm": "泣いて",
    "potential": "泣ける",
    "passive": "泣かれる",
    "causative": "泣かせる",
    "level": "N4"
  }
];
