-- Run once after deploying the code that removes these modules.
-- This deletes the retired Requests, Work Orders, Assets, and Inventory tables.

DELETE FROM role_permissions
WHERE permission_id IN (
  SELECT id
  FROM permissions
  WHERE code IN (
    'REQUESTS_CREATE',
    'REQUESTS_READ',
    'REQUESTS_ASSIGN',
    'REQUESTS_APPROVE',
    'WORK_ORDERS_MANAGE',
    'WORK_ORDERS_CLOSE',
    'ASSETS_MANAGE',
    'INVENTORY_MANAGE'
  )
);

DELETE FROM permissions
WHERE code IN (
  'REQUESTS_CREATE',
  'REQUESTS_READ',
  'REQUESTS_ASSIGN',
  'REQUESTS_APPROVE',
  'WORK_ORDERS_MANAGE',
  'WORK_ORDERS_CLOSE',
  'ASSETS_MANAGE',
  'INVENTORY_MANAGE'
);

DROP TABLE IF EXISTS purchase_requests CASCADE;
DROP TABLE IF EXISTS stock_movements CASCADE;
DROP TABLE IF EXISTS inventory_items CASCADE;
DROP TABLE IF EXISTS suppliers CASCADE;

DROP TABLE IF EXISTS work_order_assignments CASCADE;
DROP TABLE IF EXISTS checklist_responses CASCADE;
DROP TABLE IF EXISTS checklist_items CASCADE;
DROP TABLE IF EXISTS checklists CASCADE;
DROP TABLE IF EXISTS activity_timelines CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS attachments CASCADE;

DROP TABLE IF EXISTS preventive_maintenance_schedules CASCADE;
DROP TABLE IF EXISTS preventive_maintenance_plans CASCADE;
DROP TABLE IF EXISTS qr_assets CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS work_orders CASCADE;
DROP TABLE IF EXISTS maintenance_requests CASCADE;
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS asset_categories CASCADE;

DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS escalation_rules CASCADE;
DROP TABLE IF EXISTS sla_configs CASCADE;
DROP TABLE IF EXISTS settings CASCADE;
DROP TABLE IF EXISTS holidays CASCADE;
DROP TABLE IF EXISTS technician_attendance CASCADE;
DROP TABLE IF EXISTS technician_performance_metrics CASCADE;
DROP TABLE IF EXISTS custom_fields CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS properties CASCADE;
DROP TABLE IF EXISTS clients CASCADE;

ALTER TABLE users DROP COLUMN IF EXISTS client_id CASCADE;
ALTER TABLE branches DROP COLUMN IF EXISTS client_id CASCADE;
ALTER TABLE branches DROP COLUMN IF EXISTS latitude CASCADE;
ALTER TABLE branches DROP COLUMN IF EXISTS longitude CASCADE;

DROP TYPE IF EXISTS "RequestStatus" CASCADE;
DROP TYPE IF EXISTS "WorkOrderStatus" CASCADE;
DROP TYPE IF EXISTS "Priority" CASCADE;
DROP TYPE IF EXISTS "RequestSource" CASCADE;
DROP TYPE IF EXISTS "Frequency" CASCADE;
DROP TYPE IF EXISTS "AssetStatus" CASCADE;
DROP TYPE IF EXISTS "InventoryMovementType" CASCADE;
DROP TYPE IF EXISTS "PurchaseRequestStatus" CASCADE;
DROP TYPE IF EXISTS "NotificationChannel" CASCADE;
DROP TYPE IF EXISTS "NotificationStatus" CASCADE;
DROP TYPE IF EXISTS "AttachmentOwnerType" CASCADE;
DROP TYPE IF EXISTS "CommentVisibility" CASCADE;
DROP TYPE IF EXISTS "ChecklistOwnerType" CASCADE;
DROP TYPE IF EXISTS "AttendanceStatus" CASCADE;
DROP TYPE IF EXISTS "SlaTargetType" CASCADE;
DROP TYPE IF EXISTS "CustomFieldEntity" CASCADE;
