// Japanese JLPT N5 & N4 Comprehensive Active Learning Curricula

export const N5_GRAMMAR = [
  {
    id: 'n5-g-1',
    title: '〜てください (te kudasai)',
    formula: 'Verb [て-form] + ください',
    category: 'Requests & Instructions',
    meaning: 'Please do (something)',
    description: 'Used to politely ask or instruct someone to perform an action.',
    examples: [
      { jp: 'ここに名前を書いてください。', romaji: 'Koko ni namae o kaite kudasai.', en: 'Please write your name here.' },
      { jp: '窓を開けてください。', romaji: 'Mado o akete kudasai.', en: 'Please open the window.' },
      { jp: '日本語で話してください。', romaji: 'Nihongo de hanashite kudasai.', en: 'Please speak in Japanese.' },
    ],
  },
  {
    id: 'n5-g-2',
    title: '〜たい (tai)',
    formula: 'Verb [ます stem] + たい (です)',
    category: 'Desires & Wishes',
    meaning: 'Want to do (something)',
    description: 'Expresses the speaker\'s first-person desire to do an action.',
    examples: [
      { jp: '日本へ行きたいです。', romaji: 'Nihon e ikitai desu.', en: 'I want to go to Japan.' },
      { jp: 'お水を飲みたいです。', romaji: 'Omizu o nomitai desu.', en: 'I want to drink water.' },
      { jp: '新しい車を買いたいです。', romaji: 'Atarashii kuruma o kaitai desu.', en: 'I want to buy a new car.' },
    ],
  },
  {
    id: 'n5-g-3',
    title: '〜たことがある (ta koto ga aru)',
    formula: 'Verb [た-form] + ことがある',
    category: 'Past Experience',
    meaning: 'Have done (something) before / Have the experience of',
    description: 'Expresses that the speaker has had the past experience of doing an action.',
    examples: [
      { jp: '富士山に登ったことがあります。', romaji: 'Fujisan ni nobotta koto ga arimasu.', en: 'I have climbed Mount Fuji before.' },
      { jp: '納豆を食べたことがありますか。', romaji: 'Nattou o tabeta koto ga arimasu ka.', en: 'Have you ever eaten natto?' },
    ],
  },
  {
    id: 'n5-g-4',
    title: '〜ている (te iru)',
    formula: 'Verb [て-form] + いる',
    category: 'Actions & States',
    meaning: 'Is doing (continuous) / Resulting state',
    description: 'Expresses an action currently in progress, or a continuous state resulting from a past action.',
    examples: [
      { jp: '今、本を読んでいます。', romaji: 'Ima, hon o yonde imasu.', en: 'I am reading a book right now.' },
      { jp: '東京に住んでいます。', romaji: 'Toukyou ni sunde imasu.', en: 'I live in Tokyo.' },
      { jp: '田中さんを知っていますか。', romaji: 'Tanaka-san o shitte imasu ka.', en: 'Do you know Mr. Tanaka?' },
    ],
  },
  {
    id: 'n5-g-5',
    title: '〜てもいい (temo ii)',
    formula: 'Verb [て-form] + もいい (です)',
    category: 'Permission',
    meaning: 'May do / It is okay to do',
    description: 'Used to ask for or give permission to do something.',
    examples: [
      { jp: '写真を撮ってもいいですか。', romaji: 'Shashin o totte mo ii desu ka.', en: 'May I take a photo?' },
      { jp: 'ここでタバコを吸ってもいいです。', romaji: 'Koko de tabako o sutte mo ii desu.', en: 'You may smoke here.' },
    ],
  },
  {
    id: 'n5-g-6',
    title: '〜てはいけない (te wa ikenai)',
    formula: 'Verb [て-form] + はいけない / はだめ',
    category: 'Prohibition',
    meaning: 'Must not do / You cannot do',
    description: 'Used to strictly forbid or state a prohibition.',
    examples: [
      { jp: 'ここで写真を撮ってはいけません。', romaji: 'Koko de shashin o totte wa ikemasen.', en: 'You must not take photos here.' },
      { jp: '教室で走ってはいけません。', romaji: 'Kyoushitsu de hashitte wa ikemasen.', en: 'You must not run in the classroom.' },
    ],
  },
  {
    id: 'n5-g-7',
    title: '〜から (kara) / 〜ので (node)',
    formula: 'Sentence A + から / ので + Sentence B',
    category: 'Reason & Cause',
    meaning: 'Because / Since / So',
    description: 'Explains the reason or cause for the second statement.',
    examples: [
      { jp: '雨が降っていますから、傘を持って行きます。', romaji: 'Ame ga futte imasu kara, kasa o motte ikimasu.', en: 'Because it is raining, I will take an umbrella.' },
      { jp: '頭が痛いので、早く寝ます。', romaji: 'Atama ga itai node, hayaku nemasu.', en: 'Since I have a headache, I will sleep early.' },
    ],
  },
  {
    id: 'n5-g-8',
    title: '〜より〜ほうが (yori... hou ga)',
    formula: 'Noun A + より + Noun B + のほうが + Adjective',
    category: 'Comparison',
    meaning: 'B is more [Adjective] than A',
    description: 'Compares two items and states that one is more of a certain quality than the other.',
    examples: [
      { jp: '飛行機は電車より速いです。', romaji: 'Hikouki wa densha yori hayai desu.', en: 'Airplanes are faster than trains.' },
      { jp: 'コーヒーよりお茶のほうが好きです。', romaji: 'Koohii yori ocha no hou ga suki desu.', en: 'I like tea more than coffee.' },
    ],
  },
  {
    id: 'n5-g-9',
    title: '〜まえに (mae ni)',
    formula: 'Verb [Dictionary form] / Noun + の + 前に',
    category: 'Time & Sequence',
    meaning: 'Before doing (something)',
    description: 'Indicates that something happens before another action or event.',
    examples: [
      { jp: '寝る前に本を読みます。', romaji: 'Neru mae ni hon o yomimasu.', en: 'I read a book before going to bed.' },
      { jp: '食事の前に手を洗いましょう。', romaji: 'Shokuji no mae ni te o araimashou.', en: 'Let us wash our hands before the meal.' },
    ],
  },
  {
    id: 'n5-g-10',
    title: '〜てから (te kara)',
    formula: 'Verb [て-form] + から',
    category: 'Time & Sequence',
    meaning: 'After doing (something)',
    description: 'Indicates that the second action takes place after the first action is completed.',
    examples: [
      { jp: '手を洗ってからご飯を食べます。', romaji: 'Te o aratte kara gohan o tabemasu.', en: 'I eat meal after washing my hands.' },
      { jp: '宿題をしてから遊びに行きます。', romaji: 'Shukudai o shite kara asobi ni ikimasu.', en: 'I will go play after doing my homework.' },
    ],
  },
];

export const N4_GRAMMAR = [
  {
    id: 'n4-g-1',
    title: '〜すぎる (sugiru)',
    formula: 'Verb [ます stem] / い-Adj [drop い] / な-Adj + すぎる',
    category: 'Excess & Extent',
    meaning: 'Too much / Overly / Excessively',
    description: 'Indicates that an action or state goes beyond the acceptable limit.',
    examples: [
      { jp: '昨夜、お酒を飲みすぎました。', romaji: 'Sakuya, osake o nomisugimashita.', en: 'I drank too much alcohol last night.' },
      { jp: 'この問題は難しすぎます。', romaji: 'Kono mondai wa muzukashisugimasu.', en: 'This problem is too difficult.' },
      { jp: '服を買いすぎてお金がありません。', romaji: 'Fuku o kaisugite okane ga arimasen.', en: 'I bought too many clothes and have no money left.' },
    ],
  },
  {
    id: 'n4-g-2',
    title: '〜やすい / 〜にくい (yasui / nikui)',
    formula: 'Verb [ます stem] + やすい / にくい',
    category: 'Ease & Difficulty',
    meaning: 'Easy to do / Hard to do',
    description: 'Describes whether an action is easy or difficult to perform.',
    examples: [
      { jp: 'このペンはとても書きやすいです。', romaji: 'Kono pen wa totemo kakiyasui desu.', en: 'This pen is very easy to write with.' },
      { jp: '彼の説明は分かりにくいです。', romaji: 'Kare no setsumei wa wakarinikui desu.', en: 'His explanation is hard to understand.' },
    ],
  },
  {
    id: 'n4-g-3',
    title: '〜ば / 〜なら / 〜たら (Conditionals)',
    formula: 'Verb [ば-form] / [たら-form] / Noun + なら',
    category: 'Conditionals',
    meaning: 'If / When',
    description: 'Expresses conditional hypotheses and hypothetical situations.',
    examples: [
      { jp: '安ければ買います。', romaji: 'Yasukereba kaimasu.', en: 'If it is cheap, I will buy it.' },
      { jp: '雨が降ったら行きません。', romaji: 'Ame ga futtara ikimasen.', en: 'If it rains, I will not go.' },
      { jp: '日本へ行くなら春がいいですよ。', romaji: 'Nihon e iku nara haru ga ii desu yo.', en: 'If you are going to Japan, spring is good.' },
    ],
  },
  {
    id: 'n4-g-4',
    title: '〜ようにする (you ni suru)',
    formula: 'Verb [Dictionary / ない form] + ようにする',
    category: 'Habits & Efforts',
    meaning: 'Make an effort to / Try to do regularly',
    description: 'Expresses a conscious effort to adopt a habit or ensure something happens.',
    examples: [
      { jp: '毎日野菜を食べるようにしています。', romaji: 'Mainichi yasai o taberu you ni shite imasu.', en: 'I make an effort to eat vegetables every day.' },
      { jp: '夜遅く甘いものを食べないようにします。', romaji: 'Yoru osoku amai mono o tabenai you ni shimasu.', en: 'I try not to eat sweet things late at night.' },
    ],
  },
  {
    id: 'n4-g-5',
    title: '〜ようになる (you ni naru)',
    formula: 'Verb [Dictionary / Potential / ない form] + ようになる',
    category: 'Change in State',
    meaning: 'Come to / Reach the point where / Become able to',
    description: 'Describes a gradual change in ability, state, or circumstance over time.',
    examples: [
      { jp: '日本語の新聞が読めるようになりました。', romaji: 'Nihongo no shinbun ga yomeru you ni narimashita.', en: 'I have become able to read Japanese newspapers.' },
      { jp: '早く起きられるようになりました。', romaji: 'Hayaku okirareru you ni narimashita.', en: 'I became able to wake up early.' },
    ],
  },
  {
    id: 'n4-g-6',
    title: '〜受身形 (Passive: Rareru)',
    formula: 'Verb [Passive form: 書かれる / 食べられる]',
    category: 'Voice & Perspective',
    meaning: 'Be done by / Was affected by',
    description: 'Expresses that the subject is acted upon by another person or entity.',
    examples: [
      { jp: '先生に褒められました。', romaji: 'Sensei ni homeraremashita.', en: 'I was praised by my teacher.' },
      { jp: '雨に降られて服が濡れました。', romaji: 'Ame ni furarete fuku ga nuremashita.', en: 'I got rained on and my clothes got wet.' },
    ],
  },
  {
    id: 'n4-g-7',
    title: '〜使役形 (Causative: Saseru)',
    formula: 'Verb [Causative form: 読ませる / 食べさせる]',
    category: 'Voice & Perspective',
    meaning: 'Make / Let (someone) do',
    description: 'Expresses making someone do something or permitting them to do something.',
    examples: [
      { jp: '母は子供に野菜を食べさせます。', romaji: 'Haha wa kodomo ni yasai o tabesasemasu.', en: 'The mother makes her child eat vegetables.' },
      { jp: '先生は生徒に本を読ませました。', romaji: 'Sensei wa seito ni hon o yomasemashita.', en: 'The teacher had the students read the book.' },
    ],
  },
];

export const N5_KANJI = [
  { char: '日', meaning: 'Day / Sun', onyomi: 'NICHI, JITSU', kunyomi: 'hi, bi, ka', strokes: 4, examples: ['日本 (Nihon - Japan)', '日曜日 (Nichiyoubi - Sunday)', '今日 (Kyou - Today)'] },
  { char: '月', meaning: 'Month / Moon', onyomi: 'GETSU, GATSU', kunyomi: 'tsuki', strokes: 4, examples: ['月曜日 (Getsuyoubi - Monday)', '一月 (Ichigatsu - January)', '今月 (Kongetsu - This month)'] },
  { char: '火', meaning: 'Fire', onyomi: 'KA', kunyomi: 'hi', strokes: 4, examples: ['火曜日 (Kayoubi - Tuesday)', '火事 (Kaji - Fire accident)', '花火 (Hanabi - Fireworks)'] },
  { char: '水', meaning: 'Water', onyomi: 'SUI', kunyomi: 'mizu', strokes: 4, examples: ['水曜日 (Suiyoubi - Wednesday)', 'お水 (Omizu - Water)', '水泳 (Suiei - Swimming)'] },
  { char: '木', meaning: 'Tree / Wood', onyomi: 'MOKU, BOKU', kunyomi: 'ki', strokes: 4, examples: ['木曜日 (Mokuyoubi - Thursday)', '木 (Ki - Tree)'] },
  { char: '金', meaning: 'Gold / Money', onyomi: 'KIN, KON', kunyomi: 'kane', strokes: 8, examples: ['金曜日 (Kinyoubi - Friday)', 'お金 (Okane - Money)', '料金 (Ryoukin - Fee)'] },
  { char: '土', meaning: 'Earth / Soil', onyomi: 'DO, TO', kunyomi: 'tsuchi', strokes: 3, examples: ['土曜日 (Doyoubi - Saturday)', '土地 (Tochi - Land)'] },
  { char: '人', meaning: 'Person', onyomi: 'JIN, NIN', kunyomi: 'hito', strokes: 2, examples: ['日本人 (Nihonjin - Japanese person)', '三人 (Sannin - Three people)', '大人 (Otona - Adult)'] },
  { char: '本', meaning: 'Book / Origin', onyomi: 'HON', kunyomi: 'moto', strokes: 5, examples: ['本 (Hon - Book)', '日本 (Nihon - Japan)', '本当 (Hontou - Really)'] },
  { char: '学', meaning: 'Study / Learn', onyomi: 'GAKU', kunyomi: 'mana-bu', strokes: 8, examples: ['学生 (Gakusei - Student)', '大学 (Daigaku - University)', '学校 (Gakkou - School)'] },
  { char: '生', meaning: 'Life / Birth', onyomi: 'SEI, SHOU', kunyomi: 'i-kiru, u-mareru', strokes: 5, examples: ['先生 (Sensei - Teacher)', '学生 (Gakusei - Student)', '生活 (Seikatsu - Daily life)'] },
  { char: '先', meaning: 'Previous / Ahead', onyomi: 'SEN', kunyomi: 'saki', strokes: 6, examples: ['先生 (Sensei - Teacher)', '先週 (Senshuu - Last week)', '先に (Saki ni - Ahead/First)'] },
  { char: '大', meaning: 'Big / Large', onyomi: 'DAI, TAI', kunyomi: 'oo-kii', strokes: 3, examples: ['大きい (Ookii - Big)', '大学 (Daigaku - University)', '大変 (Taihen - Tough/Very)'] },
  { char: '小', meaning: 'Small', onyomi: 'SHOU', kunyomi: 'chii-sai, ko', strokes: 3, examples: ['小さい (Chiisai - Small)', '小学校 (Shougakkou - Elementary school)'] },
  { char: '中', meaning: 'Inside / Middle', onyomi: 'CHUU', kunyomi: 'naka', strokes: 4, examples: ['中 (Naka - Inside)', '中国 (Chuugoku - China)', '一日中 (Ichinichijuu - All day long)'] },
  { char: '上', meaning: 'Above / Up', onyomi: 'JOU', kunyomi: 'ue, a-garu', strokes: 3, examples: ['上 (Ue - Above)', '上手 (Jouzu - Skillful)', '上がる (Agaru - To go up)'] },
  { char: '下', meaning: 'Below / Down', onyomi: 'KA, GE', kunyomi: 'shita, sa-garu', strokes: 3, examples: ['下 (Shita - Below)', '下手 (Heta - Unskillful)', '地下鉄 (Chikatetsu - Subway)'] },
  { char: '車', meaning: 'Car / Wheel', onyomi: 'SHA', kunyomi: 'kuruma', strokes: 7, examples: ['車 (Kuruma - Car)', '電車 (Densha - Train)', '自転車 (Jitensha - Bicycle)'] },
  { char: '食', meaning: 'Eat / Food', onyomi: 'SHOKU', kunyomi: 'ta-beru', strokes: 9, examples: ['食べる (Taberu - To eat)', '食べ物 (Tabemono - Food)', '食事 (Shokuji - Meal)'] },
  { char: '飲', meaning: 'Drink', onyomi: 'IN', kunyomi: 'no-mu', strokes: 12, examples: ['飲む (Nomu - To drink)', '飲み物 (Nomimono - Drink/Beverage)', '飲食店 (Inshokuten - Restaurant)'] },
  { char: '見', meaning: 'See / Look', onyomi: 'KEN', kunyomi: 'mi-ru', strokes: 7, examples: ['見る (Miru - To see)', '見学 (Kengaku - Inspection/Tour)', '意見 (Iken - Opinion)'] },
  { char: '聞', meaning: 'Hear / Listen / Ask', onyomi: 'BUN, MON', kunyomi: 'ki-ku', strokes: 14, examples: ['聞く (Kiku - To listen/ask)', '新聞 (Shinbun - Newspaper)'] },
  { char: '書', meaning: 'Write / Book', onyomi: 'SHO', kunyomi: 'ka-ku', strokes: 10, examples: ['書く (Kaku - To write)', '辞書 (Jisho - Dictionary)', '図書館 (Toshokan - Library)'] },
  { char: '読', meaning: 'Read', onyomi: 'DOKU', kunyomi: 'yo-mu', strokes: 14, examples: ['読む (Yomu - To read)', '読書 (Dokusho - Reading books)'] },
];

export const N4_KANJI = [
  { char: '会', meaning: 'Meet / Association', onyomi: 'KAI, E', kunyomi: 'a-u', strokes: 6, examples: ['会う (Au - To meet)', '会社 (Kaisha - Company)', '会議 (Kaigi - Meeting)'] },
  { char: '同', meaning: 'Same / Equal', onyomi: 'DOU', kunyomi: 'ona-ji', strokes: 6, examples: ['同じ (Onaji - Same)', '同時に (Douji ni - Simultaneously)'] },
  { char: '事', meaning: 'Matter / Thing / Affair', onyomi: 'JI', kunyomi: 'koto', strokes: 8, examples: ['仕事 (Shigoto - Work/Job)', '事故 (Jiko - Accident)', '食事 (Shokuji - Meal)'] },
  { char: '社', meaning: 'Company / Shrine', onyomi: 'SHA', kunyomi: 'yashiro', strokes: 7, examples: ['会社 (Kaisha - Company)', '社会 (Shakai - Society)', '神社 (Jinja - Shinto shrine)'] },
  { char: '発', meaning: 'Discharge / Depart / Emit', onyomi: 'HATSU, HOTSU', kunyomi: 'ta-tsu', strokes: 9, examples: ['出発 (Shuppatsu - Departure)', '発表 (Happyou - Announcement)'] },
  { char: '者', meaning: 'Person / Specialist', onyomi: 'SHA', kunyomi: 'mono', strokes: 8, examples: ['医者 (Isha - Doctor)', '若者 (Wakamono - Young person)', '学者 (Gakusha - Scholar)'] },
  { char: '地', meaning: 'Ground / Earth', onyomi: 'CHI, JI', kunyomi: 'tsuchi', strokes: 6, examples: ['地下鉄 (Chikatetsu - Subway)', '地震 (Jishin - Earthquake)', '地図 (Chizu - Map)'] },
  { char: '業', meaning: 'Business / Industry', onyomi: 'GYOU, GOU', kunyomi: 'waza', strokes: 13, examples: ['作業 (Sagyou - Work/Operation)', '授業 (Jugyou - Class lesson)', '工業 (Kougyou - Industry)'] },
  { char: '方', meaning: 'Direction / Method', onyomi: 'HOU', kunyomi: 'kata', strokes: 4, examples: ['方法 (Houhou - Method)', '使い方 (Tsukaikata - How to use)', '夕方 (Yuugata - Evening)'] },
  { char: '新', meaning: 'New', onyomi: 'SHIN', kunyomi: 'atara-shii', strokes: 13, examples: ['新しい (Atarashii - New)', '新聞 (Shinbun - Newspaper)', '新年 (Shinnen - New Year)'] },
  { char: '場', meaning: 'Place / Location', onyomi: 'JOU', kunyomi: 'ba', strokes: 12, examples: ['工場 (Koujou - Factory/Plant)', '場所 (Basho - Location)', '駐車場 (Chuushajou - Parking lot)'] },
  { char: '員', meaning: 'Member / Employee', onyomi: 'IN', kunyomi: '-', strokes: 10, examples: ['社員 (Shain - Employee)', '店員 (Ten\'in - Shop clerk)', '全員 (Zen\'in - All members)'] },
];

export const N5_VOCABULARY = [
  { jp: '行く', kana: 'いく', romaji: 'iku', en: 'to go', category: 'Verbs (Group 1)' },
  { jp: '来る', kana: 'くる', romaji: 'kuru', en: 'to come', category: 'Verbs (Group 3)' },
  { jp: '食べる', kana: 'たべる', romaji: 'taberu', en: 'to eat', category: 'Verbs (Group 2)' },
  { jp: '飲む', kana: 'のむ', romaji: 'nomu', en: 'to drink', category: 'Verbs (Group 1)' },
  { jp: '見る', kana: 'みる', romaji: 'miru', en: 'to see / look', category: 'Verbs (Group 2)' },
  { jp: '聞く', kana: 'きく', romaji: 'kiku', en: 'to hear / listen / ask', category: 'Verbs (Group 1)' },
  { jp: '話す', kana: 'はなす', romaji: 'hanasu', en: 'to speak', category: 'Verbs (Group 1)' },
  { jp: '買う', kana: 'かう', romaji: 'kau', en: 'to buy', category: 'Verbs (Group 1)' },
  { jp: '大きい', kana: 'おおきい', romaji: 'ookii', en: 'big / large', category: 'I-Adjectives' },
  { jp: '小さい', kana: 'ちいさい', romaji: 'chiisai', en: 'small', category: 'I-Adjectives' },
  { jp: '新しい', kana: 'あたらしい', romaji: 'atarashii', en: 'new', category: 'I-Adjectives' },
  { jp: '古い', kana: 'ふるい', romaji: 'furui', en: 'old', category: 'I-Adjectives' },
  { jp: '静か', kana: 'しずか', romaji: 'shizuka', en: 'quiet', category: 'Na-Adjectives' },
  { jp: '綺麗', kana: 'きれい', romaji: 'kirei', en: 'pretty / clean', category: 'Na-Adjectives' },
  { jp: '便利', kana: 'べんり', romaji: 'benri', en: 'convenient', category: 'Na-Adjectives' },
  { jp: '車', kana: 'くるま', romaji: 'kuruma', en: 'car', category: 'Nouns' },
  { jp: '水', kana: 'みず', romaji: 'mizu', en: 'water', category: 'Nouns' },
  { jp: '本', kana: 'ほん', romaji: 'hon', en: 'book', category: 'Nouns' },
  { jp: '時間', kana: 'じかん', romaji: 'jikan', en: 'time / hours', category: 'Nouns' },
  { jp: 'ホテル', kana: 'ほてる', romaji: 'hoteru', en: 'hotel', category: 'Katakana' },
  { jp: 'タクシー', kana: 'たくしー', romaji: 'takushii', en: 'taxi', category: 'Katakana' },
  { jp: 'コンピューター', kana: 'こんぴゅーたー', romaji: 'konpyuutaa', en: 'computer', category: 'Katakana' },
];

export const N4_VOCABULARY = [
  { jp: '調べる', kana: 'しらべる', romaji: 'shiraberu', en: 'to investigate / examine / check', category: 'Verbs' },
  { jp: '直す', kana: 'なおす', romaji: 'naosu', en: 'to fix / repair', category: 'Verbs' },
  { jp: '故障する', kana: 'こしょうする', romaji: 'koshou suru', en: 'to break down / malfunction', category: 'Verbs' },
  { jp: '点検する', kana: 'てんけんする', romaji: 'tenken suru', en: 'to inspect / check over', category: 'Verbs' },
  { jp: '運ぶ', kana: 'はこぶ', romaji: 'hakobu', en: 'to carry / transport', category: 'Verbs' },
  { jp: '危険', kana: 'きけん', romaji: 'kiken', en: 'dangerous / hazard', category: 'Na-Adjectives' },
  { jp: '複雑', kana: 'ふくざつ', romaji: 'fukuzatsu', en: 'complex / complicated', category: 'Na-Adjectives' },
  { jp: '安全', kana: 'あんぜん', romaji: 'anzen', en: 'safe / security', category: 'Na-Adjectives' },
  { jp: '機械', kana: 'きかい', romaji: 'kikai', en: 'machine / machinery', category: 'Nouns' },
  { jp: '部品', kana: 'ぶひん', romaji: 'buhin', en: 'spare parts / components', category: 'Nouns' },
  { jp: '道具', kana: 'どうぐ', romaji: 'dougu', en: 'tool / equipment', category: 'Nouns' },
  { jp: '報告書', kana: 'ほうこくしょ', romaji: 'houkokusho', en: 'written report', category: 'Nouns' },
  { jp: '必ず', kana: 'かならず', romaji: 'kanarazu', en: 'certainly / without fail', category: 'Adverbs' },
  { jp: '大体', kana: 'だいたい', romaji: 'daitai', en: 'generally / roughly', category: 'Adverbs' },
];

export const N5_MOCK_EXAM = {
  title: 'Official JLPT N5 Full Simulation Test',
  audioTracks: [
    { id: 'n5-a-1', title: 'Task-Based Listening (課題理解)', src: '/audio/japanese/n5/captured-media-0-mp3.mp3', duration: '4:52' },
    { id: 'n5-a-2', title: 'Point Comprehension (ポイント理解)', src: '/audio/japanese/n5/captured-media-1-mp3.mp3', duration: '2:01' },
    { id: 'n5-a-3', title: 'Utterance Expressions (発話表現)', src: '/audio/japanese/n5/captured-media-2-mp3.mp3', duration: '1:58' },
    { id: 'n5-a-4', title: 'Quick Response (即時応答)', src: '/audio/japanese/n5/captured-media-3-mp3.mp3', duration: '14:12' },
  ],
  questions: [
    {
      id: 'q1',
      section: 'Kanji & Vocabulary',
      question: 'あの　<u>ひと</u>は　だれですか。',
      options: ['木', '人', '入', '大'],
      correct: 1,
      explanation: '「ひと」is written as「人」.',
    },
    {
      id: 'q2',
      section: 'Kanji & Vocabulary',
      question: 'まいあさ　<u>みず</u>を　のみます。',
      options: ['水', '木', '金', '土'],
      correct: 0,
      explanation: '「みず」is written as「水」.',
    },
    {
      id: 'q3',
      section: 'Grammar',
      question: 'わたしは　きのう　ともだち（　）　映画を　見ました。',
      options: ['に', 'で', 'と', 'を'],
      correct: 2,
      explanation: 'Particle「と」indicates doing an action "together with" someone.',
    },
    {
      id: 'q4',
      section: 'Grammar',
      question: 'すみませんが、この漢字の読み方を（　）ください。',
      options: ['教えて', '教える', '教えた', '教え'],
      correct: 0,
      explanation: 'Requests take the [て-form] + ください: 教えてください。',
    },
    {
      id: 'q5',
      section: 'Reading',
      question: '【メモ】「山田さんへ。今日の会議は３階の部屋で２時から始まります。」\n質問：会議はどこで何時からですか。',
      options: ['２階で３時から', '３階で２時から', '３階で３時から', '２階で２時から'],
      correct: 1,
      explanation: 'The note clearly states「３階の部屋で２時から」(On 3rd floor starting at 2:00).',
    },
  ],
};

export const N4_MOCK_EXAM = {
  title: 'Official JLPT N4 Full Simulation Test',
  audioTracks: [
    { id: 'n4-a-1', title: 'Task-Based Comprehension (課題理解)', src: '/audio/japanese/n4/captured-media-0-mp3.mp3', duration: '5:39' },
    { id: 'n4-a-2', title: 'Point Comprehension (ポイント理解)', src: '/audio/japanese/n4/captured-media-1-mp3.mp3', duration: '21:26' },
    { id: 'n4-a-3', title: 'Utterance Expressions (発話表現)', src: '/audio/japanese/n4/captured-media-2-mp3.mp3', duration: '2:03' },
    { id: 'n4-a-4', title: 'Quick Response (即時応答)', src: '/audio/japanese/n4/captured-media-3-mp3.mp3', duration: '2:32' },
  ],
  questions: [
    {
      id: 'n4-q1',
      section: 'Kanji & Vocabulary',
      question: 'あしたの　<u>かいぎ</u>は　１０時からです。',
      options: ['会社', '会議', '会場', '会話'],
      correct: 1,
      explanation: '「かいぎ」is written as「会議」.',
    },
    {
      id: 'n4-q2',
      section: 'Grammar',
      question: 'この靴は　軽くて　とても（　）やすいです。',
      options: ['歩き', '歩く', '歩いて', '歩いた'],
      correct: 0,
      explanation: 'The suffix「〜やすい」attaches to the Verb [ます-stem]: 歩きやすい (easy to walk in).',
    },
    {
      id: 'n4-q3',
      section: 'Grammar',
      question: '時間が　（　）なら、手伝ってください。',
      options: ['ある', 'あった', 'あって', 'あります'],
      correct: 0,
      explanation: 'The conditional「なら」attaches to dictionary form: 時間があるなら (if you have time).',
    },
  ],
};
