export const CONTENT_PILLARS = [
  { id: 'pillar_authority', label: 'Brand Authority & Japanese Heritage', color: 'bg-sky-50 text-sky-800 border-sky-200', tagColor: 'sky', targetPct: 20, desc: 'Highlighting Komatsu Japanese precision, Dar Al Hay partnership, and Kuwait infrastructure leadership.' },
  { id: 'pillar_engineering', label: 'Technical & Product Specs', color: 'bg-indigo-50 text-indigo-800 border-indigo-200', tagColor: 'indigo', targetPct: 25, desc: 'Deep-dive machine walkthroughs, specs, KOMTRAX telematics, and heavy-duty desert cooling systems.' },
  { id: 'pillar_workshop', label: 'Workshop BTS & Overhauls', color: 'bg-amber-50 text-amber-800 border-amber-200', tagColor: 'amber', targetPct: 20, desc: 'Certified engineers, engine overhauls, diagnostic testing, and parts warehouse inventory in Shuwaikh.' },
  { id: 'pillar_projects', label: 'Kuwait Jobsites & Case Studies', color: 'bg-emerald-50 text-emerald-800 border-emerald-200', tagColor: 'emerald', targetPct: 20, desc: 'Real-world machinery performance at Sabah Al-Ahmad Sea City, desert earthworks, and highway projects.' },
  { id: 'pillar_leadgen', label: 'After-Sales & Spare Parts', color: 'bg-rose-50 text-rose-800 border-rose-200', tagColor: 'rose', targetPct: 15, desc: 'Emergency field service, genuine parts direct delivery, EQP maintenance contracts, and machine sales.' },
];

export const FORMAT_TYPES = [
  { id: 'reel', label: 'Reels / Motion Video', icon: '🎬', tag: 'Motion Video', color: 'bg-purple-50 text-purple-800 border-purple-200' },
  { id: 'carousel', label: 'Carousels (Multi-Slide)', icon: '📑', tag: 'Swipe Deck', color: 'bg-indigo-50 text-indigo-800 border-indigo-200' },
  { id: 'photography', label: 'Hero Photography', icon: '📸', tag: 'Photo Showcase', color: 'bg-emerald-50 text-emerald-800 border-emerald-200' },
  { id: 'designed_post', label: 'Technical Infographic', icon: '🎨', tag: 'Graphic / Data', color: 'bg-amber-50 text-amber-800 border-amber-200' },
  { id: 'cta_post', label: 'Conversion / Inquiry', icon: '🎯', tag: 'Direct Offer', color: 'bg-rose-50 text-rose-800 border-rose-200' },
];

export const GOAL_TYPES = [
  { id: 'brand_awareness', label: 'Brand Awareness & Authority', color: 'bg-sky-50 text-sky-800 border-sky-200' },
  { id: 'product_education', label: 'Product Education & Specs', color: 'bg-indigo-50 text-indigo-800 border-indigo-200' },
  { id: 'lead_generation', label: 'Lead Generation & Sales', color: 'bg-rose-50 text-rose-800 border-rose-200' },
  { id: 'trust_humanize', label: 'Engineering Craft & Trust', color: 'bg-emerald-50 text-emerald-800 border-emerald-200' },
  { id: 'case_study', label: 'Jobsite Validation & Case Study', color: 'bg-amber-50 text-amber-800 border-amber-200' },
  { id: 'expertise', label: 'Preventive Maintenance Guide', color: 'bg-purple-50 text-purple-800 border-purple-200' },
];

export const PIPELINE_STAGES = [
  { id: 'idea', label: 'Concept Draft', icon: '💡', badgeTone: 'neutral' },
  { id: 'scripted', label: 'Scripted & Briefed', icon: '📝', badgeTone: 'info' },
  { id: 'production', label: 'Filming / Designing', icon: '🎬', badgeTone: 'warning' },
  { id: 'review', label: 'Under Review', icon: '👀', badgeTone: 'yellow' },
  { id: 'ready', label: 'Ready to Publish', icon: '🚀', badgeTone: 'active' },
  { id: 'published', label: 'Published', icon: '✅', badgeTone: 'ready' },
];

export const MEDIA_PLATFORMS = [
  { id: 'instagram', label: 'Instagram', icon: '📸', badgeTone: 'active', handle: '@daralhay_komatsu' },
  { id: 'linkedin', label: 'LinkedIn', icon: '💼', badgeTone: 'info', handle: 'Dar Al Hay Commercial Co.' },
  { id: 'facebook', label: 'Facebook', icon: '👥', badgeTone: 'ready', handle: 'Dar Al Hay - Komatsu Kuwait' },
];

export const TOV_GUIDELINES = {
  overall: {
    title: 'Dar Al Hay Brand Voice & Persona',
    summary: 'Authoritative, Precision-Driven, Industrial Strength, and Rooted in Kuwait Progress.',
    traits: [
      { name: 'Japanese Precision & Heritage', desc: 'Emphasize Komatsu factory standards, strict quality controls, and world-leading hydraulic engineering.' },
      { name: 'Kuwait Desert Toughness', desc: 'Acknowledge the harsh 50°C+ climate, fine desert sand, and heavy rock conditions in Kuwait and how our machines conquer them.' },
      { name: 'Unwavering Engineering Authority', desc: 'Talk like certified master engineers and fleet directors — avoid generic sales fluff, focus on uptime, SMR hours, fuel efficiency, and ROI.' },
      { name: 'Customer Partnership', desc: 'Frame Dar Al Hay not just as an equipment seller, but as an indispensable operational partner on Kuwait megaprojects.' },
    ],
  },
  platforms: {
    linkedin: {
      platform: 'LinkedIn',
      tone: 'Authoritative B2B Engineering & Fleet Economics',
      target: 'C-Suite, Procurement Directors, Project Managers, Fleet Supervisors',
      guidelines: 'Focus on total cost of ownership (TCO), fuel economy data, KOMTRAX satellite telemetry, preventive maintenance contracts, and Kuwait project case studies. Use professional terminology and structured bullet points.',
    },
    instagram: {
      platform: 'Instagram',
      tone: 'Visual, High-Energy, Cinematic, & Behind-The-Scenes',
      target: 'Heavy Machinery Operators, Young Engineers, Contractors, Brand Fans',
      guidelines: 'Lead with strong 3-second visual hooks, close-up engine sounds, slow-motion hydraulic action, golden hour desert shots, and relatable maintenance tips.',
    },
    facebook: {
      platform: 'Facebook',
      tone: 'Community-Focused, Accessible, Practical & Bilingual (Arabic First)',
      target: 'Local Subcontractors, Workshop Owners, Equipment Operators, General Public',
      guidelines: 'Clear value propositions, direct WhatsApp/phone contact CTAs, workshop open days, fast spare parts availability, and transparent service offerings in both Arabic and English.',
    },
  },
  doAndDont: [
    { do: 'Use exact technical terms (e.g., PC350LC-8M0, SAA6D114E-3 engine, KOMTRAX, KTCS traction).', dont: 'Use vague generic terms like "our big digger" or "super strong machine".' },
    { do: 'Provide bilingual copy (Arabic + English) with natural professional Gulf/Kuwait phrasing.', dont: 'Rely on automated literal translations that sound robotic or awkward.' },
    { do: 'Highlight certified engineers, PPE safety helmets, clean Shuwaikh workshop, and genuine parts.', dont: 'Show uncertified field repairs without safety gear or messy workshop environments.' },
    { do: 'Include clear Call To Actions with contact numbers, WhatsApp links, and showroom location.', dont: 'Leave posts with no next step for interested fleet managers.' },
  ],
};

export const PRE_PRODUCTION_CHECKLIST = [
  { id: 'permits', category: 'Approvals & Access', task: 'Obtain worksite entry and filming permits (Kuwait Municipality / PAHW / KOC / Client).' },
  { id: 'safety', category: 'Safety & PPE', task: 'Ensure all filming crew and on-screen staff wear Komatsu safety vests, hard hats, and steel-toe boots.' },
  { id: 'cleaning', category: 'Asset Preparation', task: 'Pressure wash machine body, bucket, and tracks; ensure Komatsu & Dar Al Hay branding stickers are clean and visible.' },
  { id: 'camera', category: 'Camera & Lighting', task: 'Pack 4K gimbal stabilizer, wide-angle lens (16-35mm), macro lens for parts, and circular polarizer filter for desert glare.' },
  { id: 'audio', category: 'Audio Gear', task: 'Test dual wireless lapel microphones with deadcat wind protection for clear voiceover in windy desert conditions.' },
  { id: 'talent', category: 'Talent Briefing', task: 'Rehearse spoken script in both Arabic and English with certified service engineer prior to rolling camera.' },
];

export const INITIAL_MONTHLY_CAMPAIGNS = {
  '2026-08': {
    monthId: '2026-08',
    monthName: 'August 2026',
    themeTitle: 'Extreme Desert Heat Endurance & 50°C+ Summer Resilience',
    strategicGoal: 'Position Komatsu high-ambient cooling systems and Dar Al Hay 24/7 mobile field response as the premier solution for zero summer downtime in Kuwait.',
    targetKpi: '25 Qualified Fleet Inquiries • 180,000 Video Views in Kuwait • 95% Positive Engagement',
    pillarDistribution: { pillar_authority: 20, pillar_engineering: 30, pillar_workshop: 20, pillar_projects: 15, pillar_leadgen: 15 },
    concepts: [
      // WEEK 1
      {
        id: 101, conceptNumber: 1, week: 'Week 1', day: 'Sunday', publishDate: '2026-08-02',
        title: 'Hero Machine – PC350LC-8M0 Cinematic Brand Intro', pillar: 'pillar_authority', format: 'reel',
        platforms: ['instagram', 'linkedin', 'facebook'], goal: 'brand_awareness', status: 'published',
        targetAudience: 'Contractors, Government Infrastructure Stakeholders, Fleet Owners',
        tov: 'Cinematic, High-Impact, Authoritative Industrial',
        summary: 'Cinematic 25-sec video intro: Kuwait desert landscape -> Dar Al Hay facility -> Komatsu machine lineup -> Workshop engine rebuild -> Parts warehouse -> Engineering team -> Logo lockup.',
        hook: {
          spokenEn: 'Built for the toughest desert terrain on earth. Meet Komatsu in Kuwait.',
          spokenAr: 'صُنعت لتقهر أصعب تضاريس الصحراء في العالم.. كوماتسو في الكويت.',
          visualHook: 'Rapid cinematic crash-zoom from drone altitude over South Kuwait desert directly into the heavy steel bucket of a Komatsu PC350LC digging through rock.',
        },
        scenes: [
          { sceneNo: 1, time: '0:00 - 0:04', visual: 'Drone establishing shot over Kuwait desert highway at sunrise; transition into low-angle PC350LC track moving forward.', talentAction: 'Machine operator swings boom smoothly into frame.', audioVoiceoverEn: 'Built for the toughest desert terrain on earth.', audioVoiceoverAr: 'صُنعت لتقهر أصعب تضاريس الصحراء في العالم..', onScreenTextEn: 'BUILT FOR KUWAIT | KOMATSU PC350LC', onScreenTextAr: 'صُنعت للكويت | كوماتسو PC350LC', sfxMusic: 'Deep cinematic sub drop + engine roar' },
          { sceneNo: 2, time: '0:04 - 0:10', visual: 'Match-cut to Dar Al Hay modern Shuwaikh facility exterior and heavy showroom.', talentAction: 'Service Engineer in Komatsu uniform walking purposefully toward camera carrying diagnostic tablet.', audioVoiceoverEn: 'Backed by Dar Al Hay’s certified engineering and complete local support.', audioVoiceoverAr: 'بدعم هندسي متكامل وخبرة معتمدة من دار الحي.', onScreenTextEn: 'OFFICIAL KOMATSU DISTRIBUTOR IN KUWAIT', onScreenTextAr: 'الموزع المعتمد لكوماتسو في الكويت', sfxMusic: 'Percussive riser' },
          { sceneNo: 3, time: '0:10 - 0:18', visual: 'Montage inside Shuwaikh workshop: Torque wrench clicking on cylinder head, hydraulic testing bench, parts warehouse.', talentAction: 'Master technician tightening manifold; sparks in soft background.', audioVoiceoverEn: 'Zero-hour rebuilds, 15,000+ genuine parts in stock, and 24/7 mobile field care.', audioVoiceoverAr: 'مراكز صيانة متطورة، أكثر من 15,000 قطعة غيار أصلية جاهزة، وفرق دعم ميداني 24/7.', onScreenTextEn: 'GENUINE PARTS • CERTIFIED OVERHAULS', onScreenTextAr: 'قطع أصلية • صيانة معتمدة', sfxMusic: 'Ratchet foley + synthesizer pulse' },
        ],
        brollChecklist: ['Drone slow-mo flyby over desert excavator at sunrise', 'Macro close-up of hydraulic hoses flexing under 350 bar', 'Shuwaikh warehouse aisle showing barcoded genuine Komatsu yellow boxes'],
        postProductionNotes: 'Warm desert contrast with true Komatsu yellow and navy grading.',
        captionEn: 'From high-speed national highway networks to deep desert earthworks, Komatsu heavy machinery powers Kuwait’s progress.\n\nBacked by Dar Al Hay’s factory-trained engineers, extensive genuine parts inventory in Shuwaikh, and 24/7 mobile field service.',
        captionAr: 'من شبكات الطرق السريعة ومشاريع البنية التحتية الكبرى إلى أضخم أعمال الردم والإنشاءات، تواصل معدات كوماتسو ريادتها في الكويت.\n\nمدعومة بخبرات دار الحي الهندسية المعتمدة، ومخزون متكامل من قطع الغيار الأصلية في الشويخ.',
        hashtags: '#Komatsu #DarAlHay #KuwaitConstruction #HeavyMachinery #PC350LC #Excavator #KuwaitEngineers #Shuwaikh',
        ctaText: 'Visit our Shuwaikh showroom or call our heavy equipment sales desk.',
        slides: [],
      },
      {
        id: 102, conceptNumber: 2, week: 'Week 1', day: 'Tuesday', publishDate: '2026-08-04',
        title: 'Dar Al Hay Complete Partnership Ecosystem', pillar: 'pillar_authority', format: 'carousel',
        platforms: ['linkedin', 'instagram', 'facebook'], goal: 'brand_awareness', status: 'published',
        targetAudience: 'Fleet Managers, Maintenance Directors, Construction Contractors',
        tov: 'Corporate, Educational, Consultative',
        summary: '5-slide carousel explaining the relationship between Dar Al Hay & Komatsu, services provided, industries served, and contact CTA.',
        hook: { spokenEn: 'More than just heavy machines: How Dar Al Hay protects your fleet lifecycle in Kuwait.', spokenAr: 'أكثر من مجرد توريد آليات.. كيف تحمي دار الحي استثمارك وأسطولك في الكويت.', visualHook: 'High-contrast graphic showing a Komatsu excavator split into 5 operational support sectors.' },
        scenes: [], brollChecklist: ['Studio photo of Komatsu diagnostic tools', 'Clean exterior photo of Shuwaikh service complex'],
        postProductionNotes: '1080x1350 vertical carousel format.',
        captionEn: 'Purchasing heavy machinery is an investment. Ensuring that machine delivers maximum uptime over 10,000+ operating hours is where Dar Al Hay makes the difference.\n\nSwipe through to see our complete engineering ecosystem.',
        captionAr: 'شراء المعدات الثقيلة استثمار استراتيجي. وضمان عمل هذه المعدات بأعلى كفاءة لأكثر من 10,000 ساعة تشغيل هو ما تصنعه شراكتك مع دار الحي.\n\nاسحب الشاشة للتعرف على التفاصيل.',
        hashtags: '#DarAlHay #KomatsuKuwait #FleetManagement #PreventiveMaintenance #AssetLifecycle',
        ctaText: 'Swipe through to learn more -> Save this post for your fleet maintenance guide.',
        slides: [
          { slideNo: 1, title: 'Official Komatsu Partnership in Kuwait', body: 'Decades of engineering leadership delivering certified Japanese heavy machinery designed for high-ambient desert endurance.' },
          { slideNo: 2, title: 'Full Machinery Fleet Portfolio', body: 'Hydraulic excavators (20T to 50T), articulated haulers, large wheel loaders, and heavy bulldozers tailored for Kuwait rock and sand.' },
          { slideNo: 3, title: 'Industries We Power Every Day', body: 'Civil infrastructure, mega-highways, marine reclamation, coastal works, aggregate quarrying, and desert development.' },
          { slideNo: 4, title: 'Complete Lifecycle Care (EQP)', body: 'Scheduled 250h/500h/1000h preventive maintenance, KOMTRAX satellite telemetry, and oil analysis to prevent breakdowns.' },
          { slideNo: 5, title: 'Partner With Dar Al Hay Today', body: 'Contact our heavy equipment team to schedule your fleet inspection or request a customized maintenance proposal.' },
        ],
      },
      {
        id: 103, conceptNumber: 3, week: 'Week 1', day: 'Thursday', publishDate: '2026-08-06',
        title: 'Hero Machine on Site – Low-Angle Power Shot in South Kuwait', pillar: 'pillar_projects', format: 'photography',
        platforms: ['instagram', 'linkedin', 'facebook'], goal: 'brand_awareness', status: 'published',
        targetAudience: 'Civil Engineers, Project Directors, Equipment Enthusiasts',
        tov: 'Inspirational, Bold, High-Aesthetic Industrial',
        summary: 'Powerful low-angle environmental photograph of a Komatsu PC500LC operating at Sabah Al-Ahmad Sea City with golden hour sunset lighting.',
        hook: { spokenEn: 'Power meets precision against the Kuwait golden hour.', spokenAr: 'القوة تجتمع مع الدقة مع غروب شمس الكويت.', visualHook: 'Ultra-low 24mm wide angle photo with dust backlighting.' },
        scenes: [], brollChecklist: ['High-res photography from ground level looking up at boom', 'Golden hour rim light catching sand dust'],
        postProductionNotes: 'Sharpen metallic textures, enhance warm desert tones.',
        captionEn: 'Built to dominate heavy excavation in 50°C+ summer heat. The Komatsu PC500LC delivers relentless breakout force with advanced hydraulic efficiency.\n\n📍 On site in South Kuwait earthmoving projects.',
        captionAr: 'مصممة للعمل الشاق المتواصل في درجات حرارة تتجاوز 50 درجة مئوية. حفارة كوماتسو PC500LC تمنحك أقصى قوة كسر وحفر مع كفاءة استثنائية في استهلاك الوقود.\n\n📍 موقع العمل - جنوب الكويت.',
        hashtags: '#Komatsu #PC500LC #HeavyEquipmentPhotography #KuwaitConstruction #DarAlHay #GoldenHour',
        ctaText: 'Follow @daralhay_komatsu for daily machinery operations.',
        slides: [],
      },

      // WEEK 2
      {
        id: 104, conceptNumber: 4, week: 'Week 2', day: 'Sunday', publishDate: '2026-08-09',
        title: 'Why Genuine Komatsu Parts? – The True Cost of Cheap Filters', pillar: 'pillar_engineering', format: 'carousel',
        platforms: ['linkedin', 'facebook', 'instagram'], goal: 'product_education', status: 'ready',
        targetAudience: 'Fleet Maintenance Engineers, Procurement Officers, Workshop Managers',
        tov: 'Analytical, Factual, Educational & Persuasive',
        summary: 'Explaining genuine parts reliability, exact tolerances, desert heat filtration, warranty protection, and long-term lifecycle savings.',
        hook: { spokenEn: 'Are non-genuine filters costing you thousands in silent downtime? Here is the proof.', spokenAr: 'هل تكلفك قطع الغيار المقلدة آلاف الدنانير في التوقف المفاجئ؟ إليك الدليل العلمي.', visualHook: 'Microscope side-by-side graphic comparing genuine Komatsu micro-glass filter media vs generic paper filter.' },
        scenes: [], brollChecklist: ['Macro cut-section of genuine hydraulic filter', 'Barcoded packaging on warehouse shelves'],
        postProductionNotes: 'Blueprint styling with clean callouts.',
        captionEn: 'In Kuwait’s fine sand and extreme summer temperatures, a substandard hydraulic filter can cause catastrophic pump failure in under 200 hours. Protect your investment with genuine Komatsu components.',
        captionAr: 'في بيئة العمل الصحراوية والحرارة الشديدة بالكويت، استخدام فلاتر غير أصلية قد يسبب أعطالاً مفاجئة في المضخات خلال أقل من 200 ساعة. احمِ استثمارك بقطع غيار كوماتسو الأصلية.',
        hashtags: '#GenuineParts #KomatsuParts #DarAlHay #FleetMaintenance #HydraulicFilters #TCO',
        ctaText: 'Order genuine parts directly through our Shuwaikh warehouse.',
        slides: [
          { slideNo: 1, title: 'The Desert Filtration Challenge', body: 'Kuwait sand particles measure down to 5 microns. Aftermarket paper filters let up to 40% of micro-debris pass into your hydraulic pumps.' },
          { slideNo: 2, title: 'Micro-Glass Multi-Layer Media', body: 'Genuine Komatsu filters feature synthetic micro-glass fibers capturing 99.8% of micro-particles without restricting oil flow.' },
          { slideNo: 3, title: 'High-Temperature Oil Seals', body: 'Formulated to withstand 120°C continuous oil temperatures without hardening, cracking, or leaking hydraulic pressure.' },
          { slideNo: 4, title: 'Zero Warranty & Asset Risk', body: 'Genuine parts keep your factory warranty intact and preserve maximum resale value across your entire fleet.' },
          { slideNo: 5, title: '15,000+ Lines in Shuwaikh', body: 'Direct access to Kuwait’s largest genuine Komatsu inventory with immediate site dispatch.' },
        ],
      },
      {
        id: 105, conceptNumber: 5, week: 'Week 2', day: 'Tuesday', publishDate: '2026-08-11',
        title: 'Machine Walkaround – WA600 Heavy Specs in Kuwait', pillar: 'pillar_engineering', format: 'reel',
        platforms: ['instagram', 'linkedin', 'facebook'], goal: 'product_education', status: 'ready',
        targetAudience: 'Contractors, Quarry Operators, Site Supervisors',
        tov: 'Instructive, Engaging, Expert-Led & Technical',
        summary: 'Service Engineer walks around the WA600 Wheel Loader and explains 3 critical design advantages for Kuwait quarry & earthmoving operations.',
        hook: { spokenEn: '3 reasons why contractors choose the Komatsu WA600 for heavy sand and quarry loading in Kuwait.', spokenAr: '3 أسباب تجعل لودر كوماتسو WA600 الخيار الأول لشركات المقاولات والكسارات في الكويت.', visualHook: 'Engineer taps the massive 6.4 cubic meter reinforced bucket with a wrench, stepping into camera frame.' },
        scenes: [
          { sceneNo: 1, time: '0:00 - 0:05', visual: 'Engineer standing next to the massive front wheel of WA600, pointing up to lift arms.', talentAction: 'Engineer addresses camera with high energy.', audioVoiceoverEn: 'If you are moving thousands of tons of sand in Kuwait, here is why the WA600 dominates.', audioVoiceoverAr: 'إذا كنت تنقل آلاف الأطنان من الرمال والصخور في الكويت، إليك سر تفوق لودر كوماتسو WA600.', onScreenTextEn: 'KOMATSU WA600 | 3 KEY SPECS', onScreenTextAr: 'كوماتسو WA600 | 3 مميزات', sfxMusic: 'Energetic beat' },
          { sceneNo: 2, time: '0:05 - 0:12', visual: 'Open engine compartment showing high-ambient radiator core and auto-reversible cooling fan.', talentAction: 'Engineer demonstrates reversible fan dust purging.', audioVoiceoverEn: 'First: High-ambient cooling package with an auto-reversible fan that blows out desert sand build-up automatically.', audioVoiceoverAr: 'أولاً: نظام تبريد صحراوي ومروحة عكسية تنظف الرادياتير من الغبار تلقائياً.', onScreenTextEn: '1. AUTO-REVERSIBLE FAN', onScreenTextAr: '1. مروحة تبريد عكسية', sfxMusic: 'Air purge whoosh' },
        ],
        brollChecklist: ['Gimbal orbit around front bucket', 'Close-up of tire treads in soft sand'],
        postProductionNotes: 'Crisp callout graphics pointing to mechanical elements.',
        captionEn: 'Technical walkaround of the powerhouse Komatsu WA600 Wheel Loader.\n\nEngineered for massive bucket payloads, rapid cycle times, and operator endurance in Kuwait’s toughest conditions.',
        captionAr: 'جولة تقنية سريعة للتعرف على أسرار لودر كوماتسو WA600 العملاق.\n\nمصمم للتحميل الثقيل وسرعة دورات العمل في أصعب مواقع الكويت.',
        hashtags: '#KomatsuWA600 #WheelLoader #EarthmovingKuwait #DarAlHayEngineering #HeavyMachinery',
        ctaText: 'Comment "WA600" to receive the full technical spec sheet.',
        slides: [],
      },
      {
        id: 106, conceptNumber: 6, week: 'Week 2', day: 'Thursday', publishDate: '2026-08-13',
        title: 'Inside Our Workshop – Engine & Component Overhaul Standards', pillar: 'pillar_workshop', format: 'reel',
        platforms: ['linkedin', 'instagram', 'facebook'], goal: 'trust_humanize', status: 'production',
        targetAudience: 'Fleet Directors, Heavy Equipment Mechanics, Business Owners',
        tov: 'Authentic, High-Craftsmanship, Industrial',
        summary: 'BTS inside the Dar Al Hay central workshop: diagnostic computers, cylinder honing, injector calibration, and precision torque wrenching.',
        hook: { spokenEn: 'Behind the scenes where million-dollar heavy machines get restored to factory zero-hour precision.', spokenAr: 'خلف الكواليس.. كيف نعيد محركات الآليات الثقيلة إلى كفاءة الصفر ساعة في دار الحي.', visualHook: 'Overhead crane slowly lowering a massive 6-cylinder Komatsu turbo diesel engine block onto the rebuild stand.' },
        scenes: [], brollChecklist: ['Macro slow-mo oil pouring over camshaft', 'Electronic torque wrench digital beep readout'],
        postProductionNotes: 'Industrial sound design with ratchet clicks.',
        captionEn: 'Factory-standard diagnostic equipment, Komatsu-certified master technicians, and genuine overhaul kits.\n\nStep inside the Dar Al Hay central service facility in Shuwaikh, Kuwait.',
        captionAr: 'أحدث أجهزة الفحص والتشخيص المعتمدة عالمياً، مع كادر فني معتمد وقطع غيار أصلية 100%.\n\nنظرة من داخل مركز صيانة دار الحي الرئيسي بالشويخ.',
        hashtags: '#DarAlHayWorkshop #KomatsuService #EngineOverhaul #KuwaitEngineering #Shuwaikh',
        ctaText: 'Schedule a certified workshop overhaul for your fleet.',
        slides: [],
      },

      // WEEK 3
      {
        id: 107, conceptNumber: 7, week: 'Week 3', day: 'Sunday', publishDate: '2026-08-16',
        title: 'KOMTRAX Telematics – Satellite Fleet Intelligence on Your Phone', pillar: 'pillar_engineering', format: 'carousel',
        platforms: ['linkedin', 'facebook', 'instagram'], goal: 'product_education', status: 'scripted',
        targetAudience: 'Fleet Managers, Operations Directors, CFOs',
        tov: 'Data-Driven, Modern, Tech-Savvy',
        summary: 'How KOMTRAX satellite tracking monitors fuel burn, idle time, operator habits, and health codes live from any Kuwait jobsite.',
        hook: { spokenEn: 'How Kuwait fleet owners monitor 50 machines across the desert from a single smartphone screen.', spokenAr: 'كيف يتابع مدراء الأساطيل في الكويت أكثر من 50 معدة في عمق الصحراء من شاشة هاتف واحدة؟', visualHook: 'Smartphone screen showing live satellite map of Kuwait with green machine status pins.' },
        scenes: [], brollChecklist: ['KOMTRAX mobile app UI screencast', 'Antenna module on top of excavator cab'],
        postProductionNotes: 'High-tech graphic overlays with telemetry graphs.',
        captionEn: 'Never wonder where your diesel is going. KOMTRAX satellite telematics gives fleet directors real-time visibility into working hours, idle time, and maintenance alerts across Kuwait.\n\nSwipe through to see KOMTRAX in action.',
        captionAr: 'لا تدع الوقود يُهدر دون رقابة. نظام المتابعة عبر الأقمار الصناعية KOMTRAX يمنحك رؤية فورية لساعات التشغيل والوقود وحالة المعدات في أي موقع بالكويت.\n\nاسحب الشاشة للتعرف على النظام.',
        hashtags: '#KOMTRAX #FleetTelematics #SmartConstruction #KomatsuKuwait #FleetEfficiency',
        ctaText: 'Activate KOMTRAX fleet tracking on your machinery today.',
        slides: [
          { slideNo: 1, title: 'Satellite-Connected Heavy Fleets', body: 'KOMTRAX transmitters broadcast machine location, SMR hours, and fuel consumption via satellite 24/7.' },
          { slideNo: 2, title: 'Eliminate Fuel Waste & Idle Time', body: 'Identify operators leaving engines idling during hot afternoon breaks. Cut monthly diesel bills by up to 18%.' },
          { slideNo: 3, title: 'Instant Error Code Alerts', body: 'Receive immediate alerts before a small sensor fault turns into an expensive site shutdown.' },
          { slideNo: 4, title: 'Automated Service Scheduling', body: 'Dar Al Hay engineers monitor your fleet hours remotely and schedule 250h/500h service before intervals lapse.' },
          { slideNo: 5, title: 'Complimentary with Komatsu Machines', body: 'Factory-installed on every new Komatsu machine delivered by Dar Al Hay in Kuwait.' },
        ],
      },
      {
        id: 108, conceptNumber: 8, week: 'Week 3', day: 'Tuesday', publishDate: '2026-08-18',
        title: 'Emergency Mobile Field Service – Dispatched to Abdali Highway', pillar: 'pillar_leadgen', format: 'reel',
        platforms: ['instagram', 'linkedin', 'facebook'], goal: 'lead_generation', status: 'scripted',
        targetAudience: 'Site Supervisors, Highway Contractors, Quarry Managers',
        tov: 'Urgent, Action-Oriented, Reassuring',
        summary: 'Follow Dar Al Hay’s heavy field service truck responding to an urgent hydraulic line call in the desert within 90 minutes.',
        hook: { spokenEn: 'When a machine stops on a remote desert jobsite, this is our 90-minute mobile response team.', spokenAr: 'عندما تتوقف آلية في موقع صحراوي ناءٍ.. هكذا تستجيب فرق الصيانة الميدانية لدار الحي في 90 دقيقة.', visualHook: 'Service van headlights cutting through morning desert dust with mobile crane arm unfolding.' },
        scenes: [], brollChecklist: ['Field truck rolling on desert road', 'Technician using portable hydraulic hose crimper'],
        postProductionNotes: 'Documentary style with fast cuts and urgent pacing.',
        captionEn: 'Downtime costs money. When unexpected field repairs happen on Kuwait jobsites, Dar Al Hay’s mobile service fleet brings certified engineers, hydraulic crimpers, and genuine parts directly to your machine.\n\n📞 24/7 Emergency Hotline ready for dispatch.',
        captionAr: 'كل دقيقة توقف تكلفك مالاً. عند حدوث أي طارئ في مواقع العمل بالكويت، تتحرك ورش دار الحي المتنقلة بكامل التجهيزات الهندسية وقطع الغيار الأصلية إلى موقعك مباشرة.\n\n📞 خط الطوارئ الميداني جاهز على مدار الساعة.',
        hashtags: '#FieldService #EmergencyRepair #DarAlHay #KomatsuSupport #HeavyEquipmentService #KuwaitContractors',
        ctaText: 'Save our 24/7 Field Service Dispatch number in your phone today.',
        slides: [],
      },
      {
        id: 109, conceptNumber: 9, week: 'Week 3', day: 'Thursday', publishDate: '2026-08-20',
        title: 'Undercarriage Wear Guide – Extending Track Life in Sand', pillar: 'pillar_workshop', format: 'carousel',
        platforms: ['linkedin', 'facebook', 'instagram'], goal: 'expertise', status: 'idea',
        targetAudience: 'Equipment Operators, Workshop Superintendents, Fleet Owners',
        tov: 'Educational, Practical, Maintenance-Focused',
        summary: 'Step-by-step visual guide on measuring track chain sag, sprocket wear, and pin turning to prevent premature track replacement.',
        hook: { spokenEn: 'The 5-minute track inspection that saves fleet owners 8,000 KD in undercarriage wear.', spokenAr: 'فحص بسيط لمدة 5 دقائق يحمي جنازير آلياتك من التآكل ويوفر آلاف الدنانير.', visualHook: 'Engineer measuring track chain tension sag with a steel ruler against track shoe.' },
        scenes: [], brollChecklist: ['Close-up of track shoe grouser bar height', 'Comparison of sharp worn sprocket vs new Komatsu sprocket'],
        postProductionNotes: 'Infographic style with dimension arrows.',
        captionEn: 'Undercarriage represents nearly 50% of an excavator’s lifetime maintenance cost. In Kuwait’s abrasive sand, proper track tension and timely pin turns extend chain life by thousands of hours.\n\nSwipe through for our master technician’s undercarriage guide.',
        captionAr: 'تمثل الجنازير والقطع السفلية نحو 50% من تكلفة صيانة الحفارة على مدار عمرها. في رمال الكويت الحارقة، الضبط الصحيح للشد وتدوير المسامير في الوقت المناسب يضاعف عمر الجنزير.\n\nاسحب الشاشة للتعرف على نصائح الفحص.',
        hashtags: '#Undercarriage #TrackMaintenance #ExcavatorTracks #PreventiveMaintenance #KomatsuKuwait #DarAlHay',
        ctaText: 'Book a free undercarriage wear inspection by Dar Al Hay certified engineers.',
        slides: [
          { slideNo: 1, title: 'Check Track Chain Tension Sag', body: 'Tracks that are too tight increase bushing friction by 300% in sand. Maintain 10–15mm sag per Komatsu factory specs.' },
          { slideNo: 2, title: 'Inspect Drive Sprocket Teeth', body: 'Worn pointed sprocket teeth accelerate link damage. Replace before teeth wear down to a sharp profile.' },
          { slideNo: 3, title: 'Turn Pins & Bushings at 3,000h', body: 'Turning pins 180 degrees doubles bushing life before full replacement is required.' },
          { slideNo: 4, title: 'Clean Sand Packed in Rollers', body: 'Packed clay and sand lock carrier rollers, creating flat spots on steel rollers.' },
          { slideNo: 5, title: 'Free Ultrasonic Wear Measurement', body: 'Contact Dar Al Hay for an on-site ultrasonic undercarriage wear report for your entire fleet.' },
        ],
      },

      // WEEK 4
      {
        id: 110, conceptNumber: 10, week: 'Week 4', day: 'Sunday', publishDate: '2026-08-23',
        title: 'Komatsu D155A Heavy Dozer – Pushing Desert Dunes in South Kuwait', pillar: 'pillar_projects', format: 'reel',
        platforms: ['instagram', 'linkedin', 'facebook'], goal: 'case_study', status: 'idea',
        targetAudience: 'Earthmoving Contractors, Highway Builders, Land Reclamation Firms',
        tov: 'Massive Power, High-Octane, Cinematic',
        summary: 'High-energy 20-sec reel showing the Komatsu D155A Crawler Dozer leveling massive sand dunes at 45° slope in extreme summer heat.',
        hook: { spokenEn: '350 horsepower of raw Japanese pushing force conquering Kuwait sand dunes.', spokenAr: '350 حصان من القوة اليابانية الهادرة تروّض رمال وكثبان الكويت.', visualHook: 'Front blade pushing a 9-cubic-meter wall of red sand with turbo spool whistle.' },
        scenes: [], brollChecklist: ['Drone tracking shot parallel to moving dozer blade', 'Slow motion track shoes biting into soft dune'],
        postProductionNotes: 'Heavy bass sound design with metallic track clinking.',
        captionEn: 'Massive blade capacity, low ground pressure, and legendary lock-up torque transmission. The Komatsu D155A Crawler Dozer makes light work of Kuwait’s largest desert earthworks.\n\n🚜 Available for fleet delivery across Kuwait through Dar Al Hay.',
        captionAr: 'سعة جرف هائلة، وتوزيع مثالي للوزن على الرمال الناعمة، وناقل حركة متطور. بلدوزر كوماتسو D155A ينجز أضخم مشاريع تسوية الأراضي والصحراء في الكويت.\n\n🚜 متوفر للتوريد الفوري عبر شركة دار الحي.',
        hashtags: '#KomatsuD155A #CrawlerDozer #BulldozerKuwait #DesertEarthworks #HeavyMachinery #DarAlHay',
        ctaText: 'Request dozer specifications and fleet delivery timelines today.',
        slides: [],
      },
      {
        id: 111, conceptNumber: 11, week: 'Week 4', day: 'Tuesday', publishDate: '2026-08-25',
        title: 'Fleet Preventive Maintenance Contracts (EQP) Explained', pillar: 'pillar_leadgen', format: 'carousel',
        platforms: ['linkedin', 'facebook', 'instagram'], goal: 'lead_generation', status: 'idea',
        targetAudience: 'Contracting CFOs, Procurement Directors, Project Managers',
        tov: 'Commercial, Strategic, Cost-Savings Focus',
        summary: 'Comparing unscheduled emergency repairs vs fixed-price Dar Al Hay EQP maintenance agreements over 5,000 operating hours.',
        hook: { spokenEn: 'Why top Kuwait contractors choose fixed-price maintenance agreements over breakdown surprises.', spokenAr: 'لماذا تفضل كبرى شركات المقاولات في الكويت عقود الصيانة الوقائية الشاملة؟', visualHook: 'Side-by-side cost comparison graph: Unpredictable breakdown expenses vs flat predictable EQP agreement.' },
        scenes: [], brollChecklist: ['Dar Al Hay signed agreement document graphic', 'Service engineer stamping certified maintenance book'],
        postProductionNotes: 'Executive corporate styling with clean typography.',
        captionEn: 'Predictable maintenance costs, certified Japanese parts, zero surprise breakdown bills. Dar Al Hay’s EQP Maintenance Contracts protect your equipment ROI over 5,000+ operating hours.\n\nSwipe through to see the financial case for scheduled fleet care.',
        captionAr: 'تكاليف صيانة ثابتة ومدروسة، قطع غيار أصلية 100%، وضمان ضد التوقف المفاجئ. عقود الصيانة الشاملة EQP من دار الحي تحمي أسطولك وعوائد مشاريعك.\n\nاسحب الشاشة للمقارنة المالية.',
        hashtags: '#FleetMaintenance #EQPContract #TCO #ContractorFinance #KomatsuKuwait #DarAlHay',
        ctaText: 'Contact our heavy equipment team for a customized fleet maintenance proposal.',
        slides: [
          { slideNo: 1, title: 'The Hidden Cost of Breakdown Culture', body: 'Unscheduled breakdowns cost up to 4x more than scheduled care when factoring in idle operators and project delay penalties.' },
          { slideNo: 2, title: 'Fixed Per-Hour Maintenance Rates', body: 'Know your exact operating cost per machine hour down to the fils. No hidden charges or surprise invoices.' },
          { slideNo: 3, title: 'Certified Fluid Sampling & Telemetry', body: 'Includes regular KOWA oil laboratory diagnostics and KOMTRAX satellite health monitoring.' },
          { slideNo: 4, title: 'Priority Dispatch & Standby Units', body: 'Contract holders receive guaranteed priority field response and preferential parts pricing across Kuwait.' },
          { slideNo: 5, title: 'Tailored for Your Fleet Size', body: 'From single-machine operators to 100+ unit civil contractors. Request your customized proposal today.' },
        ],
      },
      {
        id: 112, conceptNumber: 12, week: 'Week 4', day: 'Thursday', publishDate: '2026-08-27',
        title: 'Monthly Campaign Wrap-Up – Zero Summer Downtime Achieved', pillar: 'pillar_authority', format: 'photography',
        platforms: ['instagram', 'linkedin', 'facebook'], goal: 'brand_awareness', status: 'idea',
        targetAudience: 'General Industry Stakeholders, Operators, Partners',
        tov: 'Proud, Celebrating Success, Community-Focused',
        summary: 'Group photo of Dar Al Hay service engineering team standing proudly in front of a newly delivered Komatsu fleet lineup in Shuwaikh.',
        hook: { spokenEn: 'Another summer of Kuwait megaprojects powered with zero downtime.', spokenAr: 'صيف آخر من الإنجاز وبناء مشاريع الكويت دون توقف.. مع دار الحي وكوماتسو.', visualHook: 'Wide group portrait of engineers and technicians in crisp uniforms with fleet in background.' },
        scenes: [], brollChecklist: ['Wide photography of team in Shuwaikh yard', 'Close-up of engineer smiling with hardhat'],
        postProductionNotes: 'Bright, clean, trustworthy commercial grading.',
        captionEn: 'Through 50°C+ summer heat, dust storms, and non-stop shifts, our team and our machines delivered. Thank you to Kuwait’s contractors and engineers for putting your trust in Dar Al Hay and Komatsu.\n\n🚜 Onward to the winter project season!',
        captionAr: 'رغم حرارة الصيف وشدة بيئة العمل، واصلت كوادرنا ومعداتنا العمل بأعلى كفاءة. شكراً لشركائنا ومهندسي الكويت على ثقتكم المستمرة في دار الحي وكوماتسو.\n\n🚜 مستعدون معاً لمشاريع موسم الشتاء القادم!',
        hashtags: '#DarAlHayTeam #KomatsuKuwait #KuwaitEngineers #SummerEndurance #HeavyMachinery #Partnership',
        ctaText: 'Partner with Dar Al Hay for your upcoming infrastructure contracts.',
        slides: [],
      },
    ],
  },

  '2026-09': {
    monthId: '2026-09',
    monthName: 'September 2026',
    themeTitle: 'Coastal Infrastructure & Marine Earthworks Megaprojects',
    strategicGoal: 'Showcase Komatsu heavy excavators (PC500LC) and articulated trucks (HM400) powering major Kuwait coastal reclamation projects with 98%+ uptime.',
    targetKpi: '30 Infrastructure Leads • 220,000 Social Impressions • 12 Formal Maintenance Contract Meetings',
    pillarDistribution: { pillar_authority: 15, pillar_engineering: 25, pillar_workshop: 15, pillar_projects: 30, pillar_leadgen: 15 },
    concepts: [
      // WEEK 1
      {
        id: 201, conceptNumber: 1, week: 'Week 1', day: 'Sunday', publishDate: '2026-09-06',
        title: 'Marine Earthworks – PC500LC Coastal Excavation in Sea City', pillar: 'pillar_projects', format: 'reel',
        platforms: ['instagram', 'linkedin', 'facebook'], goal: 'case_study', status: 'ready',
        targetAudience: 'Marine Contractors, Civil Infrastructure Engineers, Project Directors',
        tov: 'Cinematic, Prestigious, Power-Driven',
        summary: 'Dramatic 30-sec reel showcasing PC500LC excavators dredging coastal waterways and shaping marine canals in Kuwait.',
        hook: { spokenEn: 'When sea salt and heavy sand meet Japanese steel. Here is how Komatsu dominates coastal earthworks in Kuwait.', spokenAr: 'عندما تلتقي مياه البحر المالحة والرمال الثقيلة بالهندسة اليابانية.. كوماتسو في أضخم مشاريع الردم الساحلي.', visualHook: 'Low water-level camera angle with sea spray splashing as a massive PC500LC bucket emerges from the water brimming with wet sand.' },
        scenes: [
          { sceneNo: 1, time: '0:00 - 0:04', visual: 'Low water-level 4K shot: Sea spray splashing as giant PC500LC bucket rises from tidal canal filled with wet marine soil.', talentAction: 'Operator smoothly raises boom, water cascading off heavy steel teeth.', audioVoiceoverEn: 'When sea salt and heavy sand meet Japanese steel.', audioVoiceoverAr: 'عندما تلتقي مياه البحر المالحة بالهندسة اليابانية..', onScreenTextEn: 'COASTAL MEGA-PROJECTS | KOMATSU PC500LC', onScreenTextAr: 'مشاريع الردم الساحلي | كوماتسو PC500LC', sfxMusic: 'Deep sub-bass drop with water splash foley' },
          { sceneNo: 2, time: '0:04 - 0:11', visual: 'Drone bird-eye view panning along coastal waterway; synchronized Komatsu excavators loading HM400 articulated trucks.', talentAction: 'Excavators swinging in rhythm.', audioVoiceoverEn: 'Moving millions of cubic meters in harsh marine environments with non-stop reliability.', audioVoiceoverAr: 'نقل ملايين الأمتار المكعبة في أصعب البيئات البحرية بأعلى جاهزية تشغيلية.', onScreenTextEn: 'SYNCHRONIZED FLEET PRODUCTIVITY', onScreenTextAr: 'إنتاجية متزامنة للأساطيل الثقيلة', sfxMusic: 'Orchestral rhythm' },
        ],
        brollChecklist: ['Slow motion water dripping from bucket teeth', 'Drone bird-eye view of Sea City canals at sunrise'],
        postProductionNotes: 'Rich cyan marine grading with punchy Komatsu yellow.',
        captionEn: 'Marine salt, wet sand, and non-stop double shifts. The Komatsu PC500LC proves why it is Kuwait’s trusted choice for premier coastal reclamation projects.\n\nSupported by Dar Al Hay’s specialized marine preventive maintenance protocols.',
        captionAr: 'أملاح بحرية، رمال رطبة، وعمل متواصل على مدار الساعة. حفارات كوماتسو PC500LC تثبت تفوقها في أضخم مشاريع الردم الساحلي في الكويت.\n\nبدعم متكامل من برامج الصيانة الوقائية المتخصصة من دار الحي.',
        hashtags: '#MarineReclamation #PC500LC #KomatsuKuwait #SeaCity #CoastalProjects #DarAlHay #HeavyEarthmoving',
        ctaText: 'Partner with Dar Al Hay on your next infrastructure development.',
        slides: [],
      },
      {
        id: 202, conceptNumber: 2, week: 'Week 1', day: 'Tuesday', publishDate: '2026-09-08',
        title: 'KOWA Oil Analysis – Predicting Failures Before They Happen', pillar: 'pillar_engineering', format: 'carousel',
        platforms: ['linkedin', 'facebook', 'instagram'], goal: 'product_education', status: 'ready',
        targetAudience: 'Fleet Directors, Maintenance Supervisors, Asset Managers',
        tov: 'Scientific, Data-Driven, Authoritative B2B',
        summary: '5-slide educational breakdown of Komatsu Oil & Wear Analysis (KOWA) and how spectral analysis saves tens of thousands in unexpected breakdowns.',
        hook: { spokenEn: 'How a 50ml oil sample can save your fleet 15,000 KD in unexpected engine failure.', spokenAr: 'كيف يمكن لعينة زيت بحجم 50 مل أن توفر على شركتك أكثر من 15,000 دينار في صيانة المحركات؟', visualHook: 'High-tech lab spectrometer analyzing a glowing oil vial with wear metal particle readouts (Fe, Cu, Si).' },
        scenes: [], brollChecklist: ['Engineer drawing oil sample using vacuum extraction pump into sterile bottle', 'Lab spectrometer machine screen showing ppm wear metal graphs'],
        postProductionNotes: '1080x1350 vertical slides with laboratory aesthetic.',
        captionEn: 'Oil is the lifeblood of your heavy machinery. Komatsu Oil & Wear Analysis (KOWA) detects microscopic metal wear particles before catastrophic component failure occurs.\n\nSwipe through to see how proactive laboratory diagnostics protect your fleet ROI.',
        captionAr: 'الزيت هو شريان الحياة لمعدتك الثقيلة. برنامج فحص الزيوت المعتمد KOWA يكشف أدق جزيئات التآكل المعدني قبل وقوع الأعطال المفاجئة في المحركات والمضخات.\n\nاسحب الشاشة للتعرف على دور التحليل المخبري.',
        hashtags: '#KOWA #OilAnalysis #PredictiveMaintenance #KomatsuService #FleetHealth #DarAlHay #TCO',
        ctaText: 'Swipe through -> Request KOWA sampling kits for your fleet today.',
        slides: [
          { slideNo: 1, title: 'What Is KOWA Analysis?', body: 'Komatsu Oil & Wear Analysis uses spectral laboratory diagnostics to measure wear metals, soot, and fluid contamination in parts per million (PPM).' },
          { slideNo: 2, title: 'Early Warning Detection', body: 'Detects bearing wear (Copper/Lead), piston ring erosion (Iron/Chromium), and air filter bypass (Silicon/Sand) hundreds of hours before failure.' },
          { slideNo: 3, title: 'Prevent Catastrophic Overhauls', body: 'A 20 KD oil sample test prevents a 15,000 KD engine seizure by pinpointing faulty injectors or leaking coolant seals early.' },
          { slideNo: 4, title: 'Certified Trend Reporting', body: 'Every sample is logged in your machine’s digital health history, providing clear trend graphs and certified maintenance pedigree.' },
          { slideNo: 5, title: 'Included in Dar Al Hay EQP Agreements', body: 'Our certified engineers draw regular samples during scheduled maintenance intervals across Kuwait.' },
        ],
      },
      {
        id: 203, conceptNumber: 3, week: 'Week 1', day: 'Thursday', publishDate: '2026-09-10',
        title: 'Komatsu HM400 Articulated Truck – Conquering Soft Sand Hauling', pillar: 'pillar_engineering', format: 'photography',
        platforms: ['instagram', 'linkedin', 'facebook'], goal: 'brand_awareness', status: 'ready',
        targetAudience: 'Civil Contractors, Haulage Fleet Managers',
        tov: 'Bold, Powerful, High Aesthetic',
        summary: 'Hero photography of Komatsu HM400-5 articulated dump truck powering through soft tidal sand with 40-ton payload.',
        hook: { spokenEn: '40 tons of payload through soft Kuwait mud with KTCS traction control.', spokenAr: 'حمل 40 طناً عبر أضعف الأراضي الطينية بفضل نظام التحكم بالجر الذكي KTCS.', visualHook: 'High-speed action shot of 6x6 articulation flexing over sand ridge.' },
        scenes: [], brollChecklist: ['Low-angle shot of 6-wheel independent suspension flexing'],
        postProductionNotes: 'Sharpen metallic textures and ocean water spray.',
        captionEn: 'Soft sand and tidal mud stop rigid dump trucks in their tracks. The Komatsu HM400-5 articulated hauler features automatic traction control (KTCS) delivering unstoppable power across Kuwait coastal sites.\n\n📍 Sabah Al-Ahmad Sea City.',
        captionAr: 'الرمال الناعمة والبيئة الطينية توقف الشاحنات العادية، لكن شاحنة كوماتسو المفصلية HM400 تواصل التقدم بحمولة 40 طناً ونظام دفع سداسي ذكي.\n\n📍 مدينة صباح الأحمد البحرية.',
        hashtags: '#HM400 #ArticulatedDumpTruck #KomatsuKuwait #SeaCity #HeavyHauling #DarAlHay',
        ctaText: 'Contact our sales department for hauler fleet specifications.',
        slides: [],
      },

      // WEEK 2
      {
        id: 204, conceptNumber: 4, week: 'Week 2', day: 'Sunday', publishDate: '2026-09-13',
        title: 'Marine Anti-Corrosion Protection – Komatsu Factory Engineering', pillar: 'pillar_engineering', format: 'carousel',
        platforms: ['linkedin', 'facebook', 'instagram'], goal: 'product_education', status: 'idea',
        targetAudience: 'Marine Contractors, Maintenance Engineers, Fleet Owners',
        tov: 'Technical, Educational, Factual',
        summary: 'How Komatsu engineers sealed track pins, chrome-plated hydraulic rods, and epoxy-coated wiring harnesses to survive coastal salt air.',
        hook: { spokenEn: 'Why coastal salt air destroys generic excavators — and how Komatsu seals against rust.', spokenAr: 'كيف تدمر أملاح البحر الآليات العادية.. وأسرار العزل الياباني ضد الصدأ في كوماتسو.', visualHook: 'Cutaway graphic of hermetically sealed track pin showing internal synthetic lubricant seal.' },
        scenes: [], brollChecklist: ['Macro shot of chrome hydraulic rod', 'Sealed electrical connectors in engine bay'],
        postProductionNotes: 'Technical infographic layout.',
        captionEn: 'Operating heavy machinery within 500 meters of the sea creates intense galvanic corrosion. Here is how Komatsu factory anti-corrosion engineering protects your machine’s structural integrity.\n\nSwipe through for the engineering breakdown.',
        captionAr: 'العمل قرب مياه البحر يضاعف معدلات الصدأ والتآكل المعدني. إليك كيف صممت كوماتسو منظومة عزل متكاملة تحمي الهيكل والهيدروليك من الأملاح.\n\nاسحب الشاشة للتعرف على التفاصيل.',
        hashtags: '#AntiCorrosion #MarineEngineering #KomatsuExcavators #HeavyMachinery #KuwaitInfrastructure',
        ctaText: 'Order marine-spec Komatsu machinery through Dar Al Hay.',
        slides: [
          { slideNo: 1, title: 'Hermetically Sealed Track Pins', body: 'Polyurethane dust seals retain factory grease and prevent salt slurry from entering link bushings.' },
          { slideNo: 2, title: 'Heavy Hard-Chrome Plating', body: 'Cylinder rods feature double hard-chrome plating resisting salt pitting and seal degradation.' },
          { slideNo: 3, title: 'DT-Series Waterproof Connectors', body: 'All electrical wiring harnesses use sealed automotive DT connectors preventing salt corrosion shorts.' },
          { slideNo: 4, title: 'High-Zinc Marine Primer Coating', body: 'Chassis panels undergo cathodic electrodeposition priming before topcoat application.' },
          { slideNo: 5, title: 'Dar Al Hay Marine Wash Protocols', body: 'We provide specialized high-pressure washdown and anti-salt protective sprays.' },
        ],
      },
      {
        id: 205, conceptNumber: 5, week: 'Week 2', day: 'Tuesday', publishDate: '2026-09-15',
        title: 'Synchronized Earthmoving – PC500 & HM400 Cycle Time Optimization', pillar: 'pillar_projects', format: 'reel',
        platforms: ['instagram', 'linkedin', 'facebook'], goal: 'product_education', status: 'idea',
        targetAudience: 'Civil Contractors, Earthmoving Project Managers',
        tov: 'Dynamic, Time-Studies, Productive',
        summary: 'Side-by-side timer reel showing how a PC500LC loads an HM400 articulated truck in exactly 4 passes (110 seconds).',
        hook: { spokenEn: 'Watch a 40-ton truck get loaded in under 2 minutes with zero wasted movement.', spokenAr: 'شاهد كيف يتم تحميل شاحنة بحمولة 40 طناً في أقل من دقيقتين بدقة هندسية مذهلة.', visualHook: 'Fast split screen: Digital stopwatch counting seconds next to rapid excavator swings.' },
        scenes: [], brollChecklist: ['Top-down view of excavator bucket emptying into dump body', 'Digital stopwatch overlay graphic'],
        postProductionNotes: 'Dynamic speed ramps between bucket cycles.',
        captionEn: 'Cycle time is profit. Watch our customer’s Komatsu PC500LC excavator fill an HM400 articulated hauler in just 4 smooth passes — clocking 110 seconds flat.\n\n🚜 Speed, hydraulic precision, and maximum payload.',
        captionAr: 'سرعة دورات العمل تعني أرباحاً أعلى. شاهد حفارة كوماتسو PC500LC وهي تملأ شاحنة HM400 بأربع حركات فقط خلال 110 ثوانٍ.\n\n🚜 دقة هيدروليكية وإنتاجية قصوى.',
        hashtags: '#CycleTime #PC500LC #HM400 #EarthmovingEfficiency #KomatsuKuwait #DarAlHay',
        ctaText: 'Calculate your fleet productivity with our equipment specialists.',
        slides: [],
      },
      {
        id: 206, conceptNumber: 6, week: 'Week 2', day: 'Thursday', publishDate: '2026-09-17',
        title: 'Meet Our Master Hydraulic Technician in Shuwaikh', pillar: 'pillar_workshop', format: 'photography',
        platforms: ['linkedin', 'instagram', 'facebook'], goal: 'trust_humanize', status: 'idea',
        targetAudience: 'General Industry, Engineers, Fleet Owners',
        tov: 'Warm, Human, Expert-Driven',
        summary: 'Portrait of Lead Hydraulic Specialist Eng. Faisal / Abdelrahman inspecting a main control valve assembly in Shuwaikh workshop.',
        hook: { spokenEn: '15 years of Komatsu certified hydraulic mastery in Kuwait.', spokenAr: '15 عاماً من الخبرة الهندسية المعتمدة في أنظمة كوماتسو الهيدروليكية في الكويت.', visualHook: 'Crisp environmental portrait of engineer in clean uniform holding calibrated micrometer.' },
        scenes: [], brollChecklist: ['Portrait with soft background workshop lights', 'Macro shot of main control valve spool'],
        postProductionNotes: 'Warm skin tones, sharp industrial details.',
        captionEn: 'Behind every reliable machine in Kuwait stands our team of certified master technicians. Meet Eng. Faisal, specializing in main hydraulic control valves and high-pressure pump rebuilds at Dar Al Hay Shuwaikh.\n\n👨‍🔧 Certified expertise you can trust.',
        captionAr: 'خلف كل معدة تعمل بكفاءة في الكويت يقف فريق هندسي معتمد بأعلى المعايير. نعتز بكوادرنا الهندسية المتخصصة في صيانة وتجديد الأنظمة الهيدروليكية المعقدة في مركز الشويخ.\n\n👨‍🔧 خبرة دار الحي الهندسية في خدمتك.',
        hashtags: '#KuwaitEngineers #KomatsuTechnicians #DarAlHayTeam #HydraulicExpertise #ShuwaikhWorkshop',
        ctaText: 'Book your machine for a certified hydraulic diagnostic check.',
        slides: [],
      },

      // WEEK 3
      {
        id: 207, conceptNumber: 7, week: 'Week 3', day: 'Sunday', publishDate: '2026-09-20',
        title: 'Fuel Economy Shootout – Komatsu Hydraulic Regeneration System', pillar: 'pillar_engineering', format: 'carousel',
        platforms: ['linkedin', 'facebook', 'instagram'], goal: 'product_education', status: 'idea',
        targetAudience: 'Contracting CFOs, Fleet Directors, Procurement Managers',
        tov: 'Analytical, Financial, Data-Rich',
        summary: 'Explaining how Komatsu’s hydraulic quick-return circuit recovers boom-down energy to save up to 15% diesel per operating hour.',
        hook: { spokenEn: 'How hydraulic energy recycling saves contractors 4,500 KD per year in diesel fuel.', spokenAr: 'كيف توفر تقنية استرجاع الطاقة الهيدروليكية أكثر من 4,500 دينار سنوياً في استهلاك الديزل؟', visualHook: 'Animated diagram showing hydraulic oil flow during boom lower recycling pressure into arm cylinder.' },
        scenes: [], brollChecklist: ['Digital fuel meter screen on excavator dashboard', 'Hydraulic valve block close-up'],
        postProductionNotes: 'Clean infographic diagrams with diesel saving calculations.',
        captionEn: 'Diesel fuel is your largest ongoing variable operating expense. Komatsu excavators feature hydraulic quick-return valves that recycle fluid pressure when lowering the boom — reducing engine load and cutting fuel consumption by up to 15%.\n\nSwipe through for the engineering data.',
        captionAr: 'استهلاك الوقود هو التكلفة التشغيلية الأكبر في أي مشروع. حفارات كوماتسو مزودة بنظام ذكي لتدوير الزيت الهيدروليكي عند خفض الذراع، مما يقلل الحمل على المحرك ويوفر حتى 15% من الديزل.\n\nاسحب الشاشة للتعرف على الأرقام.',
        hashtags: '#FuelEfficiency #HydraulicEngineering #TCO #KomatsuSavings #DarAlHay #FleetEconomics',
        ctaText: 'Request a KOMTRAX fuel economy demo report for your fleet.',
        slides: [
          { slideNo: 1, title: 'The Gravity-Assisted Circuit', body: 'When lowering the heavy boom, gravity forces hydraulic oil out of the cylinder base.' },
          { slideNo: 2, title: 'Internal Pressure Recycling', body: 'Rather than dumping oil back to tank, Komatsu valves redirect pressure directly to the arm cylinder.' },
          { slideNo: 3, title: 'Reduced Engine Load', body: 'The main hydraulic pump requires up to 25% less engine horsepower during combined swing-and-lower cycles.' },
          { slideNo: 4, title: 'Real Kuwait Fleet Data', body: 'Average fuel consumption measured across South Kuwait sites: 18.5 L/h on PC350LC vs 22.0 L/h on competitors.' },
          { slideNo: 5, title: 'Calculate Your Annual Savings', body: 'Contact Dar Al Hay to model your fleet fuel savings over 2,000 annual operating hours.' },
        ],
      },
      {
        id: 208, conceptNumber: 8, week: 'Week 3', day: 'Tuesday', publishDate: '2026-09-22',
        title: 'Heavy Breaker Operations – PC400 Rock Breaking at Subiya Causeway Link', pillar: 'pillar_projects', format: 'reel',
        platforms: ['instagram', 'linkedin', 'facebook'], goal: 'case_study', status: 'idea',
        targetAudience: 'Demolition Contractors, Quarry Operators, Infrastructure Firms',
        tov: 'High-Impact, Heavy Industrial, Sonic',
        summary: 'Massive hydraulic breaker chisel shattering hard limestone rock in Subiya with high-speed 120fps camera slow motion.',
        hook: { spokenEn: 'When Kuwait hardpack rock meets 10,000 joules of hydraulic impact force.', spokenAr: 'عندما تلتقي صخور الكويت الصلبة بقوة تكسير هيدروليكية تصل إلى 10,000 جول.', visualHook: 'Ultra-slow motion shot of breaker chisel hitting rock with dust shockwave dispersing outward.' },
        scenes: [], brollChecklist: ['120fps slow-motion breaker chisel impact', 'Rock fracturing in slow motion'],
        postProductionNotes: 'Heavy percussive audio with synchronized chisel impacts.',
        captionEn: 'Hard limestone and deep trench excavation require relentless impact energy. The Komatsu PC400 equipped with heavy hydraulic hammer powers through Kuwait rock with reinforced boom structures.\n\n📍 Subiya Link Projects.',
        captionAr: 'حفر الصخور والخنادق العميقة يحتاج قوة تكسير متواصلة وهيكل ذراع معزز. حفارة كوماتسو PC400 مع المطرقة الهيدروليكية الثقيلة تكسر أصلب طبقات الصخور في مشاريع الصبية.\n\n📍 مشاريع ربط الصبية.',
        hashtags: '#HydraulicBreaker #PC400 #RockBreaking #KuwaitDemolition #KomatsuKuwait #DarAlHay',
        ctaText: 'Inquire about genuine Komatsu hydraulic breaker attachments.',
        slides: [],
      },
      {
        id: 209, conceptNumber: 9, week: 'Week 3', day: 'Thursday', publishDate: '2026-09-24',
        title: 'Parts Warehouse Tour – 15,000 Lines Available in Shuwaikh', pillar: 'pillar_leadgen', format: 'carousel',
        platforms: ['linkedin', 'facebook', 'instagram'], goal: 'lead_generation', status: 'idea',
        targetAudience: 'Procurement Managers, Workshop Owners, Spare Parts Dealers',
        tov: 'Organized, Impressive Scale, Reassuring',
        summary: 'Photo tour of Dar Al Hay’s climate-controlled central parts warehouse in Shuwaikh showing hydraulic pumps, filters, track links, and seals.',
        hook: { spokenEn: 'Inside Kuwait’s largest genuine Komatsu spare parts warehouse with 98% off-the-shelf availability.', spokenAr: 'جولة داخل أضخم مستودع لقطع غيار كوماتسو الأصلية في الكويت بتوافر فوري يتجاوز 98%.', visualHook: 'Wide symmetrical shot looking down warehouse aisle filled with stacked yellow Komatsu boxes.' },
        scenes: [], brollChecklist: ['Forklift lifting pallet of track rollers', 'Barcode scanner scanning genuine box label'],
        postProductionNotes: 'Clean, brightly lit warehouse photography.',
        captionEn: 'When your machine needs a part, waiting weeks for shipping is not an option. Dar Al Hay maintains Kuwait’s largest climate-controlled genuine Komatsu parts facility in Shuwaikh.\n\n📦 Same-day site delivery across Kuwait.',
        captionAr: 'عندما تحتاج معدتك إلى قطعة غيار، الانتظار لأسابيع ليس خياراً. توفر شركة دار الحي أكبر مستودع مكيف لقطع غيار كوماتسو الأصلية بالشويخ.\n\n📦 توصيل مباشر إلى موقع عملك في نفس اليوم.',
        hashtags: '#SpareParts #KomatsuParts #DarAlHayWarehouse #Shuwaikh #GenuineParts #HeavyMachinery',
        ctaText: 'WhatsApp our Parts Desk directly with your part number for instant pricing.',
        slides: [
          { slideNo: 1, title: '15,000+ Active Part Numbers', body: 'Filters, seals, hydraulic pumps, turbochargers, track chains, bucket teeth, and electronic sensors in stock.' },
          { slideNo: 2, title: 'Barcode Inventory Tracking', body: 'Automated warehouse management ensures rapid order picking and zero shipping errors.' },
          { slideNo: 3, title: 'Same-Day Dispatch Across Kuwait', body: 'Dedicated parts delivery vans dispatched directly to your worksite in Mutlaa, Wafra, or Subiya.' },
          { slideNo: 4, title: 'Direct Factory Sourcing', body: '100% genuine Komatsu Japan components with full manufacturer warranty protection.' },
          { slideNo: 5, title: 'Contact Our Parts Counter Today', body: 'Call or WhatsApp our parts specialists at +965 2200 XXXX for immediate quotes.' },
        ],
      },

      // WEEK 4
      {
        id: 210, conceptNumber: 10, week: 'Week 4', day: 'Sunday', publishDate: '2026-09-27',
        title: 'Komatsu Cab Ergonomics – Operator Comfort on 12-Hour Shifts', pillar: 'pillar_engineering', format: 'reel',
        platforms: ['instagram', 'linkedin', 'facebook'], goal: 'product_education', status: 'idea',
        targetAudience: 'Machinery Operators, Site Supervisors, Contractors',
        tov: 'Human, Comfort-Driven, Modern',
        summary: 'Step inside the whisper-quiet SpaceCab: air suspension seat, high-capacity dual AC climate control, and low-vibration viscous cab mounts.',
        hook: { spokenEn: 'How Komatsu keeps heavy equipment operators cool and alert through 12-hour Kuwait shifts.', spokenAr: 'كيف تضمن كوماتسو راحة وإنتاجية السائقين في نوبات العمل الطويلة في أجواء الكويت الحارة؟', visualHook: 'Door opens to show pristine air-conditioned cabin with digital dash and ergonomic joystick armrests.' },
        scenes: [], brollChecklist: ['Operator adjusting climate control knob showing 20°C', 'POV looking out panoramic curved windshield'],
        postProductionNotes: 'Smooth gimbal motion inside cabin.',
        captionEn: 'An alert, comfortable operator is a productive operator. The Komatsu SpaceCab is pressurized to seal out desert dust, equipped with dual high-output AC units and air-suspension seating.\n\n🚜 Experience operator-first design with Dar Al Hay.',
        captionAr: 'راحة السائق تنعكس مباشرة على إنتاجية وسلامة موقع العمل. كابينة كوماتسو المعزولة والمضغوطة تمنع دخول الغبار وتوفر تكييفاً فائق القوة ومقاعد هيدروليكية مريحة.\n\n🚜 تجربة قيادة استثنائية مع دار الحي.',
        hashtags: '#SpaceCab #OperatorComfort #KomatsuDesign #HeavyMachinery #Ergonomics #DarAlHay',
        ctaText: 'Visit our Shuwaikh showroom to test-sit in the new Komatsu SpaceCab.',
        slides: [],
      },
      {
        id: 211, conceptNumber: 11, week: 'Week 4', day: 'Tuesday', publishDate: '2026-09-29',
        title: 'Customer Spotlight – Al-Ghanim Earthmoving Fleet Testimonial', pillar: 'pillar_projects', format: 'photography',
        platforms: ['linkedin', 'facebook', 'instagram'], goal: 'case_study', status: 'idea',
        targetAudience: 'Civil Contractors, Business Leaders, Fleet Directors',
        tov: 'Prestigious, Social Proof, Partner-Led',
        summary: 'Executive quote card featuring a leading Kuwait infrastructure contractor sharing why they standardized on 25+ Komatsu machines with Dar Al Hay.',
        hook: { spokenEn: '"In 4 years on coastal megaprojects, our Komatsu excavators averaged 99.2% uptime with Dar Al Hay."', spokenAr: '"خلال 4 سنوات في مشاريع الردم الساحلي، حققت معدات كوماتسو جاهزية تشغيلية بلغت 99.2% بدعم دار الحي."', visualHook: 'Executive contractor standing beside PC500LC with clean project site backdrop.' },
        scenes: [], brollChecklist: ['Executive portrait on site', 'Lineup of contractor’s Komatsu machines'],
        postProductionNotes: 'High-contrast editorial portrait style.',
        captionEn: '"On high-stakes infrastructure deadlines, machine reliability and fast parts delivery are everything. Dar Al Hay has been an exceptional partner on our coastal contracts."\n\n— Project Director, Leading Kuwait Marine & Civil Contractor.\n\n🤝 Proud to power Kuwait’s premier builders.',
        captionAr: '"في المشاريع الكبرى ذات الجداول الزمنية الدقيقة، الاعتمادية وسرعة توفير قطع الغيار تصنع كل الفارق. دار الحي شريك استراتيجي في نجاح مشاريعنا."\n\n— مدير المشاريع بإحدى كبرى شركات المقاولات في الكويت.\n\n🤝 فخورون بدعم رواد البناء في الكويت.',
        hashtags: '#CustomerSuccess #KuwaitContractors #KomatsuKuwait #DarAlHay #ProjectMilestone #MarineEarthworks',
        ctaText: 'Read full contractor case studies on our website.',
        slides: [],
      },
      {
        id: 212, conceptNumber: 12, week: 'Week 4', day: 'Thursday', publishDate: '2026-09-30',
        title: 'October Overhaul Season Preview – Book Your Workshop Slot', pillar: 'pillar_workshop', format: 'cta_post',
        platforms: ['linkedin', 'facebook', 'instagram'], goal: 'lead_generation', status: 'idea',
        targetAudience: 'Fleet Owners, Plant Managers, Chief Mechanics',
        tov: 'Urgent, Exclusive, Maintenance Planning',
        summary: 'Announcement of Dar Al Hay’s annual October Engine & Hydraulic Overhaul Campaign with discounted diagnostic packages.',
        hook: { spokenEn: 'Prepare your fleet before the winter construction rush. Book your certified overhaul slot now.', spokenAr: 'جهّز أسطولك قبل ذروة مشاريع الشتاء.. احجز موعد الصيانة الشاملة لمحركات ومضخات معداتك الآن.', visualHook: 'Dyno test bench screen showing digital horsepower readout with overhaul banner overlay.' },
        scenes: [], brollChecklist: ['Technician fitting piston rings on engine block', 'Dyno testing control panel'],
        postProductionNotes: 'High-contrast promotional graphics with dates.',
        captionEn: 'Winter is peak construction season in Kuwait. Ensure your excavators, loaders, and bulldozers operate at 100% capacity by booking your certified engine and hydraulic overhaul in Shuwaikh this October.\n\n🔧 Comprehensive dyno testing & factory warranty included.\n\n📅 Limited workshop bay availability.',
        captionAr: 'فصل الشتاء هو ذروة موسم الإنشاءات في الكويت. اضمن عمل حفاراتك ومعداتك بكامل طاقتها بحجز صيانة وتجديد المحركات والهيدروليك في مركز الشويخ لشهر أكتوبر.\n\n🔧 فحص شامل على أجهزة الديناموميتر مع ضمان معتمد.\n\n📅 المواعيد محدودة في ورش الصيانة.',
        hashtags: '#OverhaulSeason #WorkshopBooking #EngineRebuild #KomatsuService #DarAlHay #Shuwaikh',
        ctaText: 'Click the link or WhatsApp us to reserve your fleet overhaul slot.',
        slides: [],
      },
    ],
  },

  '2026-10': {
    monthId: '2026-10',
    monthName: 'October 2026',
    themeTitle: 'The Overhaul Season: Shuwaikh Master Workshop & Certified Rebuilds',
    strategicGoal: 'Drive high-margin workshop rebuild contracts and promote genuine undercarriage/engine overhaul kits ahead of winter infrastructure peak.',
    targetKpi: '15 Overhaul Contracts Booked • 150,000 Reach • 40 Spare Parts Quotes Dispatched',
    pillarDistribution: { pillar_authority: 15, pillar_engineering: 20, pillar_workshop: 35, pillar_projects: 15, pillar_leadgen: 15 },
    concepts: [
      {
        id: 301, conceptNumber: 1, week: 'Week 1', day: 'Sunday', publishDate: '2026-10-04',
        title: 'Zero-Hour Master Rebuild – Inside the Central Engine Bay', pillar: 'pillar_workshop', format: 'reel',
        platforms: ['linkedin', 'instagram', 'facebook'], goal: 'trust_humanize', status: 'idea',
        targetAudience: 'Fleet Owners, Plant Managers, Chief Engineers',
        tov: 'High Craftsmanship, Precision Engineering, Industrial',
        summary: 'Macro cinematic walkthrough of a Komatsu SAA6D140E engine overhaul from bare crankcase to dyno test bench in Shuwaikh.',
        hook: { spokenEn: 'Watch a 10,000-hour Komatsu engine get rebuilt to Japanese factory zero-hour standards in Kuwait.', spokenAr: 'شاهد كيف نعيد محرك كوماتسو بعد 10,000 ساعة عمل إلى معايير المصنع الياباني في الكويت.', visualHook: 'Split-screen showing heavily carbonized piston next to brand new mirror-polished genuine Komatsu piston assembly.' },
        scenes: [], brollChecklist: ['Engine cylinder liner honing close-up', 'Digital torque wrench clicking on cylinder head bolts'],
        postProductionNotes: 'Sharp industrial sound design with rhythmic ratchet clicks.',
        captionEn: 'Why replace an entire machine when you can restore its heart to factory zero-hour specifications?\n\nStep inside Dar Al Hay’s central Shuwaikh overhaul facility. 100% genuine parts, certified master technicians, and comprehensive post-rebuild warranty.',
        captionAr: 'لماذا تستبدل المعدة بالكامل بينما يمكنك تجديد محركها إلى كفاءة الصفر ساعة؟\n\nنظرة من داخل مركز الصيانة المتطور لدار الحي بالشويخ. قطع أصلية 100%، فنيون معتمدون، وضمان شامل بعد التجديد.',
        hashtags: '#EngineRebuild #KomatsuWorkshop #Shuwaikh #ZeroHour #HeavyMachineryOverhaul #DarAlHay',
        ctaText: 'Book your fleet engine overhaul before the winter project rush.',
        slides: [],
      },
    ],
  },
};
