export const CONTENT_PILLARS = [
  { id: 'pillar_authority', label: 'Brand Authority & Japanese Heritage', color: 'bg-sky-100 text-sky-900 border-sky-300', tagColor: 'sky', targetPct: 20, desc: 'Highlighting Komatsu Japanese precision, Dar Al Hay partnership, and Kuwait infrastructure leadership.' },
  { id: 'pillar_engineering', label: 'Technical & Product Education', color: 'bg-indigo-100 text-indigo-900 border-indigo-300', tagColor: 'indigo', targetPct: 25, desc: 'Deep-dive machine walkthroughs, specs, KOMTRAX telematics, and heavy-duty desert cooling systems.' },
  { id: 'pillar_workshop', label: 'Workshop BTS & Engineering Craft', color: 'bg-amber-100 text-amber-900 border-amber-300', tagColor: 'amber', targetPct: 20, desc: 'Certified engineers, engine overhauls, diagnostic testing, and parts warehouse inventory in Shuwaikh.' },
  { id: 'pillar_projects', label: 'Kuwait Jobsites & Case Studies', color: 'bg-emerald-100 text-emerald-900 border-emerald-300', tagColor: 'emerald', targetPct: 20, desc: 'Real-world machinery performance at Sabah Al-Ahmad Sea City, desert earthworks, and highway projects.' },
  { id: 'pillar_leadgen', label: 'After-Sales & Lead Generation', color: 'bg-rose-100 text-rose-900 border-rose-300', tagColor: 'rose', targetPct: 15, desc: 'Emergency field service, genuine parts direct delivery, EQP maintenance contracts, and machine sales.' },
];

export const FORMAT_TYPES = [
  { id: 'reel', label: 'Reels / Motion Video', icon: '🎬', tag: 'Motion / BTS / Walkaround', color: 'bg-purple-100 text-purple-900 border-purple-300' },
  { id: 'carousel', label: 'Carousels (Multi-Slide)', icon: '📑', tag: 'Education / Story / Specs', color: 'bg-indigo-100 text-indigo-900 border-indigo-300' },
  { id: 'photography', label: 'Hero Photography', icon: '📸', tag: 'Environmental / Machinery / People', color: 'bg-emerald-100 text-emerald-900 border-emerald-300' },
  { id: 'designed_post', label: 'Infographic / Graphic Post', icon: '🎨', tag: 'Facts / Data / Telemetry', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { id: 'cta_post', label: 'Conversion / CTA Post', icon: '🎯', tag: 'Lead Gen / Sales / Service Call', color: 'bg-rose-100 text-rose-900 border-rose-300' },
];

export const GOAL_TYPES = [
  { id: 'brand_awareness', label: 'Brand Awareness & Positioning', color: 'bg-sky-50 text-sky-800 border-sky-200' },
  { id: 'product_education', label: 'Product Education & Specs', color: 'bg-indigo-50 text-indigo-800 border-indigo-200' },
  { id: 'lead_generation', label: 'Lead Generation & Inquiries', color: 'bg-rose-50 text-rose-800 border-rose-200' },
  { id: 'trust_humanize', label: 'Trust & Humanizing the Brand', color: 'bg-emerald-50 text-emerald-800 border-emerald-200' },
  { id: 'case_study', label: 'Social Proof & Project Validation', color: 'bg-amber-50 text-amber-800 border-amber-200' },
  { id: 'expertise', label: 'Engineering Expertise & Maintenance', color: 'bg-purple-50 text-purple-800 border-purple-200' },
];

export const PIPELINE_STAGES = [
  { id: 'idea', label: '1. Strategy & Concept', icon: '💡', badgeTone: 'neutral' },
  { id: 'scripted', label: '2. Scripted & Briefed', icon: '📝', badgeTone: 'info' },
  { id: 'production', label: '3. Shooting / Designing', icon: '🎬', badgeTone: 'warning' },
  { id: 'review', label: '4. Quality & TOV Review', icon: '👀', badgeTone: 'yellow' },
  { id: 'ready', label: '5. Scheduled & Ready', icon: '🚀', badgeTone: 'active' },
  { id: 'published', label: '6. Published & Live', icon: '✅', badgeTone: 'ready' },
];

export const MEDIA_PLATFORMS = [
  { id: 'instagram', label: 'Instagram', icon: '📸', color: 'from-pink-500 to-purple-600', badgeTone: 'active', handle: '@daralhay_komatsu' },
  { id: 'linkedin', label: 'LinkedIn', icon: '💼', color: 'from-blue-600 to-blue-800', badgeTone: 'info', handle: 'Dar Al Hay Commercial Co.' },
  { id: 'facebook', label: 'Facebook', icon: '👥', color: 'from-blue-500 to-indigo-600', badgeTone: 'ready', handle: 'Dar Al Hay - Komatsu Kuwait' },
];

export const TOV_GUIDELINES = {
  overall: {
    title: 'Dar Al Hay Brand Voice & Persona',
    summary: 'Authoritative, Precision-Driven, Industrial Strength, and Rooted in Kuwait Progress.',
    traits: [
      { name: 'Japanese Precision & Heritage', desc: 'Emphasize Komatsu factory standards, strict quality controls, and world-leading hydraulic engineering.' },
      { name: 'Kuwait Desert Toughness', desc: 'Acknowledge the harsh 50°C+ climate, fine desert sand, and heavy rock conditions in Kuwait and how our machines conquer them.' },
      { name: 'Unwavering Engineering Authority', desc: 'Talk like certified master engineers and fleet directors — avoid generic sales fluff, focus on uptime, SMR hours, fuel efficiency, and ROI.' },
      { name: 'Customer Partnership', desc: 'Frame Dar Al Hay not just as an equipment seller, but as an indispensable operational partner on Kuwait megaprojects.' },
    ],
  },
  platforms: {
    linkedin: {
      platform: 'LinkedIn',
      tone: 'Authoritative B2B Engineering & Fleet Economics',
      target: 'C-Suite, Procurement Directors, Project Managers, Fleet Supervisors',
      guidelines: 'Focus on total cost of ownership (TCO), fuel economy data, KOMTRAX satellite telemetry, preventive maintenance contracts, and Kuwait project case studies. Use professional terminology and structured bullet points.',
    },
    instagram: {
      platform: 'Instagram',
      tone: 'Visual, High-Energy, Cinematic, & Behind-The-Scenes',
      target: 'Heavy Machinery Operators, Young Engineers, Contractors, Brand Fans',
      guidelines: 'Lead with strong 3-second visual hooks, close-up engine sounds, slow-motion hydraulic action, golden hour desert shots, and relatable maintenance tips.',
    },
    facebook: {
      platform: 'Facebook',
      tone: 'Community-Focused, Accessible, Practical & Bilingual (Arabic First)',
      target: 'Local Subcontractors, Workshop Owners, Equipment Operators, General Public',
      guidelines: 'Clear value propositions, direct WhatsApp/phone contact CTAs, workshop open days, fast spare parts availability, and transparent service offerings in both Arabic and English.',
    },
  },
  doAndDont: [
    { do: 'Use exact technical terms (e.g., PC350LC-8M0, SAA6D114E-3 engine, KOMTRAX, KTCS traction).', dont: 'Use vague generic terms like "our big digger" or "super strong machine".' },
    { do: 'Provide bilingual copy (Arabic + English) with natural professional Gulf/Kuwait phrasing.', dont: 'Rely on automated literal translations that sound robotic or awkward.' },
    { do: 'Highlight certified engineers, PPE safety helmets, clean Shuwaikh workshop, and genuine parts.', dont: 'Show uncertified field repairs without safety gear or messy workshop environments.' },
    { do: 'Include clear Call To Actions with contact numbers, WhatsApp links, and showroom location.', dont: 'Leave posts with no next step for interested fleet managers.' },
  ],
};

export const PRE_PRODUCTION_CHECKLIST = [
  { id: 'permits', category: 'Approvals & Access', task: 'Obtain worksite entry and filming permits (Kuwait Municipality / PAHW / KOC / Client).' },
  { id: 'safety', category: 'Safety & PPE', task: 'Ensure all filming crew and on-screen staff wear Komatsu safety vests, hard hats, and steel-toe boots.' },
  { id: 'cleaning', category: 'Asset Preparation', task: 'Pressure wash machine body, bucket, and tracks; ensure Komatsu & Dar Al Hay branding stickers are clean and visible.' },
  { id: 'camera', category: 'Camera & Lighting', task: 'Pack 4K gimbal stabilizer, wide-angle lens (16-35mm), macro lens for parts, and circular polarizer filter for desert glare.' },
  { id: 'audio', category: 'Audio Gear', task: 'Test dual wireless lapel microphones with deadcat wind protection for clear voiceover in windy desert conditions.' },
  { id: 'talent', category: 'Talent Briefing', task: 'Rehearse spoken script in both Arabic and English with certified service engineer prior to rolling camera.' },
];

export const INITIAL_MONTHLY_CAMPAIGNS = {
  '2026-08': {
    monthId: '2026-08',
    monthName: 'August 2026',
    themeTitle: 'Extreme Desert Heat Endurance & 50°C+ Summer Resilience',
    strategicGoal: 'Position Komatsu cooling systems and Dar Al Hay preventive field care as the premier solution for zero summer downtime in Kuwait.',
    targetKpi: '25 Qualified Fleet Inquiries • 180,000 Video Views in Kuwait • 95% Positive B2B Engagement',
    pillarDistribution: { pillar_authority: 20, pillar_engineering: 30, pillar_workshop: 20, pillar_projects: 15, pillar_leadgen: 15 },
    concepts: [
      {
        id: 101,
        conceptNumber: 1,
        week: 'Week 1',
        day: 'Sunday',
        publishDate: '2026-08-02',
        title: 'Hero Machine – PC350LC-8M0 Cinematic Brand Intro',
        pillar: 'pillar_authority',
        format: 'reel',
        platforms: ['instagram', 'linkedin', 'facebook'],
        goal: 'brand_awareness',
        status: 'published',
        targetAudience: 'Contractors, Government Infrastructure Stakeholders, Fleet Owners',
        tov: 'Cinematic, High-Impact, Authoritative Industrial',
        summary: 'Cinematic 25-sec video intro: Kuwait desert landscape -> Dar Al Hay facility -> Komatsu machine lineup -> Workshop engine rebuild -> Parts warehouse -> Engineering team -> Logo lockup.',
        hook: {
          spokenEn: 'Built for the toughest desert terrain on earth. Meet Komatsu in Kuwait.',
          spokenAr: 'صُنعت لتقهر أصعب تضاريس الصحراء في العالم.. كوماتسو في الكويت.',
          visualHook: 'Rapid cinematic crash-zoom from drone altitude over South Kuwait desert directly into the heavy steel bucket of a Komatsu PC350LC digging through rock.',
        },
        scenes: [
          {
            sceneNo: 1,
            time: '0:00 - 0:03',
            visual: 'Drone wide establishing shot: Sunrise over Kuwait desert highway, transition to low-angle PC350LC track moving forward.',
            talentAction: 'Machine operator swings boom smoothly into frame, sun flare hits heavy hydraulic cylinder.',
            audioVoiceoverEn: 'Built for the toughest desert terrain on earth.',
            audioVoiceoverAr: 'صُنعت لتقهر أصعب تضاريس الصحراء في العالم..',
            onScreenTextEn: 'BUILT FOR KUWAIT | KOMATSU PC350LC-8M0',
            onScreenTextAr: 'صُنعت للكويت | كوماتسو PC350LC',
            sfxMusic: 'Cinematic low-bass sub drop into driving industrial beat; deep Komatsu engine roar.',
          },
          {
            sceneNo: 2,
            time: '0:03 - 0:08',
            visual: 'Fast match-cut to Dar Al Hay headquarters & modern Shuwaikh showroom exterior, then into wide fleet yard.',
            talentAction: 'Service Engineer in Komatsu uniform walking purposefully toward camera carrying digital diagnostic tablet.',
            audioVoiceoverEn: 'Backed by Dar Al Hay’s world-class engineering and certified local support.',
            audioVoiceoverAr: 'بدعم هندسي متكامل وخبرة معتمدة من دار الحي.',
            onScreenTextEn: 'OFFICIAL KOMATSU DISTRIBUTOR IN KUWAIT',
            onScreenTextAr: 'الموزع المعتمد لكوماتسو في الكويت',
            sfxMusic: 'Rhythmic percussive riser.',
          },
          {
            sceneNo: 3,
            time: '0:08 - 0:15',
            visual: 'Macro rapid-fire montage inside central workshop: Torque wrench clicking on cylinder head, glowing parts wash tank, digital hydraulic pressure gauge.',
            talentAction: 'Master technician tightening manifold with calibrated wrench; Sparks from welding in soft background.',
            audioVoiceoverEn: 'Overhaul expertise, 15,000+ genuine parts on shelf, and 24/7 mobile field response.',
            audioVoiceoverAr: 'مراكز صيانة متطورة، أكثر من 15,000 قطعة غيار أصلية جاهزة، وفرق دعم ميداني على مدار الساعة.',
            onScreenTextEn: 'GENUINE PARTS • CERTIFIED OVERHAULS • 24/7 FIELD CARE',
            onScreenTextAr: 'قطع أصلية • صيانة معتمدة • خدمة ميدانية 24/7',
            sfxMusic: 'Mechanical metallic ratchet clicks foley + deep synthesizer pulse.',
          },
          {
            sceneNo: 4,
            time: '0:15 - 0:22',
            visual: 'Return to worksite action: Massive 3-meter bucket cutting through desert hardpack, loading articulated dump truck with zero hesitation.',
            talentAction: 'Operator smoothly cycling hydraulic controls inside air-conditioned pressurized cabin.',
            audioVoiceoverEn: 'Powering Kuwait’s national megaprojects with uncompromising Japanese reliability.',
            audioVoiceoverAr: 'نشيد مشاريع الكويت الكبرى بأعلى معايير الاعتمادية اليابانية.',
            onScreenTextEn: 'POWERING KUWAIT’S INFRASTRUCTURE',
            onScreenTextAr: 'نبني مستقبل مشاريع الكويت',
            sfxMusic: 'Epic cinematic orchestral crescendo.',
          },
          {
            sceneNo: 5,
            time: '0:22 - 0:26',
            visual: 'Clean navy slate screen with Komatsu & Dar Al Hay gold logos lockup, showroom address and contact hotline.',
            talentAction: 'Logo animation with subtle metallic sheen reflection.',
            audioVoiceoverEn: 'Dar Al Hay. Your heavy machinery partner in Kuwait.',
            audioVoiceoverAr: 'دار الحي.. شريكك الموثوق للمعدات الثقيلة في الكويت.',
            onScreenTextEn: 'Dar Al Hay Commercial Co. | Shuwaikh | +965 2200 XXXX',
            onScreenTextAr: 'شركة دار الحي التجارية | الشويخ | 2200XXXX 965+',
            sfxMusic: 'Final clean brand audio logo chord.',
          },
        ],
        brollChecklist: [
          '4K 60fps slow-motion drone flyby over desert excavator at sunrise',
          'Macro close-up of hydraulic hoses flexing under 350 bar pressure',
          'Shuwaikh warehouse aisle showing organized barcoded genuine Komatsu yellow boxes',
          'Technician using calibrated digital torque wrench on diesel engine block',
          'Operator cabin POV looking out through clean windshield at bucket digging',
        ],
        postProductionNotes: 'Grade with warm desert golden hour contrast while preserving true Komatsu yellow (#FFD100) and Dar Al Hay deep navy.',
        captionEn: 'From high-speed national highway networks to deep marine earthworks, Komatsu heavy machinery powers Kuwait’s progress.\n\nBacked by Dar Al Hay’s factory-trained engineers, extensive genuine parts inventory in Shuwaikh, and 24/7 mobile field service.\n\n🚜 Explore our heavy excavator and earthmoving fleet today.\n\n📍 Visit our Shuwaikh central showroom or contact our heavy equipment specialists.',
        captionAr: 'من شبكات الطرق السريعة ومشاريع البنية التحتية الكبرى إلى أضخم أعمال الردم والإنشاءات، تواصل معدات كوماتسو ريادتها في الكويت.\n\nمدعومة بخبرات دار الحي الهندسية المعتمدة، ومخزون متكامل من قطع الغيار الأصلية في الشويخ، وفرق صيانة ميدانية متنقلة 24/7.\n\n🚜 استكشف أسطول الحفارات والمعدات الثقيلة المتوفرة الآن.\n\n📍 تفضل بزيارة معرضنا الرئيسي بالشويخ أو تواصل مع مستشاري المعدات الثقيلة.',
        hashtags: '#Komatsu #DarAlHay #KuwaitConstruction #HeavyMachinery #PC350LC #Excavator #KuwaitEngineers #KuwaitMegaprojects #Earthmoving #Shuwaikh',
        ctaText: 'Visit our Shuwaikh showroom or call our heavy equipment sales desk for fleet quotations.',
        slides: [],
      },
      {
        id: 102,
        conceptNumber: 2,
        week: 'Week 1',
        day: 'Tuesday',
        publishDate: '2026-08-04',
        title: 'Service Tips – Dar Al Hay Complete Partnership Ecosystem',
        pillar: 'pillar_authority',
        format: 'carousel',
        platforms: ['linkedin', 'instagram', 'facebook'],
        goal: 'brand_awareness',
        status: 'published',
        targetAudience: 'Fleet Managers, Maintenance Directors, Construction Contractors',
        tov: 'Corporate, Educational, Consultative & Reassuring',
        summary: '5-slide carousel explaining the relationship between Dar Al Hay & Komatsu, services provided, industries served, and contact CTA.',
        hook: {
          spokenEn: 'More than just heavy machines: How Dar Al Hay protects your fleet lifecycle in Kuwait.',
          spokenAr: 'أكثر من مجرد توريد آليات.. كيف تحمي دار الحي استثمارك وأسطولك في الكويت.',
          visualHook: 'High-contrast graphic showing a Komatsu excavator split into 5 operational support sectors.',
        },
        scenes: [],
        brollChecklist: [
          'Studio photography of Komatsu equipment manuals and diagnostic tools',
          'Clean architectural photo of Dar Al Hay Shuwaikh service complex',
          'Field service truck dispatched onto dusty Kuwait jobsite',
        ],
        postProductionNotes: '1080x1350 vertical carousel format for Instagram and PDF document swipe for LinkedIn.',
        captionEn: 'Purchasing heavy machinery is an investment. Ensuring that machine delivers maximum uptime over 10,000+ operating hours is where Dar Al Hay makes the difference.\n\nHere is how our complete engineering ecosystem supports contractors and fleet managers across Kuwait.\n\nSwipe through -> Save this post for your fleet management handbook.',
        captionAr: 'شراء المعدات الثقيلة استثمار استراتيجي. وضمان عمل هذه المعدات بأعلى كفاءة لأكثر من 10,000 ساعة تشغيل هو ما تصنعه شراكتك مع دار الحي.\n\nإليك كيف يغطي نظامنا الهندسي المتكامل احتياجات المقاولين وملاك الأساطيل في الكويت.\n\nاسحب الشاشة للتعرف على التفاصيل -> واحفظ المنشور كمرجع لإدارة أسطولك.',
        hashtags: '#DarAlHay #KomatsuKuwait #FleetManagement #HeavyEquipmentSupport #PreventiveMaintenance #KuwaitContractors #AssetLifecycle',
        ctaText: 'Swipe through to learn more -> Save this post for your fleet maintenance guide.',
        slides: [
          { slideNo: 1, title: 'Official Komatsu Partnership in Kuwait', body: 'Decades of engineering leadership delivering certified Japanese heavy machinery designed for high-ambient desert endurance.' },
          { slideNo: 2, title: 'Full Machinery Fleet Portfolio', body: 'Hydraulic excavators (20T to 50T), articulated haulers, large wheel loaders, and heavy bulldozers tailored for Kuwait rock and sand.' },
          { slideNo: 3, title: 'Industries We Power Every Day', body: 'Civil infrastructure, mega-highways, marine reclamation, coastal works, aggregate quarrying, and desert development.' },
          { slideNo: 4, title: 'Complete Lifecycle Care (EQP)', body: 'Scheduled 250h/500h/1000h preventive maintenance, KOMTRAX satellite telemetry, and oil analysis to prevent breakdowns.' },
          { slideNo: 5, title: 'Partner With Dar Al Hay Today', body: 'Contact our heavy equipment team to schedule your fleet inspection or request a customized maintenance proposal.' },
        ],
      },
      {
        id: 103,
        conceptNumber: 3,
        week: 'Week 1',
        day: 'Thursday',
        publishDate: '2026-08-06',
        title: 'Hero Machine on Site – Low-Angle Power Shot in South Kuwait',
        pillar: 'pillar_projects',
        format: 'photography',
        platforms: ['instagram', 'linkedin', 'facebook'],
        goal: 'brand_awareness',
        status: 'published',
        targetAudience: 'Civil Engineers, Project Directors, Equipment Enthusiasts',
        tov: 'Inspirational, Bold, High-Aesthetic Industrial',
        summary: 'Powerful low-angle environmental photograph of a Komatsu PC500LC / D155A operating at Sabah Al-Ahmad Sea City with golden hour sunset lighting.',
        hook: {
          spokenEn: 'Power meets precision against the Kuwait golden hour.',
          spokenAr: 'القوة تجتمع مع الدقة مع غروب شمس الكويت.',
          visualHook: 'Ultra-low 24mm wide angle photo with dust backlighting and razor-sharp steel track texture.',
        },
        scenes: [],
        brollChecklist: [
          'High-resolution raw photography from ground level looking up at boom',
          'Golden hour rim light catching sand dust raised by tracks',
          'Close-up of operator in cab with sunglasses looking focused',
        ],
        postProductionNotes: 'Sharpen metallic textures, enhance warm desert tones, high dynamic range color grading.',
        captionEn: 'Built to dominate heavy excavation in 50°C+ summer heat. The Komatsu PC500LC delivers relentless breakout force with advanced hydraulic efficiency.\n\n📍 On site in South Kuwait earthmoving projects.',
        captionAr: 'مصممة للعمل الشاق المتواصل في درجات حرارة تتجاوز 50 درجة مئوية. حفارة كوماتسو PC500LC تمنحك أقصى قوة كسر وحفر مع كفاءة استثنائية في استهلاك الوقود.\n\n📍 موقع العمل - جنوب الكويت.',
        hashtags: '#Komatsu #PC500LC #HeavyEquipmentPhotography #KuwaitConstruction #DesertEarthworks #DarAlHay #GoldenHour',
        ctaText: 'Follow @daralhay_komatsu for daily machinery operations from Kuwait mega-projects.',
        slides: [],
      },
      {
        id: 104,
        conceptNumber: 4,
        week: 'Week 2',
        day: 'Sunday',
        publishDate: '2026-08-09',
        title: 'Why Genuine Komatsu Parts? – The True Cost of Cheap Parts',
        pillar: 'pillar_engineering',
        format: 'carousel',
        platforms: ['linkedin', 'facebook', 'instagram'],
        goal: 'product_education',
        status: 'ready',
        targetAudience: 'Fleet Maintenance Engineers, Procurement Officers, Workshop Managers',
        tov: 'Analytical, Factual, Educational & Persuasive',
        summary: 'Explaining genuine parts reliability, exact tolerances, desert heat filtration, warranty protection, and long-term lifecycle savings.',
        hook: {
          spokenEn: 'Are non-genuine parts costing you thousands in silent downtime? Here is the proof.',
          spokenAr: 'هل تكلفك قطع الغيار المقلدة آلاف الدنانير في التوقف المفاجئ؟ إليك الدليل العلمي.',
          visualHook: 'Microscope side-by-side graphic comparing genuine Komatsu micro-glass filter media vs generic paper filter.',
        },
        scenes: [],
        brollChecklist: [
          'Macro cut-section of a genuine Komatsu hydraulic filter showing synthetic layers',
          'Comparison of worn non-genuine pump seal vs durable genuine Komatsu seal',
          'Barcoded genuine parts packaging on shelves in Shuwaikh warehouse',
        ],
        postProductionNotes: 'Use blueprint styling with clean yellow and navy callouts for specs.',
        captionEn: 'In Kuwait’s fine sand and extreme summer temperatures, a substandard hydraulic filter or seal can cause catastrophic pump failure in under 200 operating hours. Protect your investment with 100% genuine Komatsu components from Dar Al Hay.',
        captionAr: 'في بيئة العمل الصحراوية والحرارة الشديدة بالكويت، استخدام فلاتر أو موانع تسرب غير أصلية قد يسبب أعطالاً مفاجئة في المضخات الهيدروليكية خلال أقل من 200 ساعة. احمِ استثمارك بقطع غيار كوماتسو الأصلية من دار الحي.',
        hashtags: '#GenuineParts #KomatsuParts #DarAlHay #FleetMaintenance #HydraulicFilters #PreventiveMaintenance #TCO',
        ctaText: 'Order genuine parts directly through our Shuwaikh central warehouse with same-day dispatch.',
        slides: [
          { slideNo: 1, title: 'The Desert Filtration Challenge', body: 'Kuwait sand particles measure down to 5 microns. Aftermarket paper filters let up to 40% of micro-debris pass into your hydraulic pumps.' },
          { slideNo: 2, title: 'Micro-Glass Multi-Layer Media', body: 'Genuine Komatsu filters feature synthetic micro-glass fibers capturing 99.8% of micro-particles without restricting high oil flow.' },
          { slideNo: 3, title: 'High-Temperature Oil Seals', body: 'Formulated to withstand 120°C continuous oil temperatures without hardening, cracking, or leaking hydraulic pressure.' },
          { slideNo: 4, title: 'Zero Warranty & Asset Risk', body: 'Genuine parts keep your factory warranty intact and preserve maximum resale value across your entire fleet.' },
          { slideNo: 5, title: '15,000+ Lines in Shuwaikh', body: 'Direct access to Kuwait’s largest genuine Komatsu inventory with immediate site dispatch.' },
        ],
      },
      {
        id: 105,
        conceptNumber: 5,
        week: 'Week 2',
        day: 'Tuesday',
        publishDate: '2026-08-11',
        title: 'Machine Walkaround – WA600 / PC500 Heavy Specs in Kuwait',
        pillar: 'pillar_engineering',
        format: 'reel',
        platforms: ['instagram', 'linkedin', 'facebook'],
        goal: 'product_education',
        status: 'ready',
        targetAudience: 'Contractors, Quarry Operators, Site Supervisors',
        tov: 'Instructive, Engaging, Expert-Led & Technical',
        summary: 'Service Engineer walks around the WA600 Wheel Loader and explains 3 critical design advantages for Kuwait quarry & earthmoving operations.',
        hook: {
          spokenEn: '3 reasons why contractors choose the Komatsu WA600 for heavy sand and quarry loading in Kuwait.',
          spokenAr: '3 أسباب تجعل لودر كوماتسو WA600 الخيار الأول لشركات المقاولات والكسارات في الكويت.',
          visualHook: 'Engineer taps the massive 6.4 cubic meter reinforced bucket with a wrench, stepping into camera frame.',
        },
        scenes: [
          {
            sceneNo: 1,
            time: '0:00 - 0:04',
            visual: 'Engineer standing next to the towering front wheel of the WA600 (larger than human height), addressing camera.',
            talentAction: 'Engineer points up to reinforced Z-bar linkage and heavy-duty lift arms.',
            audioVoiceoverEn: 'If you are moving thousands of tons of sand and rock in Kuwait, here is why the WA600 dominates.',
            audioVoiceoverAr: 'إذا كنت تنقل آلاف الأطنان من الصخور والرمال في الكويت، إليك لماذا يتصدر لودر كوماتسو WA600.',
            onScreenTextEn: 'KOMATSU WA600 WHEEL LOADER | 3 KEY SPECS',
            onScreenTextAr: 'لودر كوماتسو WA600 | 3 مميزات رئيسية',
            sfxMusic: 'High-energy electronic drum intro.',
          },
          {
            sceneNo: 2,
            time: '0:04 - 0:11',
            visual: 'Camera follows engineer walking to the rear engine hood; cut to open side compartment showing massive radiator core.',
            talentAction: 'Engineer demonstrates the hydraulic reversible cooling fan designed for desert dust purging.',
            audioVoiceoverEn: 'First: The high-ambient cooling package with an auto-reversible fan that purges sand build-up automatically.',
            audioVoiceoverAr: 'أولاً: نظام تبريد فائق التحمل مع مروحة هيدروليكية تنظف الرادياتير من الغبار تلقائياً.',
            onScreenTextEn: '1. AUTO-REVERSIBLE DESERT COOLING FAN',
            onScreenTextAr: '1. نظام تبريد صحراوي ومروحة عكسية للتنظيف',
            sfxMusic: 'Subtle mechanical air whoosh sound.',
          },
          {
            sceneNo: 3,
            time: '0:11 - 0:18',
            visual: 'Close-up on heavy drivetrain, axle differential lock, and massive Michelin earthmover tires.',
            talentAction: 'Engineer points to the lock-up torque converter providing maximum rim pull without wheel spin.',
            audioVoiceoverEn: 'Second: Lock-up torque converter delivering maximum traction without burning excess diesel in soft sand.',
            audioVoiceoverAr: 'ثانياً: محول عزم ذكي يمنع انزلاق الإطارات في الرمال الناعمة ويوفر الوقود بشكل ملحوظ.',
            onScreenTextEn: '2. SMART TRACTION & FUEL ECONOMY',
            onScreenTextAr: '2. قوة سحب ذكية وتوفير في استهلاك الديزل',
            sfxMusic: 'Bass synth progression.',
          },
          {
            sceneNo: 4,
            time: '0:18 - 0:25',
            visual: 'Climbing up access ladder into pressurized operator cab; wide shot of ergonomic joystick controls and digital dashboard.',
            talentAction: 'Engineer sits in air-suspension seat, demonstrating climate control and panoramic visibility.',
            audioVoiceoverEn: 'Third: Pressurized dust-free cab keeping operators cool, alert, and productive through 12-hour summer shifts.',
            audioVoiceoverAr: 'ثالثاً: كابينة مكيّفة ومضغوطة تمنع دخول الغبار تماماً لراحة وإنتاجية السائق.',
            onScreenTextEn: '3. PRESSURIZED CLIMATE CABIN',
            onScreenTextAr: '3. كابينة مضغوطة ومكيفة عازلة للغبار',
            sfxMusic: 'Heavy electronic riser.',
          },
        ],
        brollChecklist: [
          'Gimbal orbit shot around front bucket showing wear plates and heavy teeth',
          'Macro shot of digital monitor displaying fuel consumption metrics',
          'Slow motion shot of WA600 wheel driving over sharp rocky terrain',
        ],
        postProductionNotes: 'Add crisp on-screen tech callouts pointing to key mechanical components.',
        captionEn: 'Join our service engineer for a technical walkaround of the powerhouse Komatsu WA600 Wheel Loader.\n\nEngineered for massive bucket payloads, rapid cycle times, and operator endurance in Kuwait’s toughest quarry and earthmoving conditions.\n\n🚜 Discover the engineering difference with Dar Al Hay.',
        captionAr: 'جولة تقنية سريعة مع مهندس الصيانة للتعرف على أسرار لودر كوماتسو WA600 العملاق.\n\nمصمم للتحميل الثقيل، وسرعة دورات العمل، وتحمل أقصى درجات حرارة الصيف في مواقع الكويت.\n\n🚜 اكتشف الفارق الهندسي مع دار الحي.',
        hashtags: '#KomatsuWA600 #WheelLoader #EarthmovingKuwait #DarAlHayEngineering #HeavyMachineryWalkaround #QuarryKuwait',
        ctaText: 'Comment "WA600" to receive the full technical spec sheet and load capacity chart directly.',
        slides: [],
      },
      {
        id: 106,
        conceptNumber: 6,
        week: 'Week 2',
        day: 'Thursday',
        publishDate: '2026-08-13',
        title: 'Inside Our Workshop – Engine & Component Overhaul Standards',
        pillar: 'pillar_workshop',
        format: 'reel',
        platforms: ['linkedin', 'instagram', 'facebook'],
        goal: 'trust_humanize',
        status: 'production',
        targetAudience: 'Fleet Directors, Heavy Equipment Mechanics, Business Owners',
        tov: 'Authentic, High-Craftsmanship, Industrial & Reassuring',
        summary: 'BTS inside the Dar Al Hay central workshop: diagnostic computers, cylinder honing, injector calibration, and precision torque wrenching.',
        hook: {
          spokenEn: 'Behind the scenes where million-dollar heavy machines get restored to factory zero-hour precision.',
          spokenAr: 'خلف الكواليس.. كيف نعيد محركات الآليات الثقيلة إلى كفاءة الصفر ساعة في دار الحي.',
          visualHook: 'Overhead crane slowly lowering a massive 6-cylinder Komatsu turbo diesel engine block onto the rebuild stand.',
        },
        scenes: [],
        brollChecklist: [
          'Macro slow-motion oil pouring over clean camshaft lobes',
          'Electronic torque wrench digital beep readout showing 280 N·m',
          'Overview wide shot of clean, organized multi-bay Shuwaikh workshop',
        ],
        postProductionNotes: 'Cinematic color grade with deep blue shadows and bright amber highlights on tools.',
        captionEn: 'Factory-standard diagnostic equipment, Komatsu-certified master technicians, and genuine overhaul kits.\n\nStep inside the Dar Al Hay central service facility in Shuwaikh, Kuwait — where precision engineering restores your fleet to peak performance.',
        captionAr: 'أحدث أجهزة الفحص والتشخيص المعتمدة عالمياً، مع كادر فني معتمد وقطع غيار أصلية 100%.\n\nنظرة من داخل مركز صيانة دار الحي الرئيسي بالشويخ.. حيث نعيد أسطولك إلى قمة الجاهزية والإنتاجية.',
        hashtags: '#DarAlHayWorkshop #KomatsuService #EngineOverhaul #HeavyMachineryWorkshop #KuwaitEngineering #Shuwaikh',
        ctaText: 'Schedule a certified workshop overhaul or comprehensive diagnostic inspection for your fleet.',
        slides: [],
      },
    ],
  },
  '2026-09': {
    monthId: '2026-09',
    monthName: 'September 2026',
    themeTitle: 'Coastal Infrastructure & Marine Earthworks Megaprojects',
    strategicGoal: 'Showcase Komatsu heavy excavators (PC500LC) and articulated trucks (HM400) powering major Kuwait coastal reclamation projects with 98%+ uptime.',
    targetKpi: '30 Infrastructure Leads • 220,000 Social Impressions • 12 Formal Maintenance Contract Meetings',
    pillarDistribution: { pillar_authority: 15, pillar_engineering: 25, pillar_workshop: 15, pillar_projects: 30, pillar_leadgen: 15 },
    concepts: [
      {
        id: 201,
        conceptNumber: 1,
        week: 'Week 1',
        day: 'Sunday',
        publishDate: '2026-09-06',
        title: 'Marine Earthworks – PC500LC Coastal Excavation in Sea City',
        pillar: 'pillar_projects',
        format: 'reel',
        platforms: ['instagram', 'linkedin', 'facebook'],
        goal: 'case_study',
        status: 'ready',
        targetAudience: 'Marine Contractors, Civil Infrastructure Engineers, Project Directors',
        tov: 'Cinematic, Prestigious, Power-Driven',
        summary: 'Dramatic 30-sec reel showcasing PC500LC excavators dredging coastal waterways and shaping marine canals in Kuwait.',
        hook: {
          spokenEn: 'When sea salt and heavy sand meet Japanese steel. Here is how Komatsu dominates coastal earthworks in Kuwait.',
          spokenAr: 'عندما تلتقي مياه البحر المالحة والرمال الثقيلة بالهندسة اليابانية.. كوماتسو في أضخم مشاريع الردم الساحلي.',
          visualHook: 'Low water-level camera angle with sea spray splashing as a massive PC500LC bucket emerges from the water brimming with wet sand.',
        },
        scenes: [
          {
            sceneNo: 1,
            time: '0:00 - 0:04',
            visual: 'Low water-level 4K shot: Sea spray splashing as giant PC500LC bucket rises from tidal canal filled with wet marine soil.',
            talentAction: 'Operator smoothly raises boom, water cascading off heavy steel teeth.',
            audioVoiceoverEn: 'When sea salt and heavy sand meet Japanese steel.',
            audioVoiceoverAr: 'عندما تلتقي مياه البحر المالحة بالهندسة اليابانية..',
            onScreenTextEn: 'COASTAL MEGA-PROJECTS | KOMATSU PC500LC',
            onScreenTextAr: 'مشاريع الردم الساحلي | كوماتسو PC500LC',
            sfxMusic: 'Deep sub-bass drop with realistic water splash foley.',
          },
          {
            sceneNo: 2,
            time: '0:04 - 0:11',
            visual: 'Drone bird-eye view panning along 2-kilometer coastal waterway; 4 Komatsu excavators operating in synchronized rhythm.',
            talentAction: 'Excavators swinging and dumping directly into waiting HM400 articulated dump trucks.',
            audioVoiceoverEn: 'Moving millions of cubic meters in harsh marine environments with non-stop reliability.',
            audioVoiceoverAr: 'نقل ملايين الأمتار المكعبة في أصعب البيئات البحرية بأعلى جاهزية تشغيلية.',
            onScreenTextEn: 'SYNCHRONIZED FLEET PRODUCTIVITY',
            onScreenTextAr: 'إنتاجية متزامنة للأساطيل الثقيلة',
            sfxMusic: 'Cinematic orchestral rhythm.',
          },
          {
            sceneNo: 3,
            time: '0:11 - 0:18',
            visual: 'Close-up of heavy undercarriage tracks submerged in wet sand, reinforced boom bushings, and anti-corrosive paint finish.',
            talentAction: 'Machine rotates effortlessly without track slippage on soft coastal bed.',
            audioVoiceoverEn: 'Sealed track pins, anti-corrosive coatings, and high-flow hydraulics built for coastal endurance.',
            audioVoiceoverAr: 'جنازير معزولة بالكامل، طلاء مقاوم للأملاح، وهيدروليك فائق التدفق مصمم للتحمل.',
            onScreenTextEn: 'ANTI-CORROSION MARINE ENDURANCE',
            onScreenTextAr: 'مقاومة فائقة للأملاح والتآكل',
            sfxMusic: 'Mechanical metallic rumble.',
          },
          {
            sceneNo: 4,
            time: '0:18 - 0:25',
            visual: 'Dar Al Hay field service truck parked on site embankment; service engineer taking fluid samples for KOWA lab testing.',
            talentAction: 'Engineer sealing oil sample bottle and entering data on tablet.',
            audioVoiceoverEn: 'Backed by dedicated on-site field engineers and certified oil sampling programs.',
            audioVoiceoverAr: 'مدعومة بفرق صيانة ميدانية مخصصة وبرامج فحص زيوت مخبرية معتمدة.',
            onScreenTextEn: '24/7 DEDICATED SITE SUPPORT',
            onScreenTextAr: 'دعم ميداني متخصص في الموقع',
            sfxMusic: 'Uplifting commercial outro chord.',
          },
        ],
        brollChecklist: [
          'Slow motion water droplets dripping from excavator bucket teeth',
          'Wide drone sweeping shot of Sea City water canals at sunrise',
          'POV looking forward from cabin over moving tracks on wet sand',
        ],
        postProductionNotes: 'Grade with rich cyan ocean tones and punchy Komatsu yellow.',
        captionEn: 'Marine salt, fine sand, and non-stop double shifts. The Komatsu PC500LC proves why it is Kuwait’s trusted choice for premier coastal reclamation projects.\n\nSupported by Dar Al Hay’s specialized marine preventive maintenance protocols.',
        captionAr: 'أملاح بحرية، رمال رطبة، وعمل متواصل على مدار الساعة. حفارات كوماتسو PC500LC تثبت تفوقها في أضخم مشاريع الردم الساحلي في الكويت.\n\nبدعم متكامل من برامج الصيانة الوقائية المتخصصة من دار الحي.',
        hashtags: '#MarineReclamation #PC500LC #KomatsuKuwait #SeaCity #CoastalProjects #DarAlHay #HeavyEarthmoving',
        ctaText: 'Partner with Dar Al Hay on your next infrastructure development.',
        slides: [],
      },
      {
        id: 202,
        conceptNumber: 2,
        week: 'Week 1',
        day: 'Tuesday',
        publishDate: '2026-09-08',
        title: 'KOWA Oil Analysis – Predicting Failures Before They Happen',
        pillar: 'pillar_engineering',
        format: 'carousel',
        platforms: ['linkedin', 'facebook', 'instagram'],
        goal: 'product_education',
        status: 'ready',
        targetAudience: 'Fleet Directors, Maintenance Supervisors, Asset Managers',
        tov: 'Scientific, Data-Driven, Authoritative B2B',
        summary: '5-slide educational breakdown of Komatsu Oil & Wear Analysis (KOWA) and how spectral analysis saves tens of thousands in unexpected breakdowns.',
        hook: {
          spokenEn: 'How a 50ml oil sample can save your fleet 15,000 KD in unexpected engine failure.',
          spokenAr: 'كيف يمكن لعينة زيت بحجم 50 مل أن توفر على شركتك أكثر من 15,000 دينار في صيانة المحركات؟',
          visualHook: 'High-tech lab spectrometer analyzing a glowing oil vial with wear metal particle readouts (Fe, Cu, Si).',
        },
        scenes: [],
        brollChecklist: [
          'Engineer drawing oil sample using vacuum extraction pump into sterile bottle',
          'Lab spectrometer machine screen showing ppm wear metal graphs',
          'Dar Al Hay certified KOWA diagnostic report with green/yellow/red status indicators',
        ],
        postProductionNotes: '1080x1350 vertical slides with laboratory aesthetic and clean infographic tables.',
        captionEn: 'Oil is the lifeblood of your heavy machinery. Komatsu Oil & Wear Analysis (KOWA) detects microscopic metal wear particles before catastrophic component failure occurs.\n\nSwipe through to see how proactive laboratory diagnostics protect your fleet ROI.',
        captionAr: 'الزيت هو شريان الحياة لمعدتك الثقيلة. برنامج فحص الزيوت المعتمد KOWA يكشف أدق جزيئات التآكل المعدني قبل وقوع الأعطال المفاجئة في المحركات والمضخات.\n\nاسحب الشاشة للتعرف على دور التحليل المخبري في حماية استثمارك.',
        hashtags: '#KOWA #OilAnalysis #PredictiveMaintenance #KomatsuService #FleetHealth #DarAlHay #TCO',
        ctaText: 'Swipe through -> Request KOWA sampling kits for your fleet today.',
        slides: [
          { slideNo: 1, title: 'What Is KOWA Analysis?', body: 'Komatsu Oil & Wear Analysis uses spectral laboratory diagnostics to measure wear metals, soot, and fluid contamination in parts per million (PPM).' },
          { slideNo: 2, title: 'Early Warning Detection', body: 'Detects bearing wear (Copper/Lead), piston ring erosion (Iron/Chromium), and air filter bypass (Silicon/Sand) hundreds of hours before failure.' },
          { slideNo: 3, title: 'Prevent Catastrophic Overhauls', body: 'A 20 KD oil sample test prevents a 15,000 KD engine seizure by pinpointing faulty injectors or leaking coolant seals early.' },
          { slideNo: 4, title: 'Certified Trend Reporting', body: 'Every sample is logged in your machine’s digital health history, providing clear trend graphs and certified maintenance pedigree.' },
          { slideNo: 5, title: 'Included in Dar Al Hay EQP Agreements', body: 'Our certified engineers draw regular samples during scheduled maintenance intervals across Kuwait.' },
        ],
      },
    ],
  },
  '2026-10': {
    monthId: '2026-10',
    monthName: 'October 2026',
    themeTitle: 'The Overhaul Season: Shuwaikh Master Workshop & Certified Rebuilds',
    strategicGoal: 'Drive high-margin workshop rebuild contracts and promote genuine undercarriage/engine overhaul kits ahead of winter infrastructure peak.',
    targetKpi: '15 Overhaul Contracts Booked • 150,000 Reach • 40 Spare Parts Quotes Dispatched',
    pillarDistribution: { pillar_authority: 15, pillar_engineering: 20, pillar_workshop: 35, pillar_projects: 15, pillar_leadgen: 15 },
    concepts: [
      {
        id: 301,
        conceptNumber: 1,
        week: 'Week 1',
        day: 'Sunday',
        publishDate: '2026-10-04',
        title: 'Zero-Hour Master Rebuild – Inside the Central Engine Bay',
        pillar: 'pillar_workshop',
        format: 'reel',
        platforms: ['linkedin', 'instagram', 'facebook'],
        goal: 'trust_humanize',
        status: 'idea',
        targetAudience: 'Fleet Owners, Plant Managers, Chief Engineers',
        tov: 'High Craftsmanship, Precision Engineering, Industrial',
        summary: 'Macro cinematic walkthrough of a Komatsu SAA6D140E engine overhaul from bare crankcase to dyno test bench in Shuwaikh.',
        hook: {
          spokenEn: 'Watch a 10,000-hour Komatsu engine get rebuilt to Japanese factory zero-hour standards in Kuwait.',
          spokenAr: 'شاهد كيف نعيد محرك كوماتسو بعد 10,000 ساعة عمل إلى معايير المصنع الياباني في الكويت.',
          visualHook: 'Split-screen showing heavily carbonized piston next to brand new mirror-polished genuine Komatsu piston assembly.',
        },
        scenes: [],
        brollChecklist: [
          'Engine cylinder liner honing with cross-hatch pattern close-up',
          'Digital torque wrench clicking on main cylinder head bolts',
          'Computerized dyno test bench screen recording engine RPM and horsepower output',
        ],
        postProductionNotes: 'Sharp industrial sound design with rhythmic ratchet and metallic clicks.',
        captionEn: 'Why replace an entire machine when you can restore its heart to factory zero-hour specifications?\n\nStep inside Dar Al Hay’s central Shuwaikh overhaul facility. 100% genuine parts, certified master technicians, and comprehensive post-rebuild warranty.',
        captionAr: 'لماذا تستبدل المعدة بالكامل بينما يمكنك تجديد محركها إلى كفاءة الصفر ساعة؟\n\nنظرة من داخل مركز الصيانة المتطور لدار الحي بالشويخ. قطع أصلية 100%، فنيون معتمدون، وضمان شامل بعد التجديد.',
        hashtags: '#EngineRebuild #KomatsuWorkshop #Shuwaikh #ZeroHour #HeavyMachineryOverhaul #DarAlHay #PrecisionEngineering',
        ctaText: 'Book your fleet engine overhaul before the winter project rush.',
        slides: [],
      },
    ],
  },
};
