export const MEDIA_PLATFORMS = [
  { id: 'instagram', label: 'Instagram', icon: '📸', color: 'from-pink-500 to-purple-600', badgeTone: 'active', handle: '@daralhay_komatsu' },
  { id: 'linkedin', label: 'LinkedIn', icon: '💼', color: 'from-blue-600 to-blue-800', badgeTone: 'info', handle: 'Dar Al Hay Commercial Co.' },
  { id: 'facebook', label: 'Facebook', icon: '👥', color: 'from-blue-500 to-indigo-600', badgeTone: 'ready', handle: 'Dar Al Hay - Komatsu Kuwait' },
];

export const CONTENT_PILLARS = [
  { id: 'pillar_authority', label: 'Brand Authority & Japanese Heritage', color: 'bg-sky-100 text-sky-900 border-sky-300', desc: 'Highlighting Komatsu Japanese precision, Dar Al Hay partnership, and Kuwait infrastructure leadership.' },
  { id: 'pillar_engineering', label: 'Technical & Product Education', color: 'bg-indigo-100 text-indigo-900 border-indigo-300', desc: 'Deep-dive machine walkthroughs, specs, KOMTRAX telematics, and heavy-duty desert cooling systems.' },
  { id: 'pillar_workshop', label: 'Behind-The-Scenes & Workshop', color: 'bg-amber-100 text-amber-900 border-amber-300', desc: 'Humanizing certified engineers, engine overhauls, diagnostic testing, and parts warehouse inventory.' },
  { id: 'pillar_projects', label: 'Kuwait Jobsites & Case Studies', color: 'bg-emerald-100 text-emerald-900 border-emerald-300', desc: 'Real-world machinery performance at Sabah Al-Ahmad Sea City, desert earthworks, and highway projects.' },
  { id: 'pillar_leadgen', label: 'After-Sales & Lead Generation', color: 'bg-rose-100 text-rose-900 border-rose-300', desc: 'Emergency field service, genuine parts direct delivery, EQP maintenance contracts, and machine sales.' },
];

export const FORMAT_TYPES = [
  { id: 'reel', label: 'Reels / Motion Video', icon: '🎬', tag: 'Motion / BTS / Walkaround', color: 'bg-purple-100 text-purple-900 border-purple-300' },
  { id: 'carousel', label: 'Carousels (Multi-Slide)', icon: '📑', tag: 'Education / Story / Specs', color: 'bg-indigo-100 text-indigo-900 border-indigo-300' },
  { id: 'photography', label: 'Hero Photography', icon: '📸', tag: 'Environmental / Machinery / People', color: 'bg-emerald-100 text-emerald-900 border-emerald-300' },
  { id: 'designed_post', label: 'Infographic / Graphic Post', icon: '🎨', tag: 'Facts / Data / Telemetry', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { id: 'cta_post', label: 'Conversion / CTA Post', icon: '🎯', tag: 'Lead Gen / Sales / Service Call', color: 'bg-rose-100 text-rose-900 border-rose-300' },
];

export const GOAL_TYPES = [
  { id: 'brand_awareness', label: 'Brand Awareness & Positioning', color: 'bg-sky-50 text-sky-800 border-sky-200' },
  { id: 'product_education', label: 'Product Education & Specs', color: 'bg-indigo-50 text-indigo-800 border-indigo-200' },
  { id: 'lead_generation', label: 'Lead Generation & Sales Inquiry', color: 'bg-rose-50 text-rose-800 border-rose-200' },
  { id: 'trust_humanize', label: 'Trust & Humanizing the Brand', color: 'bg-emerald-50 text-emerald-800 border-emerald-200' },
  { id: 'case_study', label: 'Social Proof & Project Validation', color: 'bg-amber-50 text-amber-800 border-amber-200' },
  { id: 'expertise', label: 'Engineering Expertise & Maintenance', color: 'bg-purple-50 text-purple-800 border-purple-200' },
];

export const PIPELINE_STAGES = [
  { id: 'idea', label: '1. Strategy & Idea', icon: '💡', badgeTone: 'neutral' },
  { id: 'scripted', label: '2. Scripted & Briefed', icon: '📝', badgeTone: 'info' },
  { id: 'production', label: '3. Shooting / Designing', icon: '🎬', badgeTone: 'warning' },
  { id: 'review', label: '4. Quality & TOV Review', icon: '👀', badgeTone: 'yellow' },
  { id: 'ready', label: '5. Scheduled & Ready', icon: '🚀', badgeTone: 'active' },
  { id: 'published', label: '6. Published & Monitored', icon: '✅', badgeTone: 'ready' },
];

export const TOV_GUIDELINES = {
  overall: {
    title: 'Dar Al Hay Brand Voice & Persona',
    summary: 'Authoritative, Precision-Driven, Industrial Strength, and Rooted in Kuwait Progress.',
    traits: [
      { name: 'Japanese Precision & Heritage', desc: 'Emphasize Komatsu factory standards, strict quality controls, and world-leading hydraulic engineering.' },
      { name: 'Kuwait Desert Toughness', desc: 'Acknowledge the harsh 50°C+ climate, fine desert sand, and heavy rock conditions in Kuwait and how our machines conquer them.' },
      { name: 'Unwavering Engineering Authority', desc: 'Talk like certified master engineers and fleet directors — avoid generic sales fluff, focus on uptime, SMR hours, fuel efficiency, and ROI.' },
      { name: 'Customer Partnership', desc: 'Frame Dar Al Hay not just as an equipment seller, but as an indispensable operational partner on Kuwait megaprojects.' },
    ],
  },
  platforms: {
    linkedin: {
      platform: 'LinkedIn',
      tone: 'Authoritative B2B Engineering & Fleet Economics',
      target: 'C-Suite, Procurement Directors, Project Managers, Fleet Supervisors',
      guidelines: 'Focus on total cost of ownership (TCO), fuel economy data, KOMTRAX satellite telemetry, preventive maintenance contracts, and Kuwait project case studies. Use professional terminology and structured bullet points.',
    },
    instagram: {
      platform: 'Instagram',
      tone: 'Visual, High-Energy, Cinematic, & Behind-The-Scenes',
      target: 'Heavy Machinery Operators, Young Engineers, Contractors, Brand Fans',
      guidelines: 'Lead with strong 3-second visual hooks, close-up engine sounds, slow-motion hydraulic action, golden hour desert shots, and relatable maintenance tips.',
    },
    facebook: {
      platform: 'Facebook',
      tone: 'Community-Focused, Accessible, Practical & Bilingual (Arabic First)',
      target: 'Local Subcontractors, Workshop Owners, Equipment Operators, General Public',
      guidelines: 'Clear value propositions, direct WhatsApp/phone contact CTAs, workshop open days, fast spare parts availability, and transparent service offerings in both Arabic and English.',
    },
  },
  doAndDont: [
    { do: 'Use exact technical terms (e.g., PC350LC-8M0, SAA6D114E-3 engine, KOMTRAX, KTCS traction).', dont: 'Use vague generic terms like "our big digger" or "super strong machine".' },
    { do: 'Provide bilingual copy (Arabic + English) with natural professional Gulf/Kuwait phrasing.', dont: 'Rely on automated literal translations that sound robotic or awkward.' },
    { do: 'Highlight certified engineers, PPE safety helmets, clean Shuwaikh workshop, and genuine parts.', dont: 'Show uncertified field repairs without safety gear or messy workshop environments.' },
    { do: 'Include clear Call To Actions with contact numbers, WhatsApp links, and showroom location.', dont: 'Leave posts with no next step for interested fleet managers.' },
  ],
};

export const PRE_PRODUCTION_CHECKLIST = [
  { id: 'permits', category: 'Approvals & Access', task: 'Obtain worksite entry and filming permits (Kuwait Municipality / PAHW / KOC / Client).' },
  { id: 'safety', category: 'Safety & PPE', task: 'Ensure all filming crew and on-screen staff wear Komatsu safety vests, hard hats, and steel-toe boots.' },
  { id: 'cleaning', category: 'Asset Preparation', task: 'Pressure wash machine body, bucket, and tracks; ensure Komatsu & Dar Al Hay branding stickers are clean and visible.' },
  { id: 'camera', category: 'Camera & Lighting', task: 'Pack 4K gimbal stabilizer, wide-angle lens (16-35mm), macro lens for parts, and circular polarizer filter for desert glare.' },
  { id: 'audio', category: 'Audio Gear', task: 'Test dual wireless lapel microphones with deadcat wind protection for clear voiceover in windy desert conditions.' },
  { id: 'talent', category: 'Talent Briefing', task: 'Rehearse spoken script in both Arabic and English with certified service engineer prior to rolling camera.' },
];

export const MASTER_MONTHLY_PLAN = [
  {
    id: 1,
    conceptNumber: 1,
    week: 'Week 1',
    day: 'Sunday',
    publishDate: '2026-08-30',
    title: 'Hero Machine – PC350LC-8M0 Cinematic Brand Intro',
    pillar: 'pillar_authority',
    format: 'reel',
    platforms: ['instagram', 'linkedin', 'facebook'],
    goal: 'brand_awareness',
    status: 'ready',
    targetAudience: 'Contractors, Government Infrastructure Stakeholders, Fleet Owners',
    tov: 'Cinematic, High-Impact, Authoritative Industrial',
    summary: 'Cinematic 25-sec video intro: Kuwait desert landscape -> Dar Al Hay facility -> Komatsu machine lineup -> Workshop engine rebuild -> Parts warehouse -> Engineering team -> Logo lockup.',
    hook: {
      spokenEn: 'Built for the toughest desert terrain on earth. Meet Komatsu in Kuwait.',
      spokenAr: 'صُنعت لتقهر أصعب تضاريس الصحراء في العالم.. كوماتسو في الكويت.',
      visualHook: 'Rapid cinematic crash-zoom from drone altitude over South Kuwait desert directly into the heavy steel bucket of a Komatsu PC350LC digging through rock.',
    },
    scenes: [
      {
        sceneNo: 1,
        time: '0:00 - 0:03',
        visual: 'Drone wide establishing shot: Sunrise over Kuwait desert highway, transition to low-angle PC350LC track moving forward.',
        talentAction: 'Machine operator swings boom smoothly into frame, sun flare hits heavy hydraulic cylinder.',
        audioVoiceoverEn: 'Built for the toughest desert terrain on earth.',
        audioVoiceoverAr: 'صُنعت لتقهر أصعب تضاريس الصحراء في العالم..',
        onScreenTextEn: 'BUILT FOR KUWAIT | KOMATSU PC350LC-8M0',
        onScreenTextAr: 'صُنعت للكويت | كوماتسو PC350LC',
        sfxMusic: 'Cinematic low-bass sub drop into driving industrial beat; deep Komatsu engine roar.',
      },
      {
        sceneNo: 2,
        time: '0:03 - 0:08',
        visual: 'Fast match-cut to Dar Al Hay headquarters & modern Shuwaikh showroom exterior, then into wide fleet yard.',
        talentAction: 'Service Engineer in Komatsu uniform walking purposefully toward camera carrying digital diagnostic tablet.',
        audioVoiceoverEn: 'Backed by Dar Al Hay’s world-class engineering and certified local support.',
        audioVoiceoverAr: 'بدعم هندسي متكامل وخبرة معتمدة من دار الحي.',
        onScreenTextEn: 'OFFICIAL KOMATSU DISTRIBUTOR IN KUWAIT',
        onScreenTextAr: 'الموزع المعتمد لكوماتسو في الكويت',
        sfxMusic: 'Rhythmic percussive riser.',
      },
      {
        sceneNo: 3,
        time: '0:08 - 0:15',
        visual: 'Macro rapid-fire montage inside central workshop: Torque wrench clicking on cylinder head, glowing parts wash tank, digital hydraulic pressure gauge.',
        talentAction: 'Master technician tightening manifold with calibrated wrench; Sparks from welding in soft background.',
        audioVoiceoverEn: 'Overhaul expertise, 15,000+ genuine parts on shelf, and 24/7 mobile field response.',
        audioVoiceoverAr: 'مراكز صيانة متطورة، أكثر من 15,000 قطعة غيار أصلية جاهزة، وفرق دعم ميداني على مدار الساعة.',
        onScreenTextEn: 'GENUINE PARTS • CERTIFIED OVERHAULS • 24/7 FIELD CARE',
        onScreenTextAr: 'قطع أصلية • صيانة معتمدة • خدمة ميدانية 24/7',
        sfxMusic: 'Mechanical metallic ratchet clicks foley + deep synthesizer pulse.',
      },
      {
        sceneNo: 4,
        time: '0:15 - 0:22',
        visual: 'Return to worksite action: Massive 3-meter bucket cutting through desert hardpack, loading articulated dump truck with zero hesitation.',
        talentAction: 'Operator smoothly cycling hydraulic controls inside air-conditioned pressurized cabin.',
        audioVoiceoverEn: 'Powering Kuwait’s national megaprojects with uncompromising Japanese reliability.',
        audioVoiceoverAr: 'نشيد مشاريع الكويت الكبرى بأعلى معايير الاعتمادية اليابانية.',
        onScreenTextEn: 'POWERING KUWAIT’S INFRASTRUCTURE',
        onScreenTextAr: 'نبني مستقبل مشاريع الكويت',
        sfxMusic: 'Epic cinematic orchestral crescendo.',
      },
      {
        sceneNo: 5,
        time: '0:22 - 0:26',
        visual: 'Clean navy slate screen with Komatsu & Dar Al Hay gold logos lockup, showroom address and contact hotline.',
        talentAction: 'Logo animation with subtle metallic sheen reflection.',
        audioVoiceoverEn: 'Dar Al Hay. Your heavy machinery partner in Kuwait.',
        audioVoiceoverAr: 'دار الحي.. شريكك الموثوق للمعدات الثقيلة في الكويت.',
        onScreenTextEn: 'Dar Al Hay Commercial Co. | Shuwaikh | +965 2200 XXXX',
        onScreenTextAr: 'شركة دار الحي التجارية | الشويخ | 2200XXXX 965+',
        sfxMusic: 'Final clean brand audio logo chord.',
      },
    ],
    brollChecklist: [
      '4K 60fps slow-motion drone flyby over desert excavator at sunrise',
      'Macro close-up of hydraulic hoses flexing under 350 bar pressure',
      'Shuwaikh warehouse aisle showing organized barcoded genuine Komatsu yellow boxes',
      'Technician using calibrated digital torque wrench on diesel engine block',
      'Operator cabin POV looking out through clean windshield at bucket digging',
    ],
    postProductionNotes: 'Grade with warm desert golden hour contrast while preserving true Komatsu yellow (#FFD100) and Dar Al Hay deep navy. Deliver in 9:16 (IG/FB Reels) and 16:9 (LinkedIn/YouTube).',
    captionEn: 'From high-speed national highway networks to deep marine earthworks, Komatsu heavy machinery powers Kuwait’s progress.\n\nBacked by Dar Al Hay’s factory-trained engineers, extensive genuine parts inventory in Shuwaikh, and 24/7 mobile field service.\n\n🚜 Explore our heavy excavator and earthmoving fleet today.\n\n📍 Visit our Shuwaikh central showroom or contact our heavy equipment specialists.',
    captionAr: 'من شبكات الطرق السريعة ومشاريع البنية التحتية الكبرى إلى أضخم أعمال الردم والإنشاءات، تواصل معدات كوماتسو ريادتها في الكويت.\n\nمدعومة بخبرات دار الحي الهندسية المعتمدة، ومخزون متكامل من قطع الغيار الأصلية في الشويخ، وفرق صيانة ميدانية متنقلة 24/7.\n\n🚜 استكشف أسطول الحفارات والمعدات الثقيلة المتوفرة الآن.\n\n📍 تفضل بزيارة معرضنا الرئيسي بالشويخ أو تواصل مع مستشاري المعدات الثقيلة.',
    hashtags: '#Komatsu #DarAlHay #KuwaitConstruction #HeavyMachinery #PC350LC #Excavator #KuwaitEngineers #KuwaitMegaprojects #Earthmoving #Shuwaikh',
    ctaText: 'Visit our Shuwaikh showroom or call our heavy equipment sales desk for fleet quotations.',
    slides: [],
  },
  {
    id: 2,
    conceptNumber: 2,
    week: 'Week 1',
    day: 'Tuesday',
    publishDate: '2026-09-01',
    title: 'Service Tips – Dar Al Hay Complete Partnership Ecosystem',
    pillar: 'pillar_authority',
    format: 'carousel',
    platforms: ['linkedin', 'instagram', 'facebook'],
    goal: 'brand_awareness',
    status: 'scripted',
    targetAudience: 'Fleet Managers, Maintenance Directors, Construction Contractors',
    tov: 'Corporate, Educational, Consultative & Reassuring',
    summary: '5-slide carousel explaining the relationship between Dar Al Hay & Komatsu, services provided, industries served, and contact CTA.',
    hook: {
      spokenEn: 'More than just heavy machines: How Dar Al Hay protects your fleet lifecycle in Kuwait.',
      spokenAr: 'أكثر من مجرد توريد آليات.. كيف تحمي دار الحي استثمارك وأسطولك في الكويت.',
      visualHook: 'High-contrast graphic showing a Komatsu excavator split into 5 operational support sectors.',
    },
    scenes: [],
    brollChecklist: [
      'Studio photography of Komatsu equipment manuals and diagnostic tools',
      'Clean architectural photo of Dar Al Hay Shuwaikh service complex',
      'Field service truck dispatched onto dusty Kuwait jobsite',
    ],
    postProductionNotes: '1080x1350 vertical carousel format for Instagram and PDF document swipe for LinkedIn.',
    captionEn: 'Purchasing heavy machinery is an investment. Ensuring that machine delivers maximum uptime over 10,000+ operating hours is where Dar Al Hay makes the difference.\n\nHere is how our complete engineering ecosystem supports contractors and fleet managers across Kuwait.\n\nSwipe through -> Save this post for your fleet management handbook.',
    captionAr: 'شراء المعدات الثقيلة استثمار استراتيجي. وضمان عمل هذه المعدات بأعلى كفاءة لأكثر من 10,000 ساعة تشغيل هو ما تصنعه شراكتك مع دار الحي.\n\nإليك كيف يغطي نظامنا الهندسي المتكامل احتياجات المقاولين وملاك الأساطيل في الكويت.\n\nاسحب الشاشة للتعرف على التفاصيل -> واحفظ المنشور كمرجع لإدارة أسطولك.',
    hashtags: '#DarAlHay #KomatsuKuwait #FleetManagement #HeavyEquipmentSupport #PreventiveMaintenance #KuwaitContractors #AssetLifecycle',
    ctaText: 'Swipe through to learn more -> Save this post for your fleet maintenance guide.',
    slides: [
      { slideNo: 1, title: 'Official Komatsu Partnership in Kuwait', body: 'Decades of engineering leadership delivering certified Japanese heavy machinery designed for high-ambient desert endurance.' },
      { slideNo: 2, title: 'Full Machinery Fleet Portfolio', body: 'Hydraulic excavators (20T to 50T), articulated haulers, large wheel loaders, and heavy bulldozers tailored for Kuwait rock and sand.' },
      { slideNo: 3, title: 'Industries We Power Every Day', body: 'Civil infrastructure, mega-highways, marine reclamation, coastal works, aggregate quarrying, and desert development.' },
      { slideNo: 4, title: 'Complete Lifecycle Care (EQP)', body: 'Scheduled 250h/500h/1000h preventive maintenance, KOMTRAX satellite telemetry, and oil analysis to prevent breakdowns.' },
      { slideNo: 5, title: 'Partner With Dar Al Hay Today', body: 'Contact our heavy equipment team to schedule your fleet inspection or request a customized maintenance proposal.' },
    ],
  },
  {
    id: 3,
    conceptNumber: 3,
    week: 'Week 1',
    day: 'Thursday',
    publishDate: '2026-09-03',
    title: 'Hero Machine on Site – Low-Angle Power Shot in South Kuwait',
    pillar: 'pillar_projects',
    format: 'photography',
    platforms: ['instagram', 'linkedin', 'facebook'],
    goal: 'brand_awareness',
    status: 'production',
    targetAudience: 'Civil Engineers, Project Directors, Equipment Enthusiasts',
    tov: 'Inspirational, Bold, High-Aesthetic Industrial',
    summary: 'Powerful low-angle environmental photograph of a Komatsu PC500LC / D155A operating at Sabah Al-Ahmad Sea City with golden hour sunset lighting.',
    hook: {
      spokenEn: 'Power meets precision against the Kuwait golden hour.',
      spokenAr: 'القوة تجتمع مع الدقة مع غروب شمس الكويت.',
      visualHook: 'Ultra-low 24mm wide angle photo with dust backlighting and razor-sharp steel track texture.',
    },
    scenes: [],
    brollChecklist: [
      'High-resolution raw photography from ground level looking up at boom',
      'Golden hour rim light catching sand dust raised by tracks',
      'Close-up of operator in cab with sunglasses looking focused',
    ],
    postProductionNotes: 'Sharpen metallic textures, enhance warm desert tones, high dynamic range color grading.',
    captionEn: 'Built to dominate heavy excavation in 50°C+ summer heat. The Komatsu PC500LC delivers relentless breakout force with advanced hydraulic efficiency.\n\n📍 On site in South Kuwait earthmoving projects.',
    captionAr: 'مصممة للعمل الشاق المتواصل في درجات حرارة تتجاوز 50 درجة مئوية. حفارة كوماتسو PC500LC تمنحك أقصى قوة كسر وحفر مع كفاءة استثنائية في استهلاك الوقود.\n\n📍 موقع العمل - جنوب الكويت.',
    hashtags: '#Komatsu #PC500LC #HeavyEquipmentPhotography #KuwaitConstruction #DesertEarthworks #DarAlHay #GoldenHour',
    ctaText: 'Follow @daralhay_komatsu for daily machinery operations from Kuwait mega-projects.',
    slides: [],
  },
  {
    id: 4,
    conceptNumber: 4,
    week: 'Week 2',
    day: 'Sunday',
    publishDate: '2026-09-06',
    title: 'Why Genuine Komatsu Parts? – The True Cost of Cheap Parts',
    pillar: 'pillar_engineering',
    format: 'carousel',
    platforms: ['linkedin', 'facebook', 'instagram'],
    goal: 'product_education',
    status: 'scripted',
    targetAudience: 'Fleet Maintenance Engineers, Procurement Officers, Workshop Managers',
    tov: 'Analytical, Factual, Educational & Persuasive',
    summary: 'Explaining genuine parts reliability, exact tolerances, desert heat filtration, warranty protection, and long-term lifecycle savings.',
    hook: {
      spokenEn: 'Are non-genuine parts costing you thousands in silent downtime? Here is the proof.',
      spokenAr: 'هل تكلفك قطع الغيار المقلدة آلاف الدنانير في التوقف المفاجئ؟ إليك الدليل العلمي.',
      visualHook: 'Microscope side-by-side graphic comparing genuine Komatsu micro-glass filter media vs generic paper filter.',
    },
    scenes: [],
    brollChecklist: [
      'Macro cut-section of a genuine Komatsu hydraulic filter showing synthetic layers',
      'Comparison of worn non-genuine pump seal vs durable genuine Komatsu seal',
      'Barcoded genuine parts packaging on shelves in Shuwaikh warehouse',
    ],
    postProductionNotes: 'Use blueprint styling with clean yellow and navy callouts for specs.',
    captionEn: 'In Kuwait’s fine sand and extreme summer temperatures, a substandard hydraulic filter or seal can cause catastrophic pump failure in under 200 operating hours. Protect your investment with 100% genuine Komatsu components from Dar Al Hay.',
    captionAr: 'في بيئة العمل الصحراوية والحرارة الشديدة بالكويت، استخدام فلاتر أو موانع تسرب غير أصلية قد يسبب أعطالاً مفاجئة في المضخات الهيدروليكية خلال أقل من 200 ساعة. احمِ استثمارك بقطع غيار كوماتسو الأصلية من دار الحي.',
    hashtags: '#GenuineParts #KomatsuParts #DarAlHay #FleetMaintenance #HydraulicFilters #PreventiveMaintenance #TCO',
    ctaText: 'Order genuine parts directly through our Shuwaikh central warehouse with same-day dispatch.',
    slides: [
      { slideNo: 1, title: 'The Desert Filtration Challenge', body: 'Kuwait sand particles measure down to 5 microns. Aftermarket paper filters let up to 40% of micro-debris pass into your hydraulic pumps.' },
      { slideNo: 2, title: 'Micro-Glass Multi-Layer Media', body: 'Genuine Komatsu filters feature synthetic micro-glass fibers capturing 99.8% of micro-particles without restricting high oil flow.' },
      { slideNo: 3, title: 'High-Temperature Oil Seals', body: 'Formulated to withstand 120°C continuous oil temperatures without hardening, cracking, or leaking hydraulic pressure.' },
      { slideNo: 4, title: 'Zero Warranty & Asset Risk', body: 'Genuine parts keep your factory warranty intact and preserve maximum resale value across your entire fleet.' },
      { slideNo: 5, title: '15,000+ Lines in Shuwaikh', body: 'Direct access to Kuwait’s largest genuine Komatsu inventory with immediate site dispatch.' },
    ],
  },
  {
    id: 5,
    conceptNumber: 5,
    week: 'Week 2',
    day: 'Tuesday',
    publishDate: '2026-09-08',
    title: 'Machine Walkaround – WA600 / PC500 Heavy Specs in Kuwait',
    pillar: 'pillar_engineering',
    format: 'reel',
    platforms: ['instagram', 'linkedin', 'facebook'],
    goal: 'product_education',
    status: 'production',
    targetAudience: 'Contractors, Quarry Operators, Site Supervisors',
    tov: 'Instructive, Engaging, Expert-Led & Technical',
    summary: 'Service Engineer walks around the WA600 Wheel Loader and explains 3 critical design advantages for Kuwait quarry & earthmoving operations.',
    hook: {
      spokenEn: '3 reasons why contractors choose the Komatsu WA600 for heavy sand and quarry loading in Kuwait.',
      spokenAr: '3 أسباب تجعل لودر كوماتسو WA600 الخيار الأول لشركات المقاولات والكسارات في الكويت.',
      visualHook: 'Engineer taps the massive 6.4 cubic meter reinforced bucket with a wrench, stepping into camera frame.',
    },
    scenes: [
      {
        sceneNo: 1,
        time: '0:00 - 0:04',
        visual: 'Engineer standing next to the towering front wheel of the WA600 (larger than human height), addressing camera.',
        talentAction: 'Engineer points up to reinforced Z-bar linkage and heavy-duty lift arms.',
        audioVoiceoverEn: 'If you are moving thousands of tons of sand and rock in Kuwait, here is why the WA600 dominates.',
        audioVoiceoverAr: 'إذا كنت تنقل آلاف الأطنان من الصخور والرمال في الكويت، إليك لماذا يتصدر لودر كوماتسو WA600.',
        onScreenTextEn: 'KOMATSU WA600 WHEEL LOADER | 3 KEY SPECS',
        onScreenTextAr: 'لودر كوماتسو WA600 | 3 مميزات رئيسية',
        sfxMusic: 'High-energy electronic drum intro.',
      },
      {
        sceneNo: 2,
        time: '0:04 - 0:11',
        visual: 'Camera follows engineer walking to the rear engine hood; cut to open side compartment showing massive radiator core.',
        talentAction: 'Engineer demonstrates the hydraulic reversible cooling fan designed for desert dust purging.',
        audioVoiceoverEn: 'First: The high-ambient cooling package with an auto-reversible fan that purges sand build-up automatically.',
        audioVoiceoverAr: 'أولاً: نظام تبريد فائق التحمل مع مروحة هيدروليكية تنظف الرادياتير من الغبار تلقائياً.',
        onScreenTextEn: '1. AUTO-REVERSIBLE DESERT COOLING FAN',
        onScreenTextAr: '1. نظام تبريد صحراوي ومروحة عكسية للتنظيف',
        sfxMusic: 'Subtle mechanical air whoosh sound.',
      },
      {
        sceneNo: 3,
        time: '0:11 - 0:18',
        visual: 'Close-up on heavy drivetrain, axle differential lock, and massive Michelin earthmover tires.',
        talentAction: 'Engineer points to the lock-up torque converter providing maximum rim pull without wheel spin.',
        audioVoiceoverEn: 'Second: Lock-up torque converter delivering maximum traction without burning excess diesel in soft sand.',
        audioVoiceoverAr: 'ثانياً: محول عزم ذكي يمنع انزلاق الإطارات في الرمال الناعمة ويوفر الوقود بشكل ملحوظ.',
        onScreenTextEn: '2. SMART TRACTION & FUEL ECONOMY',
        onScreenTextAr: '2. قوة سحب ذكية وتوفير في استهلاك الديزل',
        sfxMusic: 'Bass synth progression.',
      },
      {
        sceneNo: 4,
        time: '0:18 - 0:25',
        visual: 'Climbing up access ladder into pressurized operator cab; wide shot of ergonomic joystick controls and digital dashboard.',
        talentAction: 'Engineer sits in air-suspension seat, demonstrating climate control and panoramic visibility.',
        audioVoiceoverEn: 'Third: Pressurized dust-free cab keeping operators cool, alert, and productive through 12-hour summer shifts.',
        audioVoiceoverAr: 'ثالثاً: كابينة مكيّفة ومضغوطة تمنع دخول الغبار تماماً لراحة وإنتاجية السائق.',
        onScreenTextEn: '3. PRESSURIZED CLIMATE CABIN',
        onScreenTextAr: '3. كابينة مضغوطة ومكيفة عازلة للغبار',
        sfxMusic: 'Heavy electronic riser.',
      },
      {
        sceneNo: 5,
        time: '0:25 - 0:30',
        visual: 'WA600 charging forward and filling full bucket with limestone in single smooth pass; Dar Al Hay contact details.',
        talentAction: 'Machine lifts loaded bucket high and dumps into trailer.',
        audioVoiceoverEn: 'Available now at Dar Al Hay. Book your on-site demo today.',
        audioVoiceoverAr: 'متوفر الآن لدى دار الحي. تواصل معنا لطلب عرض تجريبي في موقعك.',
        onScreenTextEn: 'Book Your Demo | Dar Al Hay Komatsu Kuwait',
        onScreenTextAr: 'احجز تجربتك الميدانية | دار الحي كوماتسو الكويت',
        sfxMusic: 'Energetic outro chord.',
      },
    ],
    brollChecklist: [
      'Gimbal orbit shot around front bucket showing wear plates and heavy teeth',
      'Macro shot of digital monitor displaying fuel consumption metrics',
      'Slow motion shot of WA600 wheel driving over sharp rocky terrain',
    ],
    postProductionNotes: 'Add crisp on-screen tech callouts pointing to key mechanical components.',
    captionEn: 'Join our service engineer for a technical walkaround of the powerhouse Komatsu WA600 Wheel Loader.\n\nEngineered for massive bucket payloads, rapid cycle times, and operator endurance in Kuwait’s toughest quarry and earthmoving conditions.\n\n🚜 Discover the engineering difference with Dar Al Hay.',
    captionAr: 'جولة تقنية سريعة مع مهندس الصيانة للتعرف على أسرار لودر كوماتسو WA600 العملاق.\n\nمصمم للتحميل الثقيل، وسرعة دورات العمل، وتحمل أقصى درجات حرارة الصيف في مواقع الكويت.\n\n🚜 اكتشف الفارق الهندسي مع دار الحي.',
    hashtags: '#KomatsuWA600 #WheelLoader #EarthmovingKuwait #DarAlHayEngineering #HeavyMachineryWalkaround #QuarryKuwait',
    ctaText: 'Comment "WA600" to receive the full technical spec sheet and load capacity chart directly.',
    slides: [],
  },
  {
    id: 6,
    conceptNumber: 6,
    week: 'Week 2',
    day: 'Thursday',
    publishDate: '2026-09-10',
    title: 'Inside Our Workshop – Engine & Component Overhaul Standards',
    pillar: 'pillar_workshop',
    format: 'reel',
    platforms: ['linkedin', 'instagram', 'facebook'],
    goal: 'trust_humanize',
    status: 'idea',
    targetAudience: 'Fleet Directors, Heavy Equipment Mechanics, Business Owners',
    tov: 'Authentic, High-Craftsmanship, Industrial & Reassuring',
    summary: 'BTS inside the Dar Al Hay central workshop: diagnostic computers, cylinder honing, injector calibration, and precision torque wrenching.',
    hook: {
      spokenEn: 'Behind the scenes where million-dollar heavy machines get restored to factory zero-hour precision.',
      spokenAr: 'خلف الكواليس.. كيف نعيد محركات الآليات الثقيلة إلى كفاءة الصفر ساعة في دار الحي.',
      visualHook: 'Overhead crane slowly lowering a massive 6-cylinder Komatsu turbo diesel engine block onto the rebuild stand.',
    },
    scenes: [
      {
        sceneNo: 1,
        time: '0:00 - 0:04',
        visual: 'Overhead workshop crane gliding along yellow gantry, hoisting a clean diesel engine block.',
        talentAction: 'Two certified technicians guiding engine smoothly with safety tethers.',
        audioVoiceoverEn: 'When a heavy Komatsu engine enters our Shuwaikh central workshop, it gets rebuilt to factory zero hours.',
        audioVoiceoverAr: 'عندما يدخل محرك كوماتسو إلى مركز الصيانة الرئيسي بالشويخ، يعاد بناؤه وفق معايير المصنع الياباني تماماً.',
        onScreenTextEn: 'DAR AL HAY CENTRAL WORKSHOP | SHUWAIKH',
        onScreenTextAr: 'مركز صيانة دار الحي الرئيسي | الشويخ',
        sfxMusic: 'Industrial rhythmic clank and electronic synth beat.',
      },
      {
        sceneNo: 2,
        time: '0:04 - 0:10',
        visual: 'Close-up of digital micrometer measuring piston ring end-gap to within 0.01mm tolerance.',
        talentAction: 'Master technician inspecting readouts under bright LED work lights.',
        audioVoiceoverEn: 'Every bearing, injector, and cylinder liner is calibrated within microscopic factory tolerances.',
        audioVoiceoverAr: 'يتم قياس وفحص أدق الخلوصات الهندسية بأحدث الأجهزة الإلكترونية لضمان الأداء الكامل.',
        onScreenTextEn: 'MICROSCOPIC FACTORY TOLERANCES',
        onScreenTextAr: 'دقة متناهية وفق معايير المصنع',
        sfxMusic: 'High-precision metal tap foley.',
      },
      {
        sceneNo: 3,
        time: '0:10 - 0:17',
        visual: 'Montage: High-pressure component wash tank cleaning valves, then moving to computerized hydraulic pump test bench.',
        talentAction: 'Technician adjusting flow valve while digital graphs plot pressure curves in real time.',
        audioVoiceoverEn: 'Hydraulic pumps and control valves are dyno-tested under full operating pressure before release.',
        audioVoiceoverAr: 'تخضع المضخات الهيدروليكية والصمامات لاختبارات ضغط متقدمة تحاكي أقسى ظروف العمل.',
        onScreenTextEn: 'CERTIFIED HYDRAULIC TEST BENCH',
        onScreenTextAr: 'منصة اختبار هيدروليكي معتمدة',
        sfxMusic: 'Hydraulic pressurization whine sound effect.',
      },
      {
        sceneNo: 4,
        time: '0:17 - 0:24',
        visual: 'Complete assembled engine roaring to life on test stand, certified inspection report stamped and signed.',
        talentAction: 'Lead engineer smiling and shaking hands with technician over completed job.',
        audioVoiceoverEn: 'Backed by genuine parts warranty and certified engineering reports you can trust.',
        audioVoiceoverAr: 'مع ضمان شامل على قطع الغيار الأصلية وتقارير فحص موثقة.',
        onScreenTextEn: 'ZERO-HOUR RESTORATION • WARRANTY PROTECTED',
        onScreenTextAr: 'تجديد شامل • ضمان معتمد',
        sfxMusic: 'Triumphant electronic beat climax.',
      },
    ],
    brollChecklist: [
      'Macro slow-motion oil pouring over clean camshaft lobes',
      'Electronic torque wrench digital beep readout showing 280 N·m',
      'Overview wide shot of clean, organized multi-bay Shuwaikh workshop',
    ],
    postProductionNotes: 'Cinematic color grade with deep blue shadows and bright amber highlights on tools.',
    captionEn: 'Factory-standard diagnostic equipment, Komatsu-certified master technicians, and genuine overhaul kits.\n\nStep inside the Dar Al Hay central service facility in Shuwaikh, Kuwait — where precision engineering restores your fleet to peak performance.',
    captionAr: 'أحدث أجهزة الفحص والتشخيص المعتمدة عالمياً، مع كادر فني معتمد وقطع غيار أصلية 100%.\n\nنظرة من داخل مركز صيانة دار الحي الرئيسي بالشويخ.. حيث نعيد أسطولك إلى قمة الجاهزية والإنتاجية.',
    hashtags: '#DarAlHayWorkshop #KomatsuService #EngineOverhaul #HeavyMachineryWorkshop #KuwaitEngineering #Shuwaikh',
    ctaText: 'Schedule a certified workshop overhaul or comprehensive diagnostic inspection for your fleet.',
    slides: [],
  },
  {
    id: 7,
    conceptNumber: 7,
    week: 'Week 3',
    day: 'Sunday',
    publishDate: '2026-09-13',
    title: 'Meet the Team – Service Engineer Field Spotlight',
    pillar: 'pillar_workshop',
    format: 'photography',
    platforms: ['linkedin', 'facebook', 'instagram'],
    goal: 'trust_humanize',
    status: 'idea',
    targetAudience: 'Fleet Owners, Contractors, Industry Peers',
    tov: 'Personal, Respectful, Professional & Inspiring',
    summary: 'Professional environmental portrait of certified service engineer standing next to a Komatsu machine with name, role, years of experience, and a quote on uptime.',
    hook: {
      spokenEn: 'Meet the engineers dedicated to keeping Kuwait’s heavy machinery fleets running without interruption.',
      spokenAr: 'تعرف على مهندسينا الملتزمين بالحفاظ على استمرارية عمل أساطيلكم في أصعب المواقع.',
      visualHook: 'Confident, high-contrast portrait of service engineer in safety helmet holding diagnostic tablet in front of a giant PC500 boom.',
    },
    scenes: [],
    brollChecklist: [
      'Environmental portrait with shallow depth of field (85mm f/1.8 lens)',
      'Engineer connecting diagnostic cable to machine interface port',
      'Engineer reviewing maintenance checklist with client site supervisor',
    ],
    postProductionNotes: 'Crisp editorial portrait lighting with clean Komatsu corporate colors.',
    captionEn: '"Preventive maintenance in Kuwait is not just about changing oil — it is about understanding how extreme heat and desert dust affect every hydraulic seal and cooling circuit."\n\nMeet our Field Service Engineering Team at Dar Al Hay Commercial Co.',
    captionAr: '"الصيانة الوقائية في الكويت ليست مجرد تغيير زيوت، بل هي فهم دقيق لتأثير الحرارة والغبار على كل دائرة هيدروليكية ونظام تبريد."\n\nفريق المهندسين في دار الحي بخبراتهم الميدانية يضمنون استمرار عمل أسطولك دون توقف.',
    hashtags: '#MeetTheTeam #DarAlHay #KomatsuEngineers #KuwaitProfessionals #HeavyEquipmentExperts #FieldEngineering',
    ctaText: 'Connect with our engineering team for specialized maintenance agreements.',
    slides: [],
  },
  {
    id: 8,
    conceptNumber: 8,
    week: 'Week 3',
    day: 'Tuesday',
    publishDate: '2026-09-15',
    title: 'Did You Know? – KOMTRAX Satellite Fleet Telemetry',
    pillar: 'pillar_engineering',
    format: 'designed_post',
    platforms: ['linkedin', 'instagram', 'facebook'],
    goal: 'product_education',
    status: 'idea',
    targetAudience: 'Fleet Managers, Operations Controllers, Tech-Savvy Contractors',
    tov: 'Smart, Innovative, Tech-Forward & Insightful',
    summary: 'Infographic highlighting KOMTRAX satellite tracking: remote SMR hours, fuel consumption alerts, location mapping, and error code monitoring right from your phone.',
    hook: {
      spokenEn: 'Did you know you can monitor your machine’s fuel burn, SMR hours, and health from your smartphone anywhere in Kuwait?',
      spokenAr: 'هل تعلم أنك تستطيع مراقبة استهلاك الوقود وساعات العمل وحالة معدتك من هاتفك أينما كنت في الكويت؟',
      visualHook: 'Futuristic graphic showing satellite connection beams connecting a 3D Komatsu machine to an iPhone KOMTRAX dashboard.',
    },
    scenes: [],
    brollChecklist: [
      'Close-up screen recording of live KOMTRAX app displaying machine location and fuel graph',
      'KOMTRAX satellite antenna mounted on excavator cab roof',
    ],
    postProductionNotes: 'High-contrast graphic design with glowing data nodes and sleek UI frames.',
    captionEn: 'KOMTRAX comes standard on modern Komatsu machinery, giving fleet managers in Kuwait real-time visibility into machine location, working vs idling hours, and upcoming service milestones.\n\n📊 Reduce idle fuel burn by up to 15% with data-driven fleet analytics.',
    captionAr: 'نظام KOMTRAX للأقمار الصناعية متوفر قياسياً في معدات كوماتسو الحديثة، ليوفر لمدراء الأساطيل رؤية شاملة لمواقع المعدات، ساعات العمل والتشغيل الفعلي، ومواعيد الصيانة الدورية.\n\n📊 وفّر حتى 15% من استهلاك الوقود عبر تحليلات التشغيل الذكية.',
    hashtags: '#KOMTRAX #FleetTelemetry #SmartMachinery #KomatsuTech #DarAlHay #IoTKuwait #FleetAnalytics',
    ctaText: 'Ask our technical team how to activate and optimize KOMTRAX monitoring for your Komatsu fleet.',
    slides: [],
  },
  {
    id: 9,
    conceptNumber: 9,
    week: 'Week 3',
    day: 'Thursday',
    publishDate: '2026-09-17',
    title: 'From Delivery to Worksite – New Asset Handover Journey',
    pillar: 'pillar_projects',
    format: 'reel',
    platforms: ['instagram', 'linkedin', 'facebook'],
    goal: 'case_study',
    status: 'idea',
    targetAudience: 'Prospective Buyers, Contractors, Fleet Supervisors',
    tov: 'Dynamic, Celebratory, Fast-Paced & Customer-Centric',
    summary: 'Fast-paced reel showing the journey of a brand new HM400: PDI inspection at facility -> loading onto heavy transporter -> convoy to desert site -> handover to client.',
    hook: {
      spokenEn: 'Watch a brand new 40-ton Komatsu dump truck make its journey to its new home in Kuwait.',
      spokenAr: 'شاهد رحلة شاحنة كوماتسو المفصلية HM400 الجديدة حتى وصولها لموقع العميل في الكويت.',
      visualHook: 'Massive heavy transport lowbed hauling a brand new Komatsu HM400 down Kuwait highway under clear blue sky.',
    },
    scenes: [
      {
        sceneNo: 1,
        time: '0:00 - 0:04',
        visual: 'PDI Pre-Delivery Inspection check in Shuwaikh yard: Engineer ticking off digital checklist, inspecting hydraulic fluids.',
        talentAction: 'Engineer removes protective transport wrap and applies certified Dar Al Hay PDI seal.',
        audioVoiceoverEn: 'Every new Komatsu machine undergoes comprehensive pre-delivery inspection before leaving our yard.',
        audioVoiceoverAr: 'تخضع كل معدة جديدة لفحص تسليم شامل وتوثيق دقيق قبل مغادرتها لموقع العمل.',
        onScreenTextEn: 'CERTIFIED PRE-DELIVERY INSPECTION (PDI)',
        onScreenTextAr: 'فحص ما قبل التسليم المعتمد',
        sfxMusic: 'Upbeat electronic momentum track.',
      },
      {
        sceneNo: 2,
        time: '0:04 - 0:10',
        visual: 'Heavy winch loading HM400 onto multi-axle heavy transport lowbed trailer; heavy chains securing wheels.',
        talentAction: 'Rigger tightening heavy ratchet binders with metallic clank.',
        audioVoiceoverEn: 'Safely secured and dispatched on specialized heavy haulage across Kuwait.',
        audioVoiceoverAr: 'نقل آمن وتوصيل فوري بأحدث شاحنات النقل الثقيل.',
        onScreenTextEn: 'SECURE HEAVY TRANSPORT ACROSS KUWAIT',
        onScreenTextAr: 'نقل ثقيل آمن لكافة مناطق الكويت',
        sfxMusic: 'Ratcheting metal foley sound effect.',
      },
      {
        sceneNo: 3,
        time: '0:10 - 0:18',
        visual: 'Convoy arrives at client desert earthworks site; ramps deployed and HM400 drives off smoothly under its own power.',
        talentAction: 'Machine rolls onto golden sand with zero hesitation; operator honks horn in celebration.',
        audioVoiceoverEn: 'Arriving on site fully commissioned, fueled, and ready for immediate operation.',
        audioVoiceoverAr: 'تصل جاهزة للعمل فوراً وبكامل طاقتها الإنتاجية.',
        onScreenTextEn: 'ON-SITE COMMISSIONING & HANDOVER',
        onScreenTextAr: 'تسليم وتشغيل فوري في الموقع',
        sfxMusic: 'High energy beat build-up.',
      },
      {
        sceneNo: 4,
        time: '0:18 - 0:25',
        visual: 'Dar Al Hay sales lead handing golden key and technical operation folder to client project manager; handshake in front of machine.',
        talentAction: 'Client smiling and walking around the machine with enthusiasm.',
        audioVoiceoverEn: 'Congratulations to our partners. Another heavy asset ready to build Kuwait.',
        audioVoiceoverAr: 'مبارك لشركائنا.. معدة جديدة تساهم في إعمار وتطوير مشاريع الكويت.',
        onScreenTextEn: 'CONGRATULATIONS TO OUR PARTNER',
        onScreenTextAr: 'نهنئ شركاءنا بالانضمام لأسطول كوماتسو',
        sfxMusic: 'Inspiring final melody.',
      },
    ],
    brollChecklist: [
      'Gimbal tracking shot alongside lowbed trailer during highway transport',
      'Close-up of golden Komatsu key and maintenance folder handover',
      'First dump body lift test on client site with dust rising',
    ],
    postProductionNotes: 'High-contrast commercial style edit with snappy sound design on each transport step.',
    captionEn: 'Another brand new Komatsu asset delivered ready for action! Complete PDI pre-delivery inspections conducted by Dar Al Hay certified technicians before reaching the client worksite in Kuwait.\n\n🚜 Discover our current available inventory for immediate delivery.',
    captionAr: 'تسليم معدة كوماتسو جديدة جاهزة لبدء العمل فوراً! فحص تسليم شامل وموثق لضمان أعلى جاهزية قبل وصول المعدة لموقع العميل في الكويت.\n\n🚜 اكتشف الآليات المتوفرة للتسليم الفوري لدى دار الحي.',
    hashtags: '#MachineDelivery #HM400 #KomatsuTruck #KuwaitContractors #DarAlHayDelivery #HeavyHaulage #KuwaitProjects',
    ctaText: 'Looking to expand your fleet? Contact us for immediate delivery timelines on available stock.',
    slides: [],
  },
  {
    id: 10,
    conceptNumber: 10,
    week: 'Week 4',
    day: 'Sunday',
    publishDate: '2026-09-20',
    title: 'Machine Explained – HM400 Articulated Dump Truck in Kuwait Sand',
    pillar: 'pillar_engineering',
    format: 'carousel',
    platforms: ['linkedin', 'instagram', 'facebook'],
    goal: 'product_education',
    status: 'idea',
    targetAudience: 'Earthmoving Contractors, Quarry Managers, Site Engineers',
    tov: 'Technical, Clear, Value-Driven & Educational',
    summary: '5-slide educational breakdown of the HM400: Articulated steering, payload capacity, Komatsu Traction Control System (KTCS), and desert ground clearance.',
    hook: {
      spokenEn: 'Why articulated dump trucks conquer sandy terrain where rigid trucks get stuck.',
      spokenAr: 'لماذا تتفوق الشاحنات المفصلية في الرمال الناعمة وتتجنب التغريز والتعطل؟',
      visualHook: 'Diagram showing HM400 center hitch oscillation keeping all 6 wheels grounded on uneven sand dune.',
    },
    scenes: [],
    brollChecklist: [
      'Articulated center hitch turning 45 degrees in action',
      'Tire tread comparison in soft sand',
      'Cockpit view showing KTCS traction button and retarder lever',
    ],
    postProductionNotes: '1080x1350 vertical slides with clear callouts and technical diagrams.',
    captionEn: 'Soft sand and uneven terrain demand superior traction. Here is why the Komatsu HM400 articulated dump truck is Kuwait’s top choice for coastal reclamation and desert hauling.\n\nSwipe through to inspect the engineering advantages ->',
    captionAr: 'التضاريس الرملية والأراضي الوعرة تتطلب نظام دفع متطور. إليك أسرار تفوق شاحنة كوماتسو المفصلية HM400 في مواقع الردم والإنشاءات بالكويت.\n\nاسحب الشاشة للتعرف على المزايا الهندسية ->',
    hashtags: '#HM400 #ArticulatedDumpTruck #KomatsuHaulers #KuwaitEarthmoving #KTCS #DarAlHay #TractionControl',
    ctaText: 'Swipe through to inspect the specs -> Share with your site engineers and plant managers.',
    slides: [
      { slideNo: 1, title: '40-Ton Heavy Duty Payload', body: 'Heaped body capacity of 24.0 m³ engineered to withstand abrasive desert rock and bulk earthmoving loads.' },
      { slideNo: 2, title: 'KTCS Intelligent Traction Control', body: 'Automatically senses wheel slip in soft sand and locks differential clutches without operator intervention.' },
      { slideNo: 3, title: 'Articulated Steering & Center Oscillation', body: 'Center hitch design allows 45° steering angle and keeps all 6 wheels grounded over severe bumps and dunes.' },
      { slideNo: 4, title: 'Desert Cooling & Oil-Cooled Brakes', body: 'Multi-disc wet brakes sealed against sand ingress, paired with a high-capacity radiator core.' },
      { slideNo: 5, title: 'Backed by Dar Al Hay in Kuwait', body: 'Guaranteed genuine parts, mobile lube trucks, and 24/7 emergency field technician support across Kuwait.' },
    ],
  },
  {
    id: 11,
    conceptNumber: 11,
    week: 'Week 4',
    day: 'Tuesday',
    publishDate: '2026-09-22',
    title: 'Field Maintenance Tip – Air Pre-Cleaner Desert Dust Protocol',
    pillar: 'pillar_engineering',
    format: 'reel',
    platforms: ['instagram', 'linkedin', 'facebook'],
    goal: 'expertise',
    status: 'idea',
    targetAudience: 'Machine Operators, Maintenance Foremen, Site Mechanics',
    tov: 'Practical, Hands-on, Helpful & Authoritative',
    summary: 'Service engineer demonstrates how to properly inspect and clean the pre-cleaner and primary air filters after sandstorm conditions in Kuwait.',
    hook: {
      spokenEn: '1 simple daily maintenance habit that can extend your heavy engine life by 5,000 hours in Kuwait.',
      spokenAr: 'فحص يومي بسيط لمدة دقيقتين يطيل عمر محرك ديزل معدتك 5,000 ساعة إضافية في الكويت.',
      visualHook: 'Engineer opens a dust bowl on an air pre-cleaner, pouring out fine desert sand, and holding up a clean genuine filter.',
    },
    scenes: [
      {
        sceneNo: 1,
        time: '0:00 - 0:04',
        visual: 'Engineer standing on excavator walkway next to air cleaner housing, addressing camera directly.',
        talentAction: 'Engineer unclips air filter canister cover with safety gloves.',
        audioVoiceoverEn: 'After a Kuwait sandstorm, this 2-minute daily check saves you thousands in engine overhauls.',
        audioVoiceoverAr: 'بعد موجات الغبار في الكويت، هذا الفحص البسيط لمدة دقيقتين يحمي محركك من التآكل وتكاليف التوضيب.',
        onScreenTextEn: '2-MINUTE DAILY AIR CLEANER PROTOCOL',
        onScreenTextAr: 'فحص فلتر الهواء اليومي في الكويت',
        sfxMusic: 'Snappy electronic beat.',
      },
      {
        sceneNo: 2,
        time: '0:04 - 0:10',
        visual: 'Close-up of cyclone pre-cleaner bowl showing accumulated sand particles.',
        talentAction: 'Engineer empties bowl and wipes seal with clean lint-free cloth.',
        audioVoiceoverEn: 'First: Empty the pre-cleaner centrifuge bowl before dust reaches the primary filter element.',
        audioVoiceoverAr: 'أولاً: تفريغ وعاء الفلتر الأولي (Pre-cleaner) بانتظام قبل وصول الغبار للفلتر الرئيسي.',
        onScreenTextEn: '1. EMPTY PRE-CLEANER CENTRIFUGE',
        onScreenTextAr: '1. تفريغ وعاء الفلتر الأولي',
        sfxMusic: 'Sand pouring foley sound.',
      },
      {
        sceneNo: 3,
        time: '0:10 - 0:17',
        visual: 'Demonstration of compressed air cleaning from INSIDE out at maximum 2.0 bar pressure.',
        talentAction: 'Engineer demonstrates correct nozzle angle to avoid tearing delicate filter paper.',
        audioVoiceoverEn: 'Second: Blow compressed air only from the inside out — never exceed 2 bar pressure to protect filter media.',
        audioVoiceoverAr: 'ثانياً: نفخ الهواء المضغوط من الداخل إلى الخارج فقط وبضغط لا يتجاوز 2 بار لحماية مسام الفلتر.',
        onScreenTextEn: '2. BLOW AIR FROM INSIDE-OUT (MAX 2 BAR)',
        onScreenTextAr: '2. تنظيف الهواء من الداخل للخارج (بأقصى حد 2 بار)',
        sfxMusic: 'Air hose hiss foley effect.',
      },
      {
        sceneNo: 4,
        time: '0:17 - 0:24',
        visual: 'Inspection light inserted inside filter checking for micro-tears or light pinholes.',
        talentAction: 'Engineer inspects glowing cylinder: "If you see a pinhole of light, replace immediately with genuine Komatsu filter."',
        audioVoiceoverEn: 'Third: Inspect with light. Any pinhole means instant replacement with genuine parts from Dar Al Hay.',
        audioVoiceoverAr: 'ثالثاً: فحص الفلتر بمصباح داخلي.. أي ثقب صغير يستدعي استبداله فوراً بفلتر أصلي من دار الحي.',
        onScreenTextEn: '3. INSPECT FOR MICRO-TEARS',
        onScreenTextAr: '3. فحص الإضاءة للتأكد من عدم وجود ثقوب',
        sfxMusic: 'High-tech confirmation chime.',
      },
    ],
    brollChecklist: [
      'Macro close-up of air cleaner safety indicator valve showing yellow vs red band',
      'Engineer sealing canister latches with satisfying snap sound',
    ],
    postProductionNotes: 'Add red warning indicators on incorrect methods (e.g. tapping filter on ground).',
    captionEn: 'Fine sand dust is the #1 cause of premature engine wear and turbocharger dusting in Kuwait.\n\nFollow this simple 3-step field maintenance protocol to protect your Komatsu diesel engines and keep fleet productivity at 100%.\n\n🚜 Save this reel for your site maintenance crew and operators.',
    captionAr: 'الغبار الناعم هو العدو الأول لمحركات الديزل وأنظمة التيربو في بيئة الكويت الصحراوية.\n\nاتبع هذه الخطوات الثلاث البسيطة لحماية محركات أسطولك وضمان استمرارية العمل بأعلى أداء.\n\n🚜 احفظ المنشور وشاركه مع مشرفي الصيانة والسائقين في موقعك.',
    hashtags: '#MaintenanceTips #EngineCare #KomatsuKuwait #AirFilterCare #FieldService #DarAlHay #FleetUptime',
    ctaText: 'Save this reel for your site operators and maintenance crew.',
    slides: [],
  },
  {
    id: 12,
    conceptNumber: 12,
    week: 'Week 4',
    day: 'Thursday',
    publishDate: '2026-09-24',
    title: 'Project Case Study – Marine Reclamation with 98% Uptime',
    pillar: 'pillar_projects',
    format: 'carousel',
    platforms: ['linkedin', 'facebook', 'instagram'],
    goal: 'case_study',
    status: 'idea',
    targetAudience: 'Major Contractors, Project Directors, Government Engineers',
    tov: 'Prestigious, Data-Driven, Authoritative & Results-Oriented',
    summary: 'Case study highlighting a major Kuwait coastal reclamation project: 15+ Komatsu machines working 20 hours a day with 98% fleet availability.',
    hook: {
      spokenEn: 'How 15 Komatsu machines maintained 98.2% uptime over 24 consecutive operating months in Kuwait.',
      spokenAr: 'كيف حافظ 15 حفاراً وشاحنة كوماتسو على نسبة جاهزية بلغت 98.2% لمدة سنتين متواصلتين في الكويت.',
      visualHook: 'Aerial overview photo of huge coastal reclamation canal with Komatsu excavators lined up along the water channel.',
    },
    scenes: [],
    brollChecklist: [
      'High-resolution drone panorama of marine earthworks project',
      'Excavator bucket scooping wet coastal sand with sea spray in background',
      'KOMTRAX uptime graph showing 98.2% green availability bar',
    ],
    postProductionNotes: 'Professional corporate case study slide deck with key metrics in prominent gold callouts.',
    captionEn: 'Marine salt, fine sand, and non-stop double shifts. Discover how Dar Al Hay’s dedicated field maintenance program (EQP) and 24/7 parts dispatch delivered 98.2% fleet availability for a premier Kuwait coastal contractor.\n\nRead the complete project breakdown in the carousel above ->',
    captionAr: 'بيئة بحرية، أملاح، وغبار على مدار الساعة. اكتشف كيف ساهم برنامج الصيانة الوقائية (EQP) والدعم الميداني من دار الحي في تحقيق نسبة جاهزية بلغت 98.2% في أحد أضخم مشاريع الردم الساحلي بالكويت.\n\nاقرأ تفاصيل دراسة الحالة في المنشور أعلاه ->',
    hashtags: '#KuwaitCaseStudy #MarineReclamation #KomatsuFleet #HighUptime #KuwaitMegaprojects #DarAlHay #AssetReliability',
    ctaText: 'Read the full case study on our LinkedIn page or request a customized fleet maintenance proposal for your project.',
    slides: [
      { slideNo: 1, title: 'The Kuwait Marine Challenge', body: 'Moving 5 million cubic meters of marine soil under tight contract deadlines with corrosive salt spray and double shifts.' },
      { slideNo: 2, title: 'The Komatsu Fleet Deployed', body: '15 units: PC500LC Excavators, HM400 Articulated Haulers, and D155A Heavy Bulldozers operating in concert.' },
      { slideNo: 3, title: 'The Dar Al Hay Maintenance Plan', body: 'Standardized 250-hour preventive intervals (EQP), weekly oil sampling (KOWA), and daily KOMTRAX telematics tracking.' },
      { slideNo: 4, title: 'The Proven Result', body: '98.2% fleet availability recorded over 24 consecutive months with zero critical pump or engine downtime.' },
      { slideNo: 5, title: 'Partner With Dar Al Hay for Your Next Tender', body: 'Contact our corporate fleet engineering division for customized maintenance service level agreements (SLA).' },
    ],
  },
];
