export const MEDIA_PLATFORMS = [
  { id: 'instagram', label: 'Instagram', icon: '📸', color: 'from-pink-500 to-purple-600', badgeTone: 'active' },
  { id: 'linkedin', label: 'LinkedIn', icon: '💼', color: 'from-blue-600 to-blue-800', badgeTone: 'info' },
  { id: 'facebook', label: 'Facebook', icon: '👥', color: 'from-blue-500 to-indigo-600', badgeTone: 'ready' },
];

export const FORMAT_TYPES = [
  { id: 'reel', label: 'Reels / Motion', icon: '🎬', tag: 'motion / BTS', color: 'bg-purple-100 text-purple-900 border-purple-300' },
  { id: 'carousel', label: 'Carousels', icon: '📑', tag: 'education / story', color: 'bg-indigo-100 text-indigo-900 border-indigo-300' },
  { id: 'photography', label: 'Photography', icon: '📸', tag: 'hero / people', color: 'bg-emerald-100 text-emerald-900 border-emerald-300' },
  { id: 'designed_post', label: 'Designed Post', icon: '🎨', tag: 'fact / graphic', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { id: 'cta_post', label: 'CTA Post', icon: '🎯', tag: 'lead generation', color: 'bg-rose-100 text-rose-900 border-rose-300' },
];

export const GOAL_TYPES = [
  { id: 'brand_awareness', label: 'Brand Awareness', color: 'bg-sky-50 text-sky-800 border-sky-200' },
  { id: 'product_education', label: 'Product Education', color: 'bg-indigo-50 text-indigo-800 border-indigo-200' },
  { id: 'lead_generation', label: 'Lead Generation', color: 'bg-rose-50 text-rose-800 border-rose-200' },
  { id: 'trust_humanize', label: 'Trust & Humanize', color: 'bg-emerald-50 text-emerald-800 border-emerald-200' },
  { id: 'case_study', label: 'Case Study / Social Proof', color: 'bg-amber-50 text-amber-800 border-amber-200' },
  { id: 'expertise', label: 'Technical Expertise', color: 'bg-purple-50 text-purple-800 border-purple-200' },
];

export const PIPELINE_STAGES = [
  { id: 'idea', label: 'Idea / Planned', icon: '💡', badgeTone: 'neutral' },
  { id: 'scripted', label: 'Scripted / Briefed', icon: '📝', badgeTone: 'info' },
  { id: 'production', label: 'Shoot / Design', icon: '🎬', badgeTone: 'warning' },
  { id: 'review', label: 'In Review', icon: '👀', badgeTone: 'yellow' },
  { id: 'ready', label: 'Ready / Scheduled', icon: '🚀', badgeTone: 'active' },
  { id: 'published', label: 'Published', icon: '✅', badgeTone: 'ready' },
];

export const DEFAULT_MEDIA_CONCEPTS = [
  {
    id: 1,
    conceptNumber: 1,
    title: 'Hero Machine – PC350LC-8M0 Cinematic Intro',
    format: 'reel',
    platforms: ['instagram', 'linkedin', 'facebook'],
    goal: 'brand_awareness',
    status: 'ready',
    publishDate: '2026-08-28',
    summary: 'Cinematic 20-30 sec introduction: Kuwait landscape -> Dar Al Hay facility -> Komatsu machines fleet -> workshop engine overhaul -> spare parts warehouse -> certified engineers -> brand logo.',
    hook: 'Built for the toughest desert terrain on earth. Meet Komatsu in Kuwait.',
    visualDirection: 'Fast-paced cinematic montage with 4K drone shots over Kuwait desert infrastructure, transitioning to macro mechanical shots inside the Dar Al Hay central workshop and parts warehouse.',
    audioBroll: 'Energetic cinematic percussion with low industrial sub-bass drops. Natural heavy engine rumble and hydraulic hiss sound effects.',
    captionEn: 'From desert megaprojects to precision infrastructure, Komatsu heavy machinery powers Kuwait’s progress. Backed by Dar Al Hay’s certified engineering excellence, 24/7 technical support, and genuine parts availability.\n\n🚜 Explore the Komatsu hydraulic excavator series built for high-ambient desert endurance.',
    captionAr: 'من المشاريع التنموية الكبرى إلى أدق أعمال البنية التحتية في الكويت، معدات كوماتسو تواصل العمل بأعلى كفاءة. بدعم متواصل من دار الحي، بفريق هندسي معتمد وقطع غيار أصلية متوفرة دائماً.\n\n🚜 اكتشف قوة الحفارات الهيدروليكية المصممة لتحمل أصعب الظروف المناخية في الكويت.',
    hashtags: '#Komatsu #DarAlHay #KuwaitConstruction #HeavyMachinery #Excavator #PC350LC #KuwaitEngineers #KuwaitProjects',
    ctaText: 'Visit our Shuwaikh showroom or contact our heavy equipment specialists today.',
    slides: [],
  },
  {
    id: 2,
    conceptNumber: 2,
    title: 'Service Tips – Dar Al Hay Complete Partnership',
    format: 'carousel',
    platforms: ['linkedin', 'instagram', 'facebook'],
    goal: 'brand_awareness',
    status: 'scripted',
    publishDate: '2026-08-30',
    summary: '5-slide carousel explaining the relationship between Dar Al Hay & Komatsu, services provided, industries served, and contact CTA.',
    hook: 'More than just heavy equipment: The full lifecycle partnership keeping Kuwait moving.',
    visualDirection: 'Clean corporate Komatsu aesthetic (navy slate & Komatsu amber yellow), high-resolution studio icons and on-site Kuwait photography.',
    audioBroll: 'N/A (Multi-slide carousel post)',
    captionEn: 'Behind every productive machine on Kuwait worksites is an engineering partnership built on trust. Here is how Dar Al Hay supports contractors and fleet owners from machine delivery to full lifecycle management.',
    captionAr: 'خلف كل معدة تعمل بكفاءة في مواقع الكويت شراكة هندسية مبنية على الثقة والاعتمادية. تعرف على كيفية دعم دار الحي للمقاولين وملاك الأساطيل من يوم التسليم وحتى الصيانة المستمرة.',
    hashtags: '#DarAlHay #KomatsuKuwait #FleetManagement #HeavyEquipmentSupport #KuwaitContractors #PreventiveMaintenance',
    ctaText: 'Swipe through to learn more -> Save this post for your fleet maintenance guide.',
    slides: [
      { slideNo: 1, title: 'Official Komatsu Distributor in Kuwait', body: 'Decades of engineering leadership delivering world-class Japanese heavy machinery.' },
      { slideNo: 2, title: 'What We Deliver', body: 'Hydraulic excavators, articulated dump trucks, wheel loaders, and heavy bulldozers tailored for high-ambient durability.' },
      { slideNo: 3, title: 'Industries We Power', body: 'Civil infrastructure, mega-highways, marine earthworks, quarrying, and desert reclamation.' },
      { slideNo: 4, title: 'Comprehensive Care', body: 'Certified field service engineers, preventive maintenance intervals (EQP), and KOMTRAX telemetry.' },
      { slideNo: 5, title: 'Partner With Dar Al Hay', body: 'Contact our heavy equipment team to schedule your fleet inspection or request a quote.' },
    ],
  },
  {
    id: 3,
    conceptNumber: 3,
    title: 'Hero Machine on Site – Low-Angle Power Shot',
    format: 'photography',
    platforms: ['instagram', 'linkedin', 'facebook'],
    goal: 'brand_awareness',
    status: 'production',
    publishDate: '2026-09-02',
    summary: 'Powerful low-angle environmental photograph of a Komatsu PC500LC / D155A operating at Sabah Al-Ahmad Sea City with golden hour sunset lighting.',
    hook: 'Power meets precision in Kuwait’s golden hour.',
    visualDirection: 'Ultra-wide 24mm low-angle shot, golden hour desert dust rim-lighting, sharp track detail and massive boom scale.',
    audioBroll: 'Ambient desert wind audio track with subtle Komatsu engine hum.',
    captionEn: 'Built to dominate heavy excavation in 50°C+ summer heat. The Komatsu PC500LC delivers relentless breakout force with advanced fuel efficiency.\n\n📍 On site in South Kuwait.',
    captionAr: 'مصممة للعمل الشاق في درجات حرارة تتجاوز 50 درجة مئوية. حفارة كوماتسو PC500LC تمنحك أقصى قوة حفر مع كفاءة استثنائية في استهلاك الوقود.\n\n📍 موقع العمل - جنوب الكويت.',
    hashtags: '#Komatsu #PC500LC #HeavyEquipmentPhotography #KuwaitConstruction #DesertEarthworks #DarAlHay',
    ctaText: 'Follow @DarAlHayKuwait for daily machinery operations from Kuwait mega-projects.',
    slides: [],
  },
  {
    id: 4,
    conceptNumber: 4,
    title: 'Why Genuine Komatsu Parts? – The True Cost of Cheap Parts',
    format: 'carousel',
    platforms: ['linkedin', 'facebook', 'instagram'],
    goal: 'product_education',
    status: 'scripted',
    publishDate: '2026-09-04',
    summary: 'Explaining genuine parts reliability, exact tolerances, desert heat filtration, warranty protection, and long-term lifecycle savings.',
    hook: 'Are non-genuine parts costing you thousands in downtime? Here is the proof.',
    visualDirection: 'Side-by-side comparison graphics: Genuine Komatsu filter vs counterfeit aftermarket filter, showing micron filtration efficiency.',
    audioBroll: 'N/A (Multi-slide carousel post)',
    captionEn: 'In Kuwait’s fine sand and extreme summer temperatures, a substandard hydraulic filter or seal can cause catastrophic pump failure in under 200 operating hours. Protect your investment with 100% genuine Komatsu components from Dar Al Hay.',
    captionAr: 'في بيئة العمل الصحراوية والحرارة الشديدة بالكويت، استخدام فلاتر أو موانع تسرب غير أصلية قد يسبب أعطالاً مفاجئة في المضخات الهيدروليكية. احمِ استثمارك بقطع غيار كوماتسو الأصلية من دار الحي.',
    hashtags: '#GenuineParts #KomatsuParts #DarAlHay #FleetMaintenance #HydraulicFilters #PreventiveMaintenance',
    ctaText: 'Order genuine parts directly through our Shuwaikh central warehouse.',
    slides: [
      { slideNo: 1, title: 'The Desert Filtration Challenge', body: 'Kuwait sand particles measure down to 5 microns. Aftermarket filters let 40% of micro-debris pass into your hydraulic circuit.' },
      { slideNo: 2, title: 'Micro-Glass Filter Media', body: 'Genuine Komatsu filters feature multi-layered synthetic micro-glass for 99.8% contaminant capture.' },
      { slideNo: 3, title: 'High-Temperature Oil Seals', body: 'Formulated to withstand 120°C continuous oil temperatures without hardening or leaking.' },
      { slideNo: 4, title: 'Zero Warranty Risks', body: 'Genuine parts keep your factory warranty intact and preserve maximum resale asset value.' },
      { slideNo: 5, title: 'Immediate Availability in Kuwait', body: 'Direct access to over 15,000 genuine part lines at Dar Al Hay central inventory.' },
    ],
  },
  {
    id: 5,
    conceptNumber: 5,
    title: 'Machine Walkaround – WA600 / PC500 Heavy Specs',
    format: 'reel',
    platforms: ['instagram', 'linkedin', 'facebook'],
    goal: 'product_education',
    status: 'production',
    publishDate: '2026-09-06',
    summary: 'Service Engineer walks around the WA600 Wheel Loader and explains 3 critical design advantages for Kuwait quarry & earthmoving operations.',
    hook: '3 reasons why contractors choose the Komatsu WA600 for heavy sand and quarry loading in Kuwait.',
    visualDirection: 'Dynamic handheld camera tracking with the engineer pointing directly to the reinforced bucket linkage, high-capacity cooling radiator, and ergonomic cab.',
    audioBroll: 'Wireless lapel microphone for clear engineer voiceover, soft background workshop atmosphere.',
    captionEn: 'Join our service engineer for a technical walkaround of the powerhouse Komatsu WA600. Engineered for massive bucket payloads, rapid cycle times, and operator comfort in extreme climates.',
    captionAr: 'جولة تقنية سريعة مع مهندس الصيانة للتعرف على مميزات لودر كوماتسو WA600 العملاق. مصمم خصيصاً للتحميل الثقيل وسرعة الأداء في أصعب مواقع العمل بالكويت.',
    hashtags: '#KomatsuWA600 #WheelLoader #EarthmovingKuwait #DarAlHayEngineering #HeavyMachineryWalkaround',
    ctaText: 'Comment "WA600" to receive the full technical spec sheet and load capacity chart.',
    slides: [],
  },
  {
    id: 6,
    conceptNumber: 6,
    title: 'Inside Our Workshop – Engine & Component Overhaul',
    format: 'reel',
    platforms: ['linkedin', 'instagram', 'facebook'],
    goal: 'trust_humanize',
    status: 'idea',
    publishDate: '2026-09-09',
    summary: 'BTS inside the Dar Al Hay central workshop: diagnostic computers, cylinder honing, injector calibration, and precision torque wrenching.',
    hook: 'Behind the scenes where million-dollar heavy machines get restored to factory zero-hour precision.',
    visualDirection: 'Cinematic slow-motion B-roll: oil pressure testing, digital torque readouts, glowing parts cleaning tanks, and calibrated valve adjustments.',
    audioBroll: 'Rhythmic mechanical sounds, metal clicking, hydraulic pressurization, accompanied by upbeat electronic music.',
    captionEn: 'Factory-standard diagnostic equipment, Komatsu-certified master technicians, and genuine overhaul kits. Step inside the Dar Al Hay service facility in Kuwait.',
    captionAr: 'أحدث أجهزة الفحص والتشخيص المعتمدة عالمياً، مع كادر فني مدرب على أعلى مستوى. نظرة من داخل مركز صيانة دار الحي المعتمد لكوماتسو بالكويت.',
    hashtags: '#DarAlHayWorkshop #KomatsuService #EngineOverhaul #HeavyMachineryWorkshop #KuwaitEngineering',
    ctaText: 'Schedule a certified workshop overhaul or diagnostic inspection for your fleet.',
    slides: [],
  },
  {
    id: 7,
    conceptNumber: 7,
    title: 'Meet the Team – Engineer Spotlight',
    format: 'photography',
    platforms: ['linkedin', 'facebook', 'instagram'],
    goal: 'trust_humanize',
    status: 'idea',
    publishDate: '2026-09-12',
    summary: 'Professional environmental portrait of certified service engineer standing next to a Komatsu machine with name, role, years of experience, and a quote on uptime.',
    hook: 'Meet the engineers dedicated to keeping Kuwait’s heavy machinery fleets running without interruption.',
    visualDirection: 'Clean shallow depth-of-field portrait with Komatsu machine in soft background, safety PPE, confidence and craftsmanship.',
    audioBroll: 'N/A',
    captionEn: '"Preventive maintenance in Kuwait is not just about changing oil — it is about understanding how extreme heat and desert dust affect every hydraulic seal and cooling circuit."\n\nMeet our Service Engineering Team at Dar Al Hay.',
    captionAr: '"الصيانة الوقائية في الكويت ليست مجرد تغيير زيوت، بل هي فهم دقيق لتأثير الحرارة والغبار على كل دائرة هيدروليكية ونظام تبريد."\n\nفريق المهندسين في دار الحي بخبراتهم الميدانية يضمنون استمرار عمل أسطولك.',
    hashtags: '#MeetTheTeam #DarAlHay #KomatsuEngineers #KuwaitProfessionals #HeavyEquipmentExperts',
    ctaText: 'Connect with our engineering team for specialized maintenance agreements.',
    slides: [],
  },
  {
    id: 8,
    conceptNumber: 8,
    title: 'Did You Know? – KOMTRAX Fleet Telemetry',
    format: 'designed_post',
    platforms: ['linkedin', 'instagram', 'facebook'],
    goal: 'product_education',
    status: 'idea',
    publishDate: '2026-09-15',
    summary: 'Infographic highlighting KOMTRAX satellite tracking: remote SMR hours, fuel consumption alerts, location mapping, and error code monitoring right from your phone.',
    hook: 'Did you know you can monitor your machine’s fuel burn, SMR hours, and health from your smartphone?',
    visualDirection: 'High-contrast graphic design featuring a 3D Komatsu excavator connected to digital satellite telemetry waves and smartphone interface.',
    audioBroll: 'N/A',
    captionEn: 'KOMTRAX comes standard on modern Komatsu machinery, giving fleet managers in Kuwait real-time visibility into machine location, working vs idling hours, and upcoming service milestones.',
    captionAr: 'هل تعلم أن نظام KOMTRAX يتيح لك مراقبة موقع معدتك، ساعات العمل الفعلية، واستهلاك الوقود مباشرة من هاتفك الذكي؟ تقنية ذكية لإدارة الأساطيل بأعلى كفاءة.',
    hashtags: '#KOMTRAX #FleetTelemetry #SmartMachinery #KomatsuTech #DarAlHay #IoTKuwait',
    ctaText: 'Ask our team how to activate KOMTRAX monitoring for your Komatsu machines.',
    slides: [],
  },
  {
    id: 9,
    conceptNumber: 9,
    title: 'From Delivery to Worksite – New Asset Handover',
    format: 'reel',
    platforms: ['instagram', 'linkedin', 'facebook'],
    goal: 'case_study',
    status: 'idea',
    publishDate: '2026-09-18',
    summary: 'Fast-paced reel showing the journey of a brand new HM400: PDI inspection at facility -> loading onto heavy transporter -> convoy to desert site -> handover to client.',
    hook: 'Watch a brand new 40-ton Komatsu dump truck make its journey to its new home in Kuwait.',
    visualDirection: 'Smooth gimbal shots of strapping down wheels, highway transport, unloading on site, engine start-up, and client handover handshake.',
    audioBroll: 'Uplifting commercial tech music with transport ambient sounds.',
    captionEn: 'Another brand new Komatsu asset delivered ready for action. Complete PDI pre-delivery inspections conducted by Dar Al Hay before reaching the client worksite.',
    captionAr: 'تسليم معدة جديدة جاهزة لبدء العمل فوراً! فحص تسليم شامل وموثق لضمان أعلى جاهزية قبل وصول المعدة لموقع العميل في الكويت.',
    hashtags: '#MachineDelivery #HM400 #KomatsuTruck #KuwaitContractors #DarAlHayDelivery #HeavyHaulage',
    ctaText: 'Looking to expand your fleet? Contact us for delivery timelines on current stock.',
    slides: [],
  },
  {
    id: 10,
    conceptNumber: 10,
    title: 'Machine Explained – HM400 Articulated Dump Truck',
    format: 'carousel',
    platforms: ['linkedin', 'instagram', 'facebook'],
    goal: 'product_education',
    status: 'idea',
    publishDate: '2026-09-21',
    summary: '5-slide educational breakdown of the HM400: Articulated steering, payload capacity, Komatsu Traction Control System (KTCS), and desert ground clearance.',
    hook: 'Why articulated dump trucks conquer sandy terrain where rigid trucks get stuck.',
    visualDirection: 'Blueprint-style graphics with real action photography of the HM400 hauling rocky material.',
    audioBroll: 'N/A',
    captionEn: 'Soft sand and uneven terrain demand superior traction. Here is why the Komatsu HM400 articulated dump truck is Kuwait’s top choice for coastal and desert hauling.',
    captionAr: 'التضاريس الرملية والأراضي الوعرة تتطلب نظام دفع متطور. إليك أسرار تفوق شاحنة كوماتسو المفصلية HM400 في مواقع الردم والإنشاءات بالكويت.',
    hashtags: '#HM400 #ArticulatedDumpTruck #KomatsuHaulers #KuwaitEarthmoving #KTCS #DarAlHay',
    ctaText: 'Swipe through to inspect the specs -> Share with your site engineers.',
    slides: [
      { slideNo: 1, title: '40-Ton Heavy Payload', body: 'Engineered for high-volume earthmoving with a 24.0 m³ heaped body capacity.' },
      { slideNo: 2, title: 'KTCS Traction Control', body: 'Automatically senses wheel slip in soft Kuwait sand and locks differentials without operator intervention.' },
      { slideNo: 3, title: 'Articulated Steering & Oscillation', body: 'Center hitch design keeps all 6 wheels grounded over severe bumps and slopes.' },
      { slideNo: 4, title: 'Desert Cooling Package', body: 'Heavy-duty hydraulic fan with automatic reverse mode to purge sand dust from radiator cores.' },
      { slideNo: 5, title: 'Supported by Dar Al Hay', body: 'Guaranteed genuine parts and 24/7 emergency field technician support in Kuwait.' },
    ],
  },
  {
    id: 11,
    conceptNumber: 11,
    title: 'Field Maintenance Tip – Desert Dust Protection',
    format: 'reel',
    platforms: ['instagram', 'linkedin', 'facebook'],
    goal: 'expertise',
    status: 'idea',
    publishDate: '2026-09-24',
    summary: 'Service engineer demonstrates how to properly inspect and clean the pre-cleaner and primary air filters after sandstorm conditions in Kuwait.',
    hook: '1 quick maintenance habit that extends your heavy machine engine life by 5,000 hours in Kuwait.',
    visualDirection: 'Close-up camera on engineer removing pre-cleaner bowl, showing dust accumulation, and demonstrating reverse compressed air cleaning technique.',
    audioBroll: 'Clear voiceover with air hose sound effects.',
    captionEn: 'Dust is the number one enemy of heavy diesel engines in the GCC. Follow this quick 2-minute daily check to safeguard your turbocharger and piston rings.',
    captionAr: 'الغبار هو العدو الأول لمحركات الديزل في بيئة الخليج. شاهد هذا الفحص البسيط لمدة دقيقتين لحماية المحرك والتيربو من التآكل المبكر.',
    hashtags: '#MaintenanceTips #EngineCare #KomatsuKuwait #AirFilterCare #FieldService #DarAlHay',
    ctaText: 'Save this reel for your site operators and maintenance crew.',
    slides: [],
  },
  {
    id: 12,
    conceptNumber: 12,
    title: 'Project Case Study – Marine Reclamation with Komatsu',
    format: 'carousel',
    platforms: ['linkedin', 'facebook', 'instagram'],
    goal: 'case_study',
    status: 'idea',
    publishDate: '2026-09-26',
    summary: 'Case study highlighting a major Kuwait coastal reclamation project: 15+ Komatsu machines working 20 hours a day with 98% fleet availability.',
    hook: 'How 15 Komatsu machines maintained 98% uptime in a 24-month coastal reclamation project in Kuwait.',
    visualDirection: 'High impact project photos: Sea City water channels, bulk material moving, night shift operations with floodlights.',
    audioBroll: 'N/A',
    captionEn: 'Marine salt, fine sand, and non-stop double shifts. Discover how Dar Al Hay’s dedicated field maintenance program kept the equipment operating at peak productivity.',
    captionAr: 'بيئة بحرية، أملاح، وغبار على مدار الساعة. اكتشف كيف ساهم برنامج الصيانة الوقائية من دار الحي في تحقيق نسبة جاهزية بلغت 98% في مشروع ساحلي ضخم بالكويت.',
    hashtags: '#KuwaitCaseStudy #MarineReclamation #KomatsuFleet #HighUptime #KuwaitMegaprojects #DarAlHay',
    ctaText: 'Read the full case study on our LinkedIn page or request a customized fleet maintenance proposal.',
    slides: [
      { slideNo: 1, title: 'The Challenge', body: 'Moving 5 million cubic meters of marine soil under tight deadlines in saline coastal conditions.' },
      { slideNo: 2, title: 'The Fleet Deployed', body: '15 Komatsu PC500LC Excavators, HM400 Dump Trucks, and D155A Bulldozers.' },
      { slideNo: 3, title: 'The Maintenance Protocol', body: 'Standardized 250-hour periodic services (EQP) with scheduled oil sampling and daily KOMTRAX monitoring.' },
      { slideNo: 4, title: 'The Result', body: '98.2% fleet availability recorded over 24 consecutive operating months.' },
      { slideNo: 5, title: 'Your Project Next', body: 'Partner with Dar Al Hay for heavy equipment reliability on your next tender.' },
    ],
  },
  {
    id: 13,
    conceptNumber: 13,
    title: 'Parts Department & Fast Dispatch in Kuwait',
    format: 'photography',
    platforms: ['instagram', 'linkedin', 'facebook'],
    goal: 'lead_generation',
    status: 'idea',
    publishDate: '2026-09-28',
    summary: 'Visual photo gallery of the modern Dar Al Hay central parts logistics center in Shuwaikh, highlighting same-day site dispatch across Kuwait.',
    hook: 'Why wait weeks for parts when you can get genuine Komatsu spares dispatched same-day in Kuwait?',
    visualDirection: 'Clean organized warehouse aisles, barcoded genuine Komatsu packaging, parts specialists preparing dispatch crates.',
    audioBroll: 'N/A',
    captionEn: 'Every hour of downtime costs money. Dar Al Hay maintains an extensive multi-million inventory of genuine filters, hoses, pumps, ground engaging tools, and undercarriage components right here in Kuwait.',
    captionAr: 'كل ساعة توقف تكلف أموالاً. توفر دار الحي مخزوناً ضخماً من قطع غيار كوماتسو الأصلية، من الفلاتر والسيور إلى المضخات وسلاسل الجنازير، مع توصيل فوري لمواقع العمل.',
    hashtags: '#KomatsuParts #SparePartsKuwait #SameDayDispatch #HeavyEquipmentParts #DarAlHayLogistics',
    ctaText: 'Call our parts counter on WhatsApp or visit our central Shuwaikh warehouse.',
    slides: [],
  },
  {
    id: 14,
    conceptNumber: 14,
    title: 'Built for Kuwait – Desert Heat Testing',
    format: 'reel',
    platforms: ['instagram', 'linkedin', 'facebook'],
    goal: 'brand_awareness',
    status: 'idea',
    publishDate: '2026-09-29',
    summary: 'Fast-cut cinematic reel showcasing Komatsu cooling systems, dust seals, and high-spec cabins operating effortlessly in extreme Kuwait midday temperatures.',
    hook: 'When Kuwait reaches 52°C, these machines don’t stop. Here’s why.',
    visualDirection: 'Heat haze distortion effects, intense sun flare, machine cutting through rock, close-up of air conditioned cab with temperature gauge readout.',
    audioBroll: 'Deep bass pulse with crisp ambient machinery sound design.',
    captionEn: 'Engineered in Japan, proven in Kuwait. Komatsu heavy equipment features specialized high-ambient cooling radiators and pressurized cabs built specifically for desert climates.',
    captionAr: 'هندسة يابانية أثبتت جدارتها في مناخ الكويت. رادياتيرات فائقة التحمل وكبائن مكيفة ومضغوطة لمنع دخول الغبار لأقصى راحة وإنتاجية.',
    hashtags: '#BuiltForKuwait #DesertMachinery #HighHeatPerformance #KomatsuTough #DarAlHay',
    ctaText: 'Experience Japanese engineering excellence with Dar Al Hay.',
    slides: [],
  },
  {
    id: 15,
    conceptNumber: 15,
    title: 'Complete Dar Al Hay Support Ecosystem',
    format: 'carousel',
    platforms: ['linkedin', 'facebook', 'instagram'],
    goal: 'lead_generation',
    status: 'idea',
    publishDate: '2026-08-31',
    summary: 'Full-funnel carousel presenting the 360-degree Dar Al Hay offering: Equipment Sales -> Genuine Parts -> Mobile Field Service -> Telemetry -> Certified Overhauls.',
    hook: 'Everything your heavy machinery fleet needs under one certified roof in Kuwait.',
    visualDirection: 'Polished brand infographic carousel with clear iconography, phone mockups, and customer testimonial quotes.',
    audioBroll: 'N/A',
    captionEn: 'Looking for a reliable heavy equipment partner in Kuwait? From equipment acquisition to complete lifecycle maintenance and telemetry tracking, Dar Al Hay has you covered.\n\n📞 Contact our team today to discuss your fleet requirements.',
    captionAr: 'هل تبحث عن شريك موثوق للمعدات الثقيلة في الكويت؟ من توريد الآليات وقطع الغيار إلى الصيانة الميدانية المتنقلة، دار الحي معك في كل خطوة.\n\n📞 تواصل معنا اليوم لمعرفة عروض الأساطيل وعقود الصيانة.',
    hashtags: '#DarAlHay #KomatsuKuwait #FleetSolutions #HeavyMachineryPartner #KuwaitConstructionLeader',
    ctaText: 'Contact our team via phone or direct message to get started.',
    slides: [
      { slideNo: 1, title: '1. Machinery Sales & Fleet Leasing', body: 'New and certified Komatsu excavators, loaders, articulated haulers, and bulldozers.' },
      { slideNo: 2, title: '2. 100% Genuine Spare Parts', body: 'Over 15,000 line items stocked locally in Kuwait for immediate dispatch.' },
      { slideNo: 3, title: '3. 24/7 Mobile Field Service', body: 'Fully equipped service trucks and certified field technicians ready for on-site interventions.' },
      { slideNo: 4, title: '4. Digital Fleet Telematics (KOMTRAX)', body: 'Real-time location, SMR monitoring, and predictive failure alerts.' },
      { slideNo: 5, title: '5. Certified Major Overhauls', body: 'State-of-the-art Shuwaikh central workshop for engines, transmissions, and hydraulic pumps.' },
    ],
  },
];
